# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 1321–1650 (koščatost … monarhinja).

DEC = {
 'koščatost': 'Osobina, svojstvo onoga koji je koščat, onoga što je koščato.',
 'koščina': 'Uvećanica i pežorativ od koska i kost.',
 'koščurina': 'Uvećanica i pežorativ od koska, kost i koščura.',
 'kožarstvo': 'Kožarski zanat; proizvodnja kože.',
 'kraguljac': 'Vrsta sokola, soko lastavičar, obično u izrazu „soko kraguljac"; i lovni soko ili jastreb (zool.).',
 'krahirati': 'Doživeti, pretrpeti krah, propasti; bankrotirati (ustanak je krahirao; trgovinska firma je krahirala).',
 'kraljić': 'Umanjenica i nežni oblik od kralj; i kralj, vladar male, neznatne države; i kraljević, princ; zool. mala ptica pevačica (vatroglavi kraljić).',
 'krampati': 'Raditi krampom (kopati i dr.).',
 'kratkodlak': 'Koji ima kratku dlaku, obično o psu (nemački kratkodlaki ptičar).',
 'kratkoprugaš': 'Atletičar koji se takmiči na kratkim stazama, naročito na 100 ili 200 m (sport).',
 'kraš': 'Kras, karst, krš.',
 'krepalina': 'Telo uginule životinje, strvina, lešina; meso uginule životinje; pežorativno: veoma mršava, slaba, iznemogla, bolesna životinja, mrcina; i mlitava, bezvoljna, veoma lenja osoba.',
 'kreposnica': 'Žena, devojka visokog morala, ona koja je kreposna, puna vrlina, časna, uzorna.',
 'krevetina': 'Pežorativno od krevet.',
 'krezubina': 'Deo vilice na kojem više nema zuba, mesto na kojem je bio zub.',
 'krimen': 'Zločin (lat.).',
 'kristalić': 'Umanjenica od kristal (kristalići nišadora).',
 'kristaličan': 'Kristalan, kristalast.',
 'krivač': 'Oboleo, zakržljao, deformisan plod šljive grašastog, pasuljastog oblika; i gljivica koja izaziva takvu deformaciju ploda.',
 'krivokletno': 'Krivo, lažno se zaklinjući.',
 'krizmati': 'Izvršiti obred krizme nad nekim; preneseno: (is)tući, (iz)udarati; (krizmati se) biti izložen obredu krizme, primiti, primati, dobijati krizmu.',
 'kričavost': 'Osobina onoga što je kričavo, onoga koji je kričav; kreštavost.',
 'krmačina': 'Uvećanica ili pežorativ od krmača.',
 'kroatistika': 'Nauka o hrvatskom jeziku i hrvatskoj književnosti; uporedi serbokroatistika.',
 'kroatizirati': 'Učiniti Hrvatom, odnosno Hrvatima; učiniti hrvatskim, da(va)ti nečemu hrvatska obeležja, svojstva, karakteristike (kroatizirati tekst); (kroatizirati se) postajati Hrvat(om), pohrvatiti se.',
 'krstarički': 'Koji se odnosi na krstarice (krstarička flotila).',
 'krstoplet': 'Unakrsno vezivanje (arh.).',
 'kruhoborac': 'Onaj koji stalno trči za zaradom, onaj koji ne bira sredstva da bi zaradio (obično pežorativno ili ironično).',
 'krunidben': 'Koji se odnosi na krunidbu, krunisanje (krunidbena svečanost).',
 'krunište': 'Zidčasti grudobran povrh spoljne strane bedema ili kule, obično srednjovekovne.',
 'kruškovac': 'Slatkasto alkoholno piće, liker od krušaka.',
 'kruškovina': 'Kruškovo drvo (kao građa, materijal).',
 'krvnica': 'Ženska osoba ubica; svirepa, surova, okrutna ženska osoba.',
 'krvoliptanje': 'Brzo, obilno krvarenje.',
 'krvoločnost': 'Osobina onoga koji je krvoločan, krvožednost (krvoločnost zveri, neprijatelja).',
 'krvoslednik': 'Vrsta lovačkog psa koji sledi krvavi trag i tako pronalazi ranjenu divljač.',
 'krznarstvo': 'Izrada i prerada krzna, krznene robe (krznarski zanat ili krznarska industrija).',
 'krznaš': 'Životinja sa krznom (obično u množini).',
 'krčmetina': 'Uvećanica i pežorativ od krčma.',
 'krševitost': 'Osobina i stanje onoga što je krševito (krševitost terena).',
 'krštenik': 'Onaj koji je kršten, krštena muška osoba; hrišćanin; i muško kumče.',
 'kržljavac': 'Onaj koji je kržljav, zakržljao.',
 'kržljavost': 'Osobina i stanje onoga koji je kržljav, onoga što je kržljavo; zakržljalost.',
 'ksenofob': 'Onaj koji mrzi strance i sve što je strano; i onaj koji se boji stranaca, tuđinaca, stranih, tuđinskih uticaja i dr.',
 'kudeljast': 'Koji je kao kudelja, sličan kudelji (kudeljasta brada, kosa).',
 'kudra': 'Pramen kudrave, kovrdžave kose ili dlake, kovrdža.',
 'kudravac': 'Onaj koji je kudrav.',
 'kudrica': 'Umanjenica i nežni oblik od kudra; kudra.',
 'kudro': 'Nežni oblik od kudrov; kudrov, kudravko.',
 'kukičati': 'Kukicom izrađivati čipku ili neki drugi ručni rad, heklati.',
 'kukuriknuti': 'Svršeni oblik glagola „kukurikati" (kukureknuti).',
 'kulašić': 'Umanjenica i nežni oblik od kulaš.',
 'kumulativan': 'Zbirni, ukupan, sveukupan (kumulativni obračun).',
 'kumulativno': 'Zajedno s nečim drugim, ujedno; u opštem zbiru, ukupno (kumulativno obračunati doprinose).',
 'kumulonimbus': 'Vrsta oblaka sličnog planini, svetlog vrha i tamnog ravnog podnožja, koji donosi pljusak s grmljavinom (često i s gradom) ili gusti sneg (met., lat.).',
 'kunar': 'Lovac na kune; i vrsta lovačkog psa obučenog za lov na kune.',
 'kunićarstvo': 'Gajenje kunića; privredna grana čija je delatnost gajenje kunića.',
 'kupaonica': 'Prostorija za kupanje; uporedi kupatilo.',
 'kupaža': 'Mešanje različitih vina ili više vrsta nekog drugog alkoholnog pića; razblaživanje, razređivanje pića (fr.).',
 'kupolast': 'Koji ima oblik kupole, sličan kupoli (kupolasta krošnja, oblik).',
 'kupolica': 'Umanjenica od kupola.',
 'kurativa': 'Nega, lečenje bolesnika.',
 'kurent': 'Način pisanja rukom, izgled rukom pisanih, povezanih slova; štamp. obična tipografska mala slova (za razliku od verzala, kurziva i dr.).',
 'kurirka': 'Ženska osoba kurir.',
 'kurkumin': 'Žuta kristalna materija, sastojak kurkume.',
 'kustoda': 'U starim štampanim (ponekad i rukopisnim) knjigama: brojka, prva reč ili slog početka sledeće strane, ispisani na kraju prethodne; muz. znak na kraju retka u notnom pismu koji označava prvu notu u sledećem retku (ital.).',
 'kusturina': 'Uvećanica i pežorativ od kustura.',
 'kutikula': 'Rožnati zaštitni sloj koji pokriva telo nekih beskicmenjaka, zglavkara, crva i dr. (anat.); bot. zaštitna tanka opna koja pokriva ćelijske membrane epiderma kod biljaka (lat.).',
 'kučište': 'Uvećanica i pežorativ od kuče.',
 'kučkin': 'Koji pripada kučki, koji se odnosi na kučku; u izrazu „kučkin sin (dete)" — pežorativno: gad, niškov.',
 'kušak': 'Pojas kao deo narodne nošnje; i šal kao deo muške narodne nošnje; i gredica, prečaga na vratnicama i dr., kosnik; i zapor, zavoranj, zasovnica (tur.).',
 'kušaonica': 'Ono što stavlja nekoga na probu, na iskušenje.',
 'kuštravac': 'Onaj koji ima bujnu kovrdžavu, kudravu ili razbarušenu kosu.',
 'kuštro': 'Isto što i kuštravac.',
 'kvadar': 'Geometrijsko telo ograničeno sa šest pravougaonika; predmet takvog oblika (ital.).',
 'kvantitativno': 'U pogledu kvantiteta, po kvantitetu (kvantitativno ispitati, veliki broj).',
 'kvarat': 'Četvrti deo neke mere — kilograma, litra, časa i sl. (kvarat žita, rakije); i stara mera za dužinu (lat.).',
 'kvartar': 'Najmlađe razdoblje u razvoju zemlje, od pojave čoveka do danas (geol., lat.).',
 'kvartina': 'Strofa od četiri stiha (ital.).',
 'kvačiti': 'Zakačivati, spajati kukom jedan predmet za drugi (kvačiti kola); preneseno: mučiti, tlačiti (jači kvači); (kvačiti se) zakačivati se, okačivati se; i prepirati se, sukobljavati se.',
 'kvekerski': 'Koji se odnosi na kvekere.',
 'kvestor': 'Visoki finansijski službenik u starom Rimu (ist.); i viši policijski činovnik u Italiji (lat.).',
 'kvrgast': 'Sličan kvrgi, koji ima dosta kvrga, kvrtav (kvrgasto lišće, mladić).',
 'lagoda': 'Osećanje lakoće i bezbrižnosti, spokojstvo; ugodnost, zadovoljstvo, uživanje.',
 'lahorast': 'Koji je kao lahor, poput lahora; lak, nežan (lahorasti uzdah).',
 'lahorić': 'Umanjenica i nežni oblik od lahor.',
 'lakirer': 'Zanatlija koji se bavi lakiranjem (nem.).',
 'lakmusov': 'Koji se odnosi na lakmus (lakmusova boja, listić, hartija).',
 'lakoumnica': 'Lakoumna, nerazborita ženska osoba.',
 'lakoumnik': 'Lakouman, nerazborit čovek.',
 'laktat': '(Obično u množini) so mlečne kiseline (hem.).',
 'laktaza': 'Ferment koji razlaže mlečni šećer na grožđani šećer i galaktozu (hem.).',
 'lamantin': 'Krupni vodeni sisar iz porodice trichechidae, sličan foki (zool., fr.).',
 'lamarkizam': 'Učenje francuskog prirodnjaka Lamarka (biol.).',
 'lamatati': 'Mahati rukom, rukama ili nečim drugim; mlatarati.',
 'lampek': 'Kazan za pečenje rakije (ital.).',
 'lanceta': 'Šiljat i oštar nožić s dvostranim sečivom za puštanje krvi, hirurške zahvate i dr.; i kratak i oštar nož za duborez.',
 'lanište': 'Zemljište na kojem se gaji ili se gajio lan.',
 'lančast': 'Koji je sličan lancu, nalik na lanac.',
 'lapidarnost': 'Osobina onoga što je lapidarno, onoga koji je lapidaran u izražavanju; sažetost, konciznost, jedrovitost.',
 'laporast': 'Koji sadrži laporac, koji je od laporca (laporasta zemlja, tlo; laporasti krečnjak).',
 'laringolog': 'Lekar specijalista za bolesti grla.',
 'larveni': 'Koji se odnosi na larvu, na larve (larveni stupanj).',
 'laskavost': 'Osobina onoga koji je laskav, onoga što je laskavo.',
 'lastavić': 'Lastin ptić; uporedi lastavičić.',
 'lasteks': 'Fabrička marka i naziv za tkaninu protkanu gumenim nitima tako da je rastezljiva, elastična.',
 'lastica': 'Umanjenica i nežni oblik od lasta.',
 'latinizirati': 'Podvrći, podvrgavati latinizaciji; (latinizirati se) podvrći se, podvrgavati se latinizaciji.',
 'lautar': 'Onaj koji svira na lauti, odnosno koji peva uz lautu.',
 'lecitin': 'Vrsta fosfatida, karakterističan sastojak mozga, živaca, žumanaca i drugih životinjskih i biljnih tkiva (fiziol.).',
 'legendarnost': 'Osobina onoga što je legendarno.',
 'legislatura': 'Legislativa; i rok punomoći, mandata zakonodavnog organa.',
 'legitimizam': 'Shvatanje da potomci nekog vladara, monarha imaju neotuđivo pravo na presto; princip nepromenljivosti nasledne monarhije; privrženost svrgnutoj, staroj dinastiji.',
 'lemeš': 'Sečivo pluga, deo raonika koji pri oranju seče zemlju i prodire u nju.',
 'leming': 'Glodar (lemmus lemmus) sličan poljskom mišu, iz potporodice voluharica (zool.).',
 'lenger': 'Sidro, kotva (tur.).',
 'lepetati': 'Proizvoditi, odavati lepet udarajući, mašući krilima; i odavati šum pri lepršanju na vetru, npr. o zastavi.',
 'lesonit': 'Vrsta materijala dobijenog presovanjem drvnih vlakanaca, veštačke smole i lakova; ploča od takvog materijala.',
 'letimičnost': 'Osobina onoga što je letimično.',
 'ljetnikovac': 'Ljetnikovac — kuća za odmor preko leta, letnja vila (ijekavski).',
 'leukoplast': 'Zaštitna lepljiva tkanina koja se stavlja preko gaze na ranu, flaster (grč.).',
 'levičarstvo': 'Levičarska shvatanja, ideje; levičarsko delovanje, levičarska politika; i uprošćeno, vulgarno ili ekstremno shvatanje ili primena levičarskih ideja i programa.',
 'lešinarski': 'Koji se odnosi na lešinare (lešinarska grabljivost, jato).',
 'lešnikov': 'Koji pripada lešniku, koji se odnosi na lešnik (lešnikova boja, jezgra, ljuska).',
 'liberalka': 'Ženska osoba liberal.',
 'liberalnost': 'Osobina onoga koji je liberalan, onoga što je liberalno; liberalizam.',
 'licitar': 'Zanatlija koji pravi šarene medene kolače i igračke i prodaje ih u svojoj radnji i na vašarima (nem.).',
 'licitarski': 'Koji se odnosi na licitare, njihovu delatnost i njihove proizvode (licitarsko srce).',
 'lignin': 'Pored celuloze, drugi glavni sastojak drvene materije (lat.).',
 'likar': 'Naziv za neke insekte iz porodice potkornjaka: borov likar, jasenov likar, omorikov likar, veliki likar (zool.).',
 'likerski': 'Koji se odnosi na liker.',
 'likovnjak': 'Likovni umetnik; onaj koji se bavi likovnom umetnošću; nastavnik likovnog vaspitanja, likovnih umetnosti (razg. i đač.).',
 'limfatičan': 'Koji se odnosi na limfu, limfni (limfatični sudovi, tkivo); i koji boluje od limfatizma, sklon limfatizmu; uvećan, natečen, podbuo (limfatičan čovek, vrat).',
 'limunast': 'Koji je kao limun, koji podseća na limunov plod, na limun, sličan limunu (o boji, obliku i dr.).',
 'lineta': 'Izbočeno polukružno utvrđenje (voj., fr.).',
 'lipar': 'Lipova šuma, lipov gaj, lipik.',
 'lipaza': 'Enzim, ferment koji razlaže, rastvara masti (hem., biol.).',
 'lipin': 'Koji se odnosi na lipu, koji pripada lipi, lipov.',
 'lipovina': 'Lipovo drvo (kao građa i gorivo).',
 'lisičar': 'Vrsta lovačkog psa, koji prvenstveno služi za lov na lisice i jazavce; uporedi jazavičar (zool.).',
 'lisnik': 'Lisnate grane koje se odsecaju i upotrebljavaju za stočnu ishranu, obično preko zime (zbirno); i plast, sto takvih grana.',
 'litij': 'Hemijski element (Li), mekani alkalni metal srebrnastobele boje (hem.).',
 'litota': 'Stilska figura za ublažavanje, kada se neka tvrdnja, ocena i sl. iskazuje poricanjem svojstva suprotnog značenja (knjiž.); lingv. dvostruka negacija (grč.).',
 'litraža': 'Litarska zapremina suda.',
 'litreni': 'Litarski.',
 'litrica': 'Manja staklena boca koja je istog oblika kao litrenjak; litrenjak (često u ironičnom značenju).',
 'liturgičar': 'Onaj koji izučava liturgiku; poznavalac liturgike.',
 'livadarstvo': 'Poljoprivredna grana, delatnost koja se odnosi na gajenje i iskorišćavanje livada, na proizvodnju trave i sena; i nauka koja se bavi unapređenjem te delatnosti.',
 'lišce': 'Umanjenica i nežni oblik od lice.',
 'ljubiteljstvo': 'Bavljenje nečim, zanimanje za nešto iz ljubavi, naklonosti prema nečemu, sklonosti nečemu.',
 'ljubovati': 'Imati, održavati ljubavne veze; uporedi ljubavisati.',
 'ljuskast': 'Ljuskav.',
 'ljuskati': 'Vaditi iz ljuske, kore, mahune i sl. (zrna graška, pasulja, jezgru oraha, lešnika i dr.); (ljuskati se) ispadati iz ljuske, mahune i sl.',
 'ljuskavac': 'Sisar roda manis tela pokrivenog rožnatim pločama, ljuskama; vrste mu žive u Africi i jugoistočnoj Aziji (zool.).',
 'ljutitost': 'Stanje onoga koji je ljutit; ljutnja.',
 'logističar': 'Pristalica, predstavnik logistike.',
 'lokalizam': 'Usko shvatanje vlastitih društvenih, ekonomskih i sl. interesa, koje ne uvažava interese društva u celini; i jezička osobenost (obično izraz ili reč) karakteristična za usko područje, za određeni kraj.',
 'lokalpatriotizam': 'Posebna ili preterana privrženost mestu življenja, kraju u kojem se živi, zavičaju.',
 'lončanica': 'Biljka koja se neguje u loncu, saksiji, obično kao sobna ukrasna biljka.',
 'lončina': 'Uvećanica i pežorativ od lonac.',
 'lornjon': 'Lornjet samo za jedno oko; monokl sa drškom (fr.).',
 'lovica': 'Mačka (ili sl. životinja) koja dobro, vešto lovi; uporedi lovačica.',
 'lovčev': 'Koji pripada lovcu, koji se odnosi na lovca.',
 'lozar': 'Vrsta pasulja koji se penje uz pritku, pritkaš (agr.).',
 'lozovina': 'Stabljika vinove loze; grana, mladica vinove loze s lišćem; i lozovo lišće.',
 'lubeničar': 'Proizvođač i prodavac lubenica; uporedi bostandžija.',
 'lugarnica': 'Lugarova, šumarova kućica.',
 'luksuznost': 'Osobina onoga što je luksuzno, luksuz.',
 'lumbalan': 'Koji se odnosi na slabine, slabinski (lumbalna anestezija, lumbalni nervi).',
 'luminiscentan': 'Koji se odnosi na luminiscenciju (luminiscentna svetlost).',
 'luneta': 'Dekorativni polukružni deo iznad vrata ili prozora oivičen kamenim okvirom; uporedi lineta (arhitektura, fr.).',
 'luteranstvo': 'Versko učenje nemačkog teologa Martina Lutera, protestantskog reformatora iz XVI veka, protestantstvo; protestantska veroispovest.',
 'lutnja': 'Isto što i lauta (muz.); i (pesnički) lutanje.',
 'lučev': 'Koji je od lučevog, borovog drveta, od lučevine; borov (lučev zublja, kapak, krov).',
 'lučica': 'Umanjenica od luka; mala luka.',
 'luša': 'U nežnom značenju: lula.',
 'macaklin': 'Gušter iz porodice gekkonidae, osoben po tome što ispušta glasove (zool.).',
 'madera': 'Čuveno vino sa portugalskog ostrva Madera (port.).',
 'maglenka': '(Obično u množini) svaka od najmanje dve sijalice na automobilu pogodne za vožnju po magli (razg.).',
 'maglin': 'Koji pripada magli, koji potiče od magle; maglen, maglenast (pesn.).',
 'maglovitost': 'Osobina, stanje onoga što je maglovito.',
 'maher': 'Veoma vešt, spretan čovek, čovek koji se snalazi u svakoj situaciji; majstor, stručnjak za nešto (nem., razg.).',
 'mahunarka': '(U množini) red biljaka sa mahunastim plodom (bot.).',
 'makartizam': 'Naziv za politiku progona i diskriminacije komunista i levičara koju je u SAD vodio senator Makarti u jednom periodu posle Drugog svetskog rata.',
 'makroskopski': 'Koji se vidi golim okom; koji se odnosi na makroskopiju; suprotno mikroskopski.',
 'maksimalistički': 'Koji se odnosi na maksimalizam i maksimaliste, svojstven maksimalizmu i maksimalistima.',
 'malenost': 'Osobina onoga koji je malen, onoga što je maleno (po veličini, obimu, razmerama, značaju, vrednosti).',
 'malinov': 'Koji se odnosi na malinu, koji pripada malini, koji je od maline (malinova grana; malinov sirup); i koji je kao u maline (o boji).',
 'malinovac': 'Sirup, sok od maline.',
 'maljić': 'Čekić u mehanizmu klavira koji na dodir dirke udara u žicu proizvodeći zvuk.',
 'malokalibarski': 'Koji je malog kalibra (o vatrenom oružju, obično o pušci).',
 'maloća': 'Osobina onoga što je malo; ono što je malo, malenkost, sitnica; i vreme, uzrasno doba dok je neko još (bio) mali, malo dete, rano detinjstvo (od maloće živi kao tuđe slušče).',
 'mamuzina': 'Uvećanica i pežorativ od mamuza.',
 'mandril': 'Vrsta majmuna iz roda pavijana (zool.).',
 'manganov': 'Koji se odnosi na mangan, koji sadrži mangana (manganova ruda).',
 'manifestant': 'Učesnik manifestacije.',
 'manual': 'Priručna knjiga, priručnik; beležnica, dnevnik; molitvenik (kod katolika); muz. klavijatura orgulja (lat.).',
 'marela': 'Vrsta višnje krupnog ploda (bot., agr.; nem.).',
 'marginalizovati': 'Učiniti marginalnim; uporedi marginalan.',
 'marinizam': 'Preterano kićenast, izveštačen pesnički stil u italijanskoj poeziji XVII veka, po ital. pesniku Đ. Mariniju (knjiž.).',
 'maritimni': 'Koji se odnosi na more i pomorstvo, pomorski (maritimna država, veza, oružje).',
 'markantnost': 'Osobina onoga koji je markantan, onoga što je markantno.',
 'marksistkinja': 'Ženska osoba marksista.',
 'martinka': 'Vrsta starinske puške, po konstruktoru Martiniju (ist.).',
 'maršalstvo': 'Maršalski čin, zvanje i dostojanstvo maršala.',
 'maskerata': 'Srednjovekovna pokladna pesma izvođena u scenkom obliku (knjiž., ital.).',
 'maslenica': 'Pita, kolač, pogača i sl. s maslom, s mašću ili nekom drugom masnoćom; i sud, posuda u kojoj se drži maslo, mast i sl.',
 'maslinar': 'Onaj koji gaji masline, koji se bavi maslinarstvom.',
 'maslinarski': 'Koji se odnosi na maslinare i maslinarstvo (maslinarski kraj).',
 'maslinarstvo': 'Gajenje maslina; poljoprivredna grana, delatnost koja se odnosi na gajenje maslina.',
 'maslinovina': 'Maslinovo drvo (kao građa, gorivo), maslinovo stablo, maslina; lisnato maslinovo granje.',
 'masnik': 'Vrsta mekane, zemljaste rude, mineral masnog opipa (min.).',
 'mason': 'Član, pripadnik (polu)tajnog kosmopolitskog religiozno-filozofskog društva i pokreta hijerarhijski organizovanog u tzv. ložama; slobodni zidar, framason (fr.).',
 'mastitis': 'Zapaljenje mlečnih žlezda dojke ili vimena (med., vet.).',
 'masen': 'Isto što i maseni; koji se odnosi na masu.',
 'mauk': 'Glas kojim se oglasava mačka, mačji glas; maukanje.',
 'mačvanin': 'Stanovnik Mačve; onaj koji je iz Mačve.',
 'mađarac': 'Severni vetar, severac (koji u naše krajeve duva iz Mađarske); i vrsta mađarskog vina.',
 'mađarizirati': 'Izvršiti mađarizaciju; da(va)ti nečemu mađarsko obeležje, (s)tvoriti, (na)praviti u duhu mađarskog jezika (mađarizirana imena); (mađarizirati se) dobijati mađarsko nacionalno obeležje, posta(ja)ti mađarski.',
 'meandrirati': 'Teći krivudavo praveći meandre, krivudati, vijugati (o reci).',
 'mecenatstvo': 'Pokroviteljstvo, pomoć, potpora mecene; mecenaška institucija.',
 'medak': 'Biljka koja ima beli cvet sa puno nektara (bot.).',
 'medaljica': 'Umanjenica i nežni oblik od medalja.',
 'medar': 'Onaj koji po šumama sakuplja med divljih pčela; onaj koji se bavi prodajom meda; uporedi pčelar.',
 'medicinarka': 'Ženska osoba medicinar.',
 'mediti': 'Zaslađivati medom (obično rakiju); preneseno: slatkorečivo pričati, govoriti; i lučiti medni sok, nektar (o biljkama).',
 'meditativan': 'Sklon meditaciji, razmišljanju.',
 'mediteranac': 'Stanovnik Mediterana, Sredozemlja; onaj koji je sa mediteranskog područja; čovek mediteranskog ili antropološkog tipa.',
 'medište': 'Gornji sloj saća ili gornji deo košnice u kojem pčele spremaju i ostavljaju med.',
 'medljikovac': 'Med od medljike.',
 'medonjica': '(U množini) porodica noćnih leptira čije gusenice žive na lišću vinove loze i drugih biljaka; i vrsta iz te porodice (zool.).',
 'medun': 'Vrsta nara, šipka (bot.).',
 'megaherc': 'Jedinica za označavanje frekvencije od milion herca, MHz (fiz.).',
 'megalomanski': 'Koji se odnosi na megalomaniju i megalomane, grandomanski (megalomanske ideje, snovi, tvrdnje).',
 'megavolt': 'Jedinica električnog napona od milion volti (fiz.).',
 'mehanicistički': 'Koji se odnosi na mehanicizam i mehaniciste, svojstven mehanicizmu i mehanicistima; uporedi mehanistički.',
 'mehanicizam': 'Učenje po kojem se sve pojave svode na mehaničko kretanje materije i objašnjavaju mehaničkim zakonima (fil.).',
 'meket': 'Oglašavanje koza i ovaca, meketanje, meka (uzvik).',
 'meketav': 'Koji mekeće; koji podseća na meket, meketanje (meketava jagnjad; meketav glas).',
 'mekokrilac': 'Insekt iz reda kornjaša mekih krila (zool.; obično u množini).',
 'mekušast': 'Prilično mek, mekan, mekušan, mekušav.',
 'melanizam': 'Prekomerna pigmentacija (usled velike toplote, vlage, hladnoće i dr.) (biol.).',
 'menadžerstvo': 'Posao i zanimanje menadžera.',
 'menaža': 'Prostorija za zajedničku ishranu, zajednička kuhinja, menza; i jelo spravljeno za veći broj lica, zajednička hrana (fr.).',
 'meningokok': 'Vrsta bakterije koja izaziva meningitis (med.).',
 'menjševizam': 'Pokret desnog krila ruske socijaldemokratske radničke partije, posle rascepa te partije (pol., ist.).',
 'merkantilan': 'Koji se odnosi na trgovinu, trgovinski (merkantilni odnosi, prodaja); „merkantilna roba" — roba prosečnog kvaliteta (ital.).',
 'merkantilistički': 'Koji se odnosi na merkantilizam i merkantiliste (merkantilističko vreme, politika).',
 'mesarstvo': 'Proizvodnja, prerada i prodaja mesa, mesarski poslovi.',
 'mesina': 'Uvećanica i pežorativ od meso (nažderati se mesine).',
 'mesnatost': 'Osobina, stanje onoga koji je mesnat, onoga što je mesnato.',
 'mesopusni': 'Koji se odnosi na mesopust, na dane mesopusta (mesopusna nedelja, utorak, ludovanje).',
 'metabolit': 'Proizvod metabolizma (fiziol.).',
 'metaloglodač': 'Radnik metalske struke koji izrađuje mašinske delove, zupčanike i dr. pomoću mašine glodalice.',
 'metamorfizam': 'Skup promena u strukturi stena izazvanih nizom fizičkih i hemijskih pojava (geol.).',
 'metastazirati': 'Preneti se, prenositi se sa jednog mesta u organizmu na drugo (obično o kanceroznim oboljenjima).',
 'meter': 'Tafički radnik koji štamparski slog prelama na određeni format stranice (štamp., fr.).',
 'metiljavost': 'Bolest izazvana metiljima; stanje onoga koji je metiljav, onoga što je metiljavo.',
 'metodičnost': 'Osobina onoga koji je metodičan, onoga što je metodično.',
 'metraža': 'Dužina izražena u metrima (obično u vezi s filmovima i filmskom trakom).',
 'mezanin': 'Međusprat, obično manji, niži od spratova između kojih se nalazi, najčešće između prizemlja i prvog sprata (ital.).',
 'međukorak': 'Vrsta koraka u nekim sportskim igrama, naročito hokeju ili rukometu (sport).',
 'međustanica': 'Stanica između polazne i krajnje ili između dve važnije; usputna stanica.',
 'međuzavisnost': 'Međusobna, uzajamna zavisnost.',
 'međuzonski': 'Koji se nalazi, održava i sl. između zona, među zonama, obično o šahovskim takmičenjima (međuzonski turnir).',
 'mešić': 'Umanjenica i nežni oblik od meh.',
 'mikroanaliza': 'Skup hemijskih metoda podešenih za određivanje malih količina supstanci.',
 'mikrometar': 'Sprava za precizno merenje veoma malih dužina ili uglova, uporedi nonijus (tehn.); i milioniti deo metra, mikron.',
 'mikrotalasan': 'Koji se odnosi na mikrotalase (mikrotalasna pećnica).',
 'milionče': 'Umanjenica i eufemizam od milion: potrošiti milionče (razg.).',
 'miljokaz': 'Kamen, stub kraj puta sa oznakama rastojanja u miljama; preneseno: ono prema čemu se određuje pravac delovanja, orijentir, putokaz.',
 'milozvučnost': 'Osobina onoga što je milozvučno, blagozvučnost, melodičnost, harmoniičnost, milozvučje (milozvučnost italijanskih stihova, srpskog jezika).',
 'ministrirati': 'Obavljati dužnost ministranta (crkv.).',
 'miokarditis': 'Zapaljenje srčanog mišića (med.).',
 'mirovinski': 'Koji se odnosi na mirovinu, penzijski, penzioni (mirovinski fond).',
 'misionarstvo': 'Rad, aktivnost misionara, misionarska delatnost, misionarski poziv; i propovedanje i sprovođenje u život određenih ideja, planova i sl.',
 'misnik': 'Katolički sveštenik ili redovnik koji služi misu; sveštenik uopšte (kod katolika).',
 'mistral': 'Hladan i suv severni ili severozapadni vetar koji duva na obalama severozapadnog dela Sredozemnog mora; uporedi maestral (fr.).',
 'mitraizam': 'Religiozni kult Mitre, indoiranskog božanstva sunca i svetlosti.',
 'mišičav': 'Koji ima razvijene, snažne mišiće; mišićav (mišičava ruka; sportista).',
 'mladar': 'Mladica, izdanak, lastar.',
 'mladomisnik': 'Katolički sveštenik koji služi mladu misu; mladi sveštenik (kod katolika).',
 'mlaznik': 'Cev za prolaz pogonskog gasa; uporedi mlaznica (tehn.).',
 'mlinarica': 'Žena mlinar; mlinareva žena.',
 'mlinarstvo': 'Privredna grana koja se bavi mlevenjem žitarica, odnosno proizvodnjom brašna; mlinarska industrija.',
 'mnogolikost': 'Osobina onoga što je mnogoliko, raznolikost, raznovrsnost.',
 'mnogoljudnost': 'Osobina onoga što je mnogoljudno.',
 'mobilizirati': 'Isto što i mobilisati (pozvati u vojsku; pokrenuti i okupiti za neki cilj).',
 'modalnost': 'Leksičko-gramatička kategorija kojom se u vidu stava uverenosti, sumnje, želje i dr. pokazuje odnos govornog lica ili subjekta prema onome što se saopštava rečenicom (lingv.).',
 'modelarnica': 'Radionica za izradu modela; uporedi model.',
 'modelarstvo': 'Izrada modela; grana sportskog vazduhoplovstva koja se bavi izradom umanjenih modela aviona, jedrilica, raketa i sl. i ispitivanjem mogućnosti njihovog letenja.',
 'modernizator': 'Onaj koji sprovodi modernizaciju, koji modernizuje nešto.',
 'monarhinja': 'Ženska osoba monarh, vladarka.',
}

C = {
 'kragulj': 'glosa samo uput na „kraluj" — osnovna reč nejasna',
 'krc': 'glosa OCR-nečitka; nesigurno (moguće onomatopeja)',
 'krivanja': 'glosa fragmentarna; značenje nejasno',
 'krivoverac': 'glosa odsečena u OCR-u („pristalica, sledbenik…") — nepotpuna',
 'kriši': 'glosa fragmentarna; značenje nejasno',
 'križarski': 'glosa odsečena/nepotpuna u OCR-u (samo uput) — nesigurno',
 'kupnja': 'glosa samo uput na „kubovina" — osnovna reč nejasna',
 'kuruz': 'glosa fragmentarna; značenje nejasno',
 'kuruza': 'glosa fragmentarna (deo odrednice „berba"); značenje nejasno',
 'kurvetina': 'vulgarno (familija „kurva", na blok-listi generatora); rečnik takve reči ne vodi',
 'kurvica': 'vulgarno (familija „kurva"); rečnik takve reči ne vodi',
 'kurvinski': 'vulgarno (familija „kurva"); rečnik takve reči ne vodi',
 'kurčiti': 'vulgarno (razg. vulg. po Matici); rečnik takve reči ne vodi',
 'kućiši': 'glosa fragmentarna; značenje nejasno',
 'laca': 'token iz predgovora rečnika; nije odrednica — nepotvrđeno',
 'lamanjem': 'glosa fragmentarna (deo odrednice „lomljenje"); značenje nejasno',
 'lanik': 'botanička glosa OCR-nečitka (rod nečitljiv) — nesigurno',
 'lača': 'glosa fragmentarna; značenje nejasno',
 'lači': 'glosa fragmentarna; značenje nejasno',
 'lekša': 'glosa fragmentarna (deo odrednice „duh"); značenje nejasno',
 'lesnih': 'glosa fragmentarna (deo odrednice „duh"); značenje nejasno',
 'lesnik': 'glosa fragmentarna; značenje nejasno',
 'lesnika': 'glosa fragmentarna; značenje nejasno',
 'longituda': 'glosa odsečena u OCR-u (astronomski termin) — nepotpuna',
 'lovaši': 'glosa fragmentarna (deo odrednice „loš"); značenje nejasno',
 'ličinama': 'glosa fragmentarna; osnovna reč nejasna',
 'ličinom': 'glosa fragmentarna; osnovna reč nejasna',
 'made': 'glosa fragmentarna; značenje nejasno',
 'madi': 'glosa fragmentarna; značenje nejasno',
 'manca': 'glosa fragmentarna; značenje nejasno',
 'matematik': 'u Matici samo „matematika/matematičar"; oblik „matematik" nije potvrđen (verovatno pokvaren uvoz)',
 'matematicima': 'u Matici samo „matematika/matematičar"; oblik nije potvrđen',
 'matematiče': 'u Matici samo „matematika/matematičar"; oblik nije potvrđen',
 'mau': 'glosa fragmentarna (deo odrednice „mijau"); značenje nejasno',
 'menjaka': 'glosa fragmentarna; značenje nejasno',
 'meš': 'glosa fragmentarna (deo odrednice „baviti se"); značenje nejasno',
 'mešima': 'glosa fragmentarna; značenje nejasno',
 'meši': 'glosa fragmentarna (deo odrednice „meta"); značenje nejasno',
 'meške': 'glosa fragmentarna; značenje nejasno',
 'mički': 'glosa fragmentarna; osnovna reč nejasna',
 'mirnica': 'glosa fragmentarna; značenje nejasno',
 'Malezi': 'u Matici samo „Malezija"; oblik „Malezi" nije potvrđen (verovatno isečak pri uvoženju)',
 'makovski': 'glosa OCR-nečitka; značenje nejasno',
}
