# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 1–330 (ablativ … Cita).
# DEC: reč/lema → objašnjenje (B ako je sama na spisku; inače izvor za izvedena A).
# C:   reč/lema → razlog zašto ide vlasnici (pokriva sve oblike grupe).

DEC = {
 'ablativ': 'Gramatički padež koji označava odvajanje ili poreklo (naročito u latinskom jeziku).',
 'abraziv': 'Materija velike tvrdoće koja služi kao sredstvo za brušenje.',
 'abrazivan': 'Koji je zahvaćen abrazijom (abrazivno tlo).',
 'acetilsalicilni': 'U izrazu „acetilsalicilna kiselina" — beli kristalni prah koji se koristi kao lek (aspirin).',
 'acetisal': 'Acetilsalicilna kiselina, aspirin (farm.).',
 'adekvatnost': 'Osobina onoga što je adekvatno.',
 'aerodinamičnost': 'Osobina onoga što je aerodinamično.',
 'aerozagađenje': 'Zagađenje vazduha.',
 'afektirano': 'Izveštačeno, neprirodno, usiljeno (govoriti afektirano).',
 'afektivnost': 'Afektivno, emotivno stanje.',
 'aferaški': 'Koji se odnosi na aferaše i aferu; skandalozan.',
 'aforističar': 'Pisac aforizama.',
 'aforistički': 'Isto što i aforističan.',
 'agava': 'Sredozemna biljka mesnatog i sočnog lišća, iz porodice agavaceae.',
 'agnostički': 'Koji se odnosi na agnostike i agnosticizam.',
 'agrotehničar': 'Poljoprivredni tehničar.',
 'akademičar': 'Onaj koji pohađa ili je završio neku akademiju; akademski građanin, student.',
 'akcidentalan': 'Koji nije bitan; slučajan, promenljiv (filozofski pojam).',
 'aksiomatski': 'Koji se odnosi na aksiom (aksiomatski sistem, metoda).',
 'aktualan': 'Aktuelan; koji je sad važan, tekući.',
 'akumulirati': 'Gomilati, skupljati (energiju, blago i sl.).',
 'akupresura': 'Metod lečenja pritiskivanjem određenih mesta na telu.',
 'akustičar': 'Stručnjak za akustiku; i muzičar koji svira na akustičnom instrumentu.',
 'akut': 'Dugouzlazni akcenat u srpskom jeziku i znak (´) kojim se označava.',
 'akutnost': 'Osobina onoga što je akutno.',
 'akvaristika': 'Hobi uzgajanja egzotičnih riba i drugih vodenih životinja u akvarijumu.',
 'Albanac': 'Stanovnik Albanije; pripadnik albanskog naroda.',
 'albinizam': 'Urođeni nedostatak melanina, koji izaziva nenormalnu belinu kože i kose (kod životinja dlake ili perja).',
 'albumin': 'Vrsta belančevine koja se nalazi u belancetu jajeta, krvnom serumu, mleku i dr.; belančevina uopšte.',
 'alegoričan': 'Slikovit i prenesen, kao alegorija (alegorična slika, predstava).',
 'alimentirati': 'Snabdevati hranom, ishranjivati; uopšte snabdevati.',
 'alkoholiziranost': 'Stanje onoga koji je alkoholiziran, onoga što je alkoholizirano.',
 'alpinac': 'Vojnik koji služi u jedinici obučenoj za planinsko ratovanje.',
 'alpinist': 'Onaj koji se bavi alpinizmom, planinar.',
 'alterirati': 'Menjati, preinačiti; i pokvariti, izopačiti.',
 'alternativac': 'Pripadnik političke, umetničke ili kulturne alternative; opozicionar.',
 'alternativan': 'Koji se odnosi na alternativu.',
 'alternirati': 'Naizmenično nastupati u nekoj ulozi; zamenjivati, izmenjivati (jedno s drugim).',
 'aluminizirati': 'Prevući, prevlačiti (metale) aluminijumom radi zaštite od oksidacije.',
 'aluzivan': 'Koji sadrži aluziju.',
 'amarela': 'Vrsta višnje krupnog, nakiselog ploda; i plod te višnje (agr.).',
 'ambivalentnost': 'Osobina onoga koji je ambivalentan, onoga što je ambivalentno; dvojaka vrednost.',
 'amenovati': 'Isto što i aminovati (složiti se s tuđim mišljenjem, odobriti).',
 'Amerika': 'Kontinent između Atlantskog i Tihog okeana; razgovorno: SAD.',
 'amerikanistika': 'Nauka o američkoj varijanti engleskog jezika, američkoj književnosti i kulturi.',
 'amerikanizam': 'Američki duh, mentalitet i način života; i reč ili izraz preuzet iz američkog engleskog.',
 'amerikanizirati': 'Davati nekome ili nečemu američko obeležje, poameričiti.',
 'Amerikanka': 'Stanovnica Amerike, stanovnica SAD; razgovorno: naša žena povratnica iz Amerike.',
 'amfiteatralan': 'Koji ima oblik amfiteatra (amfiteatralna dvorana).',
 'amfiteatralno': 'Na amfiteatralan način; u obliku amfiteatra.',
 'amilaza': 'Enzim koji razgrađuje skrob i šećer.',
 'anacionalan': 'Koji nema nacionalnog osećanja; bez narodnosti, bez nacionalnog obeležja.',
 'anacionalnost': 'Osobina onoga koji je anacionalan, onoga što je anacionalno.',
 'analfabet': 'Nepismena osoba; preneseno: nestručnjak, neznalica.',
 'analitičnost': 'Osobina onoga koji je analitičan, onoga što je analitično; sposobnost sprovođenja analize.',
 'analognost': 'Osobina onoga što je analogno.',
 'ananasov': 'Koji se odnosi na ananas, koji je od ananasa (ananasov sok).',
 'anarhistkinja': 'Žena anarhista.',
 'anemičar': 'Onaj koji boluje od anemije.',
 'anestetički': 'Koji izaziva anesteziju (anestetičko sredstvo).',
 'anestezirati': 'Izvršiti, izvoditi anesteziju; učiniti neosetljivim prema bolovima.',
 'anglikanstvo': 'Državna protestantska religija u Engleskoj.',
 'angloamerikanac': 'Amerikanac engleskog porekla; (u množini) Englezi i Amerikanci zajedno.',
 'animalistički': 'Koji se odnosi na animaliste.',
 'anonimac': 'Anonimna osoba, anonimus.',
 'anoreksičar': 'Osoba obolela od anoreksije.',
 'anorganski': 'Koji se odnosi na neživu prirodu; neorganski (anorganska hemija).',
 'antagonistički': 'Koji se odnosi na antagonizam i antagoniste; neprijateljski, suparnički.',
 'antibiogram': 'Prikaz osetljivosti mikroba — uzročnika neke bolesti — na delovanje pojedinih antibiotika (med.).',
 'antibiotički': 'Koji se odnosi na antibiotike (antibiotičko sredstvo, dejstvo).',
 'anticipativno': 'Unapred, pre vremena, prevremeno.',
 'antidatirati': 'Staviti, stavljati raniji datum umesto pravog.',
 'antidemokratski': 'Koji se odnosi na antidemokrate.',
 'antidrama': 'Drama koja nema klasične elemente drame.',
 'antifašistkinja': 'Žena antifašista.',
 'antifašizam': 'Široki demokratski pokret protiv fašizma.',
 'antikomunizam': 'Politička aktivnost usmerena na opovrgavanje i osporavanje komunističke ideologije.',
 'antikvarno': 'Kao antikvitet, putem antikvarske prodaje (nabaviti knjigu antikvarno).',
 'antilogaritam': 'Matematička operacija obrnuta od logaritmovanja (mat.).',
 'antioksidans': 'Hemijska materija koja se dodaje lako pokvarljivim proizvodima radi sprečavanja ili usporavanja oksidacije.',
 'antipatičnost': 'Osobina onoga koji je antipatičan; odvratnost, odbojnost.',
 'antipiretik': 'Lek za snižavanje povišene telesne temperature.',
 'antičestica': 'Subatomska čestica koja postoji samo prolazno pri stvaranju parova ili pri radioaktivnom raspadu (fiz.).',
 'antropomorfizam': 'Pridavanje ljudskih osobina ili ponašanja božanstvima, životinjama ili biljkama; prikazivanje božanstava ili prirodnih pojava u ljudskom liku.',
 'apelant': 'Lice koje se žali ili obraća višem sudu ili višoj vlasti (pravn.).',
 'apolitičnost': 'Osobina onoga koji je apolitičan; ravnodušan odnos prema politici.',
 'apostolstvo': 'Apostolska misija; propovedanje novih ideja.',
 'apotekarstvo': 'Služba apotekara, apotekarski poziv; nauka o lekovima, farmacija.',
 'apretura': 'Završni postupak kojim se materijalu (koži, tkanini i sl.) daje lepši izgled (sjaj, glatkoća); i ono čime je materijal apretiran.',
 'aproksimativno': 'Približno, otprilike.',
 'apćiha': 'Uzvik kojim se podražava kijanje.',
 'arabistika': 'Nauka o arapskom jeziku, arapskoj književnosti i arapskoj kulturi uopšte.',
 'arbitrator': 'Ekspert za arbitražu, procenitelj, prosuđivač.',
 'arhiepiskopstvo': 'Dostojanstvo, zvanje arhiepiskopa; sedište arhiepiskopa.',
 'arhiđakonat': 'Deo dijeceze pod upravom arhiđakona.',
 'aristotelovski': 'Koji je u duhu Aristotelovog učenja.',
 'aritmetičar': 'Stručnjak koji se bavi aritmetikom.',
 'aritmičan': 'Koji ima nepravilan ritam; neritmičan, neujednačen (aritmičan rad srca).',
 'armirati': 'Ojačavati armaturom (armirani beton, armirano staklo); i naoružavati ratne brodove ili avione.',
 'arza': 'Dizanje glasa; naglašeni ili dugi slog stope; suprotno tezi (knjiž.).',
 'asimetričnost': 'Osobina onoga što je asimetrično; nesimetričnost, asimetrija.',
 'astigmatičan': 'Koji boluje od astigmatizma.',
 'astralan': 'Koji se odnosi na zvezde, zvezdan; preneseno: bestelešan, nematerijalan, uzvišen.',
 'atestirati': 'Potvrditi, potvrđivati; uveriti atestom.',
 'atika': 'Nizak zid iznad krovnog vijenca ili pročelja zgrade (arhitektura).',
 'atomistički': 'Koji se odnosi na atomistiku, atomiste (atomističko učenje).',
 'autodrom': 'Staza za automobilske trke, trkalište za automobile.',
 'autohtonost': 'Osobina onoga što je autohtono; samorodnost, izvornost.',
 'autokefalan': 'Nezavisan, samostalan, samoupravan (o pravoslavnoj crkvi).',
 'autokefalnost': 'Samostalnost, nezavisnost (autokefalnost pravoslavne crkve).',
 'automatizam': 'Osobina organizma da određene radnje i pokrete vrši mehanički, nesvesno i bez učešća volje; takvi mehanički pokreti.',
 'automatičar': 'Vojnik koji rukuje automatskim oružjem, automatom.',
 'autonomaštvo': 'Propovedanje i sprovođenje autonomaške politike.',
 'autoritarizam': 'Autoritarni režim; oblik državne vlasti koncentrisane u rukama jedne ličnosti ili grupe ljudi koja zavodi diktaturu.',
 'autoritarno': 'Na autoritaran način (nastupiti autoritarno).',
 'autoritarnost': 'Osobina onoga što je autoritarno.',
 'autoritativnost': 'Osobina onoga što je autoritativno, onoga koji je autoritativan.',
 'autostopirati': 'Putovati auto-stopom.',
 'avanturizam': 'Sklonost avanturama; pravljenje avantura, avanturistička delatnost.',
 'babičin': 'Koji pripada babici.',
 'baburak': 'Oboleo, zakržljao plod šljive (bot.).',
 'bacalište': 'Teren na kome se izvode vežbe i takmičenja u bacanju (kugle, diska, koplja i dr.).',
 'bademast': 'Koji ima oblik bademovog ploda (bademaste oči).',
 'bagatelizirati': 'Isto što i bagatelisati (omalovažavati, potcenjivati).',
 'bakljonoša': 'Onaj koji nosi baklju; preneseno: nosilac neke ideje, idejni predvodnik, vođa.',
 'bakrenast': 'Koji je poput bakra, sličan bakru (bakrenasta boja, sjaj).',
 'bakrotisak': 'Vrsta štamparske tehnike (duboka štampa); štampanje bakropisa i bakroreza.',
 'baladni': 'Koji se odnosi na baladu (baladna forma, pesništvo).',
 'Balkan': 'Planinski sistem u istočnoj Srbiji i Bugarskoj; Balkansko poluostrvo.',
 'balotar': 'Igrač u igri balotama, u balotanju.',
 'balti': 'Zajednički naziv za narode severne Evrope koji govore baltičkim jezicima (Litvanci, Letonci, stari Prusi i dr.).',
 'bananin': 'Koji se odnosi na bananu, koji je od banane (bananin plod, kora).',
 'banstvo': 'Vlast i dostojanstvo bana.',
 'baril': 'Nekadašnja mera za vino i ulje (oko 45 l za vino, a 65 l za ulje).',
 'barograf': 'Sprava koja automatski beleži atmosferski pritisak (met.).',
 'baronić': 'Umanjenica od baron; i baronov sin.',
 'bastard': 'Mešanac nastao ukrštanjem različitih vrsta ili rasa, hibrid; razgovorno: vanbračno dete.',
 'bačvarstvo': 'Bačvarski zanat, proizvodnja bačava i drugih drvenih sudova za piće.',
 'bačvast': 'Koji je u obliku bačve, sličan bačvi; trbušast, ispupčen (bačvast trbuh).',
 'baždar': 'Ist. službenik koji kontroliše mere i tegove, kontrolor mera i tegova; i onaj koji naplaćuje baždarinu.',
 'bebast': 'Koji liči na bebu, podseća na bebu; koji je kao u bebe (bebasto lice).',
 'begovica': 'Begova žena.',
 'bekend': 'Vrsta udarca u tenisu (engl.).',
 'bekgraund': 'Pozadina, zaleđe; podloga (engl.).',
 'bekovski': 'Koji se odnosi na beka, na bekove (bekovski prostor, udarac).',
 'belančevinast': 'Koji sadrži belančevine; sličan belančevini.',
 'belača': 'Bela suknjena odeća (muška ili ženska); i bela vunena čarapa (etn.).',
 'belcat': '(Samo uz pridev „beo", za pojačavanje) sasvim beo, potpuno beo.',
 'beleg': 'Poseban znak na telu po kome se neko ili nešto raspoznaje (mladež, pečat, pramen kose); i znak, oznaka.',
 'beležništvo': 'Beležničko zvanje.',
 'benediktinac': 'Kaluđer katoličkog reda sv. Benedikta; i vrsta likera.',
 'benediktinka': 'Kaluđerica katoličkog reda sv. Benedikta.',
 'benignost': 'Osobina onoga što je benigno, dobroćudnost (benignost tumora).',
 'berat': 'Sultanova povelja, carski ukaz, dekret o imenovanjima i ovlašćenjima funkcionera (tur., ist.).',
 'beskamatno': 'Bez kamate, bez interesa.',
 'beskarakternost': 'Osobina onoga koji je beskarakteran.',
 'beskišan': 'Koji je bez kiše, oskudan u kiši, sušan (beskišno leto, kraj).',
 'besklasnost': 'Osobina onoga što je besklasno.',
 'beskompromisnost': 'Osobina onoga koji je beskompromisan; nepopustljivost, nepokolebljivost, odlučnost.',
 'beskućan': 'Koji nema kuće, veoma siromašan, ubog; beskućnički.',
 'besperspektivno': 'Bez perspektive; uzaludno (besperspektivno pokušavati nešto).',
 'besperspektivnost': 'Osobina onoga što je besperspektivno; loši izgledi na uspeh, uzaludnost.',
 'besplatnost': 'Besplatno dobijanje ili ostvarivanje nečega (besplatnost školovanja).',
 'besplodnost': 'Stanje i osobina onoga što je besplodno (besplodnost zemljišta, braka, posla).',
 'besposlenost': 'Stanje onoga koji je besposlen, dokonost, zaludnost.',
 'bespravnost': 'Bespravno stanje.',
 'bespredmetnost': 'Osobina onoga što je bespredmetno; neosnovanost, bezrazložnost; nepotrebnost, izlišnost.',
 'besprekornost': 'Osobina onoga koji je besprekoran, onoga što je besprekorno; savršenost, savršenstvo.',
 'besvest': 'Besvesno stanje, besvesnost.',
 'besvestica': 'Nesvestica, nesvest.',
 'betonirac': 'Radnik koji radi na betoniranju.',
 'bezdimno': 'Ne razvijajući dim pri sagorevanju (bezdimno goreti).',
 'bezgraničnost': 'Stanje i osobina onoga što je bezgranično; neograničenost, beskrajnost, beskonačnost.',
 'bezmesan': 'Koji je bez mesa, u kome nema mesa (bezmesna hrana); i u koji se ne jede meso (bezmesan dan).',
 'beznožac': '(U množini) podrazred vodozemaca bez nogu (zool.).',
 'bezopasnost': 'Stanje i osobina onoga što je bezopasno; neškodljivost; bezbednost, sigurnost.',
 'bezumnik': 'Bezuman čovek, ludak.',
 'bezuspešnost': 'Osobina onoga što je bezuspešno, uzaludnost.',
 'bezvodnost': 'Stanje i osobina onoga što je bezvodno; suša.',
 'bezvremenost': 'Osobina onoga što je bezvremeno; svevremenost, večnost.',
 'bešćutnost': 'Osobina onoga koji je bešćutan, onoga što je bešćutno.',
 'beživotnost': 'Stanje i osobina onoga što je beživotno.',
 'bibernica': 'Sudić u kome se drži biber.',
 'bifora': 'Prozor podeljen stubićem na dva dela sa posebnim lukovima (arhitektura).',
 'bilaterala': 'Bilateralni odnosi; bilateralni sporazum (pol.).',
 'bilingvizam': 'Podjednako upotrebljavanje dvaju različitih jezika u govornoj praksi pojedinca ili zajednice, dvojezičnost.',
 'bimetal': 'Dve međusobno spojene trake od metala s različitim koeficijentima toplotnog rastezanja; koriste se kao regulator temperature (dvometal, dvokovina).',
 'binom': 'Dvočlani algebarski izraz (mat.).',
 'binomni': 'Koji se odnosi na binom (binomna jednačina, red).',
 'biotip': 'Skup jedinki identičnih naslednih osobina (bot.).',
 'biračica': 'Ženska osoba birač.',
 'birov': 'Opštinski pozivar, pandur; i opštinski starešina, kmet, knez (mađ., ist.).',
 'biroš': 'Poljoprivredni najamni radnik koji živi na imanju svog gazde (mađ.).',
 'biskupstvo': 'Služba, čast, dostojanstvo biskupa.',
 'bitnik': 'Osoba koja se nekonvencionalno i bizarno oblači i ponaša; hipik; pripadnik američke bit-generacije književnika.',
 'bitva': 'Kratki stubić na pristaništu ili na pramcu broda koji služi za vezivanje brodova i drugih plovila (brod.).',
 'bivolče': 'Mladunče bivola.',
 'bivstven': 'Koji se odnosi na bivstvo; bitan.',
 'bivstveno': 'Bitno, suštinski.',
 'blagovesnik': 'Onaj koji donosi radosnu, prijatnu vest, glasnik radosnih vesti (zast.).',
 'blagozvučnost': 'Osobina onoga što je blagozvučno, milozvučnost, melodičnost.',
 'blagva': 'Vrsta jestive gljive (bot.).',
 'blanjalica': 'Mašina za struganje i obradu drveta ili metala.',
 'blanširati': 'Izbeliti (tekstil, papir, kožu i sl.); i kratkotrajno izložiti sirove namirnice (voće, povrće) dejstvu vrele vode, vodene pare ili zagrejane masnoće.',
 'blasfemičan': 'Bogohulan; krajnje uvredljiv, veoma pogrdan.',
 'blaziranost': 'Stanje ili osobina onoga koji je blaziran, onoga što je blazirano.',
 'blaženik': 'Onaj koji je proglašen blaženim odlukom katoličke crkve (kat.).',
 'blebetavost': 'Osobina onoga koji je blebetav, brbljivost.',
 'bludništvo': 'Blud, razvrat; bludničenje.',
 'bludnost': 'Blud, razvrat.',
 'bodljikavost': 'Osobina onoga koji je bodljikav, onoga što je bodljikavo; preneseno: zajedljivost, sarkastičnost.',
 'bogohulstvo': 'Huljenje na Boga, bezbožnost, bezbožništvo.',
 'bogoljubiv': 'Koji voli Boga, odan Bogu, pobozan.',
 'bogonosan': 'Koji je predan Bogu, veoma pobozan.',
 'bogoslovlje': 'Učenje o Bogu i veri, teologija.',
 'bogumilstvo': 'Bogumilsko učenje; bogumilski pokret.',
 'bokobran': 'Odbojnik (obično tužva od debelog konopca) koji štiti bok broda od oštećenja prilikom pristajanja (brod.).',
 'boluckati': 'Pomalo boleti, bolesti.',
 'bombastičnost': 'Osobina onoga što je bombastično.',
 'bordura': 'Ukrasni porub, obično od tkanine (fr.).',
 'boća': 'Kula za boćanje.',
 'boćalište': 'Teren uređen za boćanje.',
 'boćanje': 'Igra na otvorenom prostoru u kojoj igrači nastoje svoje boće bacanjem što više približiti cilju — maloj kugli.',
 'boćati': 'Igrati boće, učestvovati u igri na boće.',
 'bočina': 'Uvećanica od bok; bok (pežorativ).',
 'bočke': 'S bočne strane, s boka (udariti bočke).',
 'bošnjo': 'Ekspresivan, nežan oblik reči „Bošnjak".',
 'božikovina': 'Zimzeleni grm ili drvo; zelenika (bot.).',
 'božićnica': 'Jabuka kojom se prijatelji daruju o Božiću; i jabuka kojom mladoženja daruje zaručnicu (etn.).',
 'bradonjica': 'Nežni oblik reči „bradonja" (čovek s velikom, bujnom bradom).',
 'branjenica': 'Ženska osoba branjenik, štićenica.',
 'bravarstvo': 'Bravarski zanat.',
 'bravić': 'Umanjenica od brav.',
 'brazdast': 'Koji je u obliku brazde; pokriven brazdama, izbrazdan; i pun bora, izboran, zbrčkan.',
 'brazdica': 'Umanjenica i nežni oblik od brazda.',
 'brdina': 'Uvećanica od brdo (veliko brdo).',
 'brdovitost': 'Osobina, stanje onoga što je brdovito.',
 'breda': 'Vrsta mitraljeza italijanske izrade (po imenu jednog koncerna za izradu oružja).',
 'bremenitost': 'Stanje bremenite žene, trudnoća; preneseno: ispunjenost nečim, punoća.',
 'brener': 'Deo karbidske ili plinske lampe iz kojeg izbija plamen, gorionik (nem.).',
 'breskvik': 'Breskov voćnjak.',
 'brezik': 'Brezova šuma.',
 'breča': 'Sedimentna stena sastavljena od slepljenih uglastih komada istih ili različitih stena (geol.).',
 'breša': 'Otvor, rupa; voj. prodor kroz neprijateljske prepreke, utvrđenja ili bojne redove, proboj fronta.',
 'brideti': 'Pomalo boleti i trnuti, izazivajući osećaj svraba (obraz bridi, tabani bride).',
 'brkulja': 'Vrsta pšenice sa dugačkim osjem (agr.).',
 'brložan': 'Prljav, nečist, neuredan, zabušten.',
 'brodograditelj': 'Graditelj brodova; inženjer za gradnju brodova.',
 'brodovlasnički': 'Koji se odnosi na brodovlasnike.',
 'bruh': 'Izbočina koja nastaje ispadanjem unutrašnjih organa, najčešće creva pod kožu i sl., kila, hernija (nem., med.).',
 'brunirati': 'Prevući, prevlačiti spoljnu površinu predmeta od čelika ili bakra tankim slojem hlorida ili sulfida metala radi zaštite od korozije ili radi dekoracije.',
 'brusar': 'Onaj koji pravi bruseve.',
 'brusina': 'Uvećanica od brus.',
 'brusić': 'Umanjenica od brus.',
 'bršljanov': 'Koji pripada bršljanu, koji se odnosi na bršljan (bršljanov list, koren).',
 'bucanj': 'Morska riba zdepastog, spljoštenog tela, duga do 2,5 m (zool.).',
 'bucov': 'Naziv za neke vrste slatkovodnih riba (mađ.); preneseno pežorativno: klipan, glupak.',
 'budalaš': 'Budalasta, glupa muška osoba, budala, ludak.',
 'budžetirati': 'Snabdevati novčanim sredstvima, finansirati po planu predviđenom budžetom; i sastavljati budžet.',
 'bukara': 'Drveni ili zemljani sud za vodu, piće, vrč.',
 'bukački': 'Koji se odnosi na bukače, svojstven bukačima (bukačka štampa).',
 'bukvina': 'Uvećanica (i pežorativ) od bukva.',
 'bundevin': 'Koji pripada bundevi, koji je od bundeve (bundevin cvet, seme).',
 'bundica': 'Umanjenica i nežni oblik od bunda.',
 'bunjevka': 'Pripadnica bunjevačke etničke grupe.',
 'burin': 'Slab istočni vetar u Dalmaciji; slaba bura (ital.).',
 'burnica': '(U množini) red morskih ptica dugih krila, izvrsnih letača; (u jednini) takva ptica (zool.).',
 'burov': 'U izrazu „burova voda": vodeni rastvor aluminijum-acetata, koji se koristi za stavljanje obloga (kod rana, otoka, čireva i sl.).',
 'butić': 'Umanjenica od but.',
 'cakavski': 'Koji se odnosi na cakavštinu i cakavce (cakavski govor, jezička crta).',
 'caklen': 'Koji je prekriven caklinom, gleđu (cakleni zubi).',
 'capin': 'Vrsta šumskog oruđa: jak držalj s nasađenim gvožđem savijenim u obliku kljuna, za privlačenje i dizanje balvana u šumi; i planinarski štap (ital.).',
 'celcat': '(Obično u vezi s pridevom „ceo", u pojačanom značenju) ceo: ceo celcati dan, cela celcata varoš.',
 'celiti': 'Isceljivati, lečiti (celiti rane) — pesnički.',
 'celodnevan': 'Koji traje ceo dan (celodnevna nastava, boravak).',
 'celogodišnji': 'Koji traje celu godinu (celogodišnja biljka, zarada, proizvodnja).',
 'celovečernji': 'Koji traje celu večer (celovečernji film, program, drama).',
 'centimetarski': 'Koji se odnosi na centimetar.',
 'centrifugirati': 'Iscediti pomoću centrifuge (centrifugirati rublje, med).',
 'cep': 'Jaričica privezana za motku kojom se mlatilo žito pri vršidbi, mlat; i grančica za kalemljenje biljke, kalem, navršak, plemka; i deo obrednog ruha koji katolički sveštenik stavlja oko vrata.',
 'cepak': 'Koji se lako cepa, cepljiv, kalav (cepako drvo, plod).',
 'cerezin': 'Vrsta veštačkog voska koji služi za izradu sveća, impregniranje tkanina i hartije (lat.).',
 'ces': 'Muz. za polustepen sniženi ton c.',
 'cesar': 'Car (najčešće o austrougarskom caru): bečki cesar (ist., arh.).',
 'cesta': 'Put s tvrdom podlogom (asfaltiran ili popločan), omeđen s obe strane, koji služi za međumesni javni saobraćaj, drum.',
 'cestarina': 'Taksa koju plaćaju vlasnici motornih i ostalih cestovnih vozila za korišćenje i održavanje cesta, drumarina; ist. dažbina za održavanje cesta i puteva.',
 'cestica': 'Umanjenica od cesta.',
 'cestogradnja': 'Gradnja, pravljenje cesta (kao građevinska grana).',
 'cevar': 'Kvalifikovani radnik za polaganje, ugradnju cevi.',
 'cibetka': '(U množini) porodica malih zveri sličnih kunama, sa žlezdama koje luče mirisnu materiju cibet; (u jednini) zver iz te porodice (zool.).',
 'cican': 'Koji je od cica (cicana haljina).',
 'cigančić': 'Umanjenica i nežni oblik od Ciganin; cigansko dete, ciganče; (u množini) nar. padavine u vidu sitnih snežnih kristala.',
 'ciglarstvo': 'Ciglarski zanat; izrada, proizvodnja cigala (kao privredna grana).',
 'ciglast': 'Koji je kao cigla, sličan cigli, obično po boji (ciglasta boja).',
 'ciglen': 'Koji je od cigle (cigleni pod); i koji je boje kao cigla (ciglena boja).',
 'ciglica': 'Umanjenica od cigla.',
 'cigo': 'Nežni oblik od Ciganin; i nadimak čoveku crne kože, crne puti.',
 'cikut': 'Oštar, rezak, prodoran zvuk, ciktanje, cika: cikut turpije (onom.).',
 'cilik': 'Oštar visok zvuk žičanih muzičkih instrumenata (cilik violine, gusala); oštar, rezak zvuk zvona, metalnih predmeta; i škripa (onom.).',
 'ciničnost': 'Osobina onoga koji je ciničan, onoga što je cinično.',
 'cinkograf': 'Radnik stručnjak u cinkografiji.',
 'cinčan': 'Koji je od cinka (cinčana ploča, žica, krov).',
 'cionistički': 'Koji se odnosi na cioniste i cionizam.',
 'cirkusantski': 'Koji se odnosi na cirkusante, svojstven cirkusantima (cirkusantska predstava).',
 'cirus': '(U množini) sitni paperjasti oblačići koji se sastoje od sitnih kristala leda i lebde u visini; (u jednini) takav oblačić (met.).',
 'cis': 'Muz. ton „ce" povišen za pola tona.',
 'cista': 'Loptasta patološka tvorevina na organima sa sopstvenim zidom, ispunjena tečnošću ili kašastim sadržajem (med.).',
 'cistercit': 'Katolički redovnik, pripadnik benediktinskog reda sa strogim redovničkim pravilima.',
}

C = {
 'alaša': 'glosa fragmentarna („uređaj, mašina za oštrenje" — isečak iz tuđe odrednice); značenje nejasno',
 'apta': 'sumnjiv oblik; Matica na tom mestu ima botaničku glosu koja je OCR-om pomerena — nije potvrđeno',
 'aranđelovcem': 'Matica ne vodi „Aranđelovac" (grad u Šumadiji); oblik nije potvrđen rečnikom',
 'aranđelovcu': 'Matica ne vodi „Aranđelovac" (grad u Šumadiji); oblik nije potvrđen rečnikom',
 'aranđelovče': 'Matica ne vodi „Aranđelovac" (grad u Šumadiji); oblik nije potvrđen rečnikom',
 'babinji': 'glosa se odnosi na biljne nazive („babinje/babine"), primer odsečen — značenje nesigurno',
 'baši': 'glosa fragmentarna („jedan drugić"); značenje nejasno',
 'bena': 'glosa fragmentarna (deo tuđe odrednice); značenje nejasno',
 'beni': 'glosa fragmentarna („beni artikli" — verovatno deo tuđe odrednice); značenje nejasno',
 'bistrico': 'nejasna dodela: vokativ imenice ili mesta; Matica vodi „bistrica" (bistra tečnost) — nesigurno',
 'bljuzga': 'ni „bljuzga" ni oblici nisu u Matici kao tokeni; familija nepotvrđena',
 'brence': 'glosa isprekidana OCR-om („zvečak, klašno u zvoncu?, zvonče") — značenje nesigurno',
 'budiši': 'glagolski oblik bez samostalne odrednice; u Matici samo unutar glosa',
 'bula': 'glosa fragmentarna (isečak iz tuđe odrednice); značenje nejasno',
 'bulica': 'umanjenica od „bula" čije značenje nije potvrđeno — nesigurno',
 'burica': 'umanjenica od „bur(a)"; osnovna reč nejasna — nesigurno',
 'bušina': 'botanička glosa nepregledna od OCR-a; sinonimija nejasna',
 'cir': 'glosa fragmentarna („cir, ~ služba"); značenje nejasno',
 'citi': 'glagolski oblik bez samostalne odrednice (deo izraza); značenje nejasno',
}
