# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 3301–3630 (vigovac … čuvarina).

DEC = {
 'vigovac': 'Pristalica, član nekadašnje političke stranke u Engleskoj (XVII v.) koja se oslanjala na finansijsku buržoaziju; danas pristalica liberalne stranke u Engleskoj (ist.).',
 'vikontesa': 'Vikontova žena ili kćerka.',
 'vilenica': 'Žena koja po narodnom verovanju ima čarobnu, vilinsku moć, čarobnica; vračara, gatara (prazn.).',
 'vince': 'Nežni oblik od vino; u izrazu „udarilo mu vince" — opio se od vina.',
 'virulentan': 'Koji je sposoban da izazove oboljenje, o bakterijama, mikrobima (med.).',
 'virulentnost': 'Sposobnost zaraznih mikroba da izazovu oboljenje (med.).',
 'visokofrekventan': 'Koji je visoke frekvencije.',
 'visokoletač': 'Rasa golubova koji visoko lete.',
 'visokopreosveštenstvo': 'Titula arhiepiskopa i mitropolita u pravoslavnoj crkvi (crkv.).',
 'visokoškolski': 'Koji se odnosi na visoku školu, fakultetski (visokoškolska ustanova).',
 'vist': 'Hazardna kartaška igra učetvoro sa 52 karte (engl.).',
 'vitao': 'Naziv za razne naprave koje se okreću; vratilo sa točkom.',
 'vitezić': 'Umanjenica i nežni oblik od vitez; mlad vitez.',
 'vitičar': '(U množini) grupa nižih morskih rakova koji žive pričvršćeni za stene, a vitičastim nogama love hranu; (u jednini) takav rak (zool.).',
 'vizionarstvo': 'Svojstvo i sposobnost vizionara, sklonost vizijama, vidovitost.',
 'vizitator': 'Crkveno lice koje vrši vizitaciju (apostolski vizitator).',
 'višeglasan': 'Složen, sliven od više glasova; komponovan u više glasova, polifoni: višeglasno pevanje, kompozicija (muz.).',
 'višekratnik': 'Broj u kome se neki manji broj sadrži više puta bez ostatka, mnogokratnik (mat.).',
 'višemesečni': 'Koji se odnosi na period od više meseci; koji ima više meseci, traje više meseci i sl.',
 'višestrukost': 'Osobina onoga što je višestruko.',
 'višeznačnost': 'Osobina onoga što je višeznačno (višeznačnost izraza); mat. postojanje više rešenja (višeznačnost funkcije).',
 'vlakance': 'Umanjenica od vlakno.',
 'vlasat': 'U kome ima mnogo vlasi, dlaka, vlakana (vlasata vuna, kudelja); koji je obrastao vlasima, dlakom, kosom, dlakav, kosmat (vlasata glava, prsa); i čupav (vlasat ćebe).',
 'vlasić': 'Umanjenica i nežni oblik od vlas.',
 'vlasište': 'Deo glave na kome rastu vlasi, kosa.',
 'vlasteličić': 'Vlastelin sa manjim posedom i na nižem položaju, niži plemić; i vlastelinov sin, mlad vlastelin (ist.).',
 'vlaše': 'Umanjenica i ironično od vlah.',
 'vodarica': 'Ženska osoba vodonoša; mit. vila koja po narodnom verovanju živi pored vode; zool. vodena ptica pevačica; i bela pastirica; (u množini) rod vodenih zmija.',
 'vodenika': 'Bodljikava biljka iz familije glavočika (bot.).',
 'vodir': 'Rog ili izdubljen komad drveta u kome kosci drže vodu i brus za oštrenje kose.',
 'vodičar': 'Onaj koji nosi posvećenu vodicu o Bogojavljenju.',
 'vodonikov': 'Koji se odnosi na vodonik (vodonikov atom, molekul, oksid, bomba).',
 'vodoprivredni': 'Koji se odnosi na vodoprivredu (vodoprivredni sistem).',
 'vodoravnost': 'Vodoravan položaj, horizontalnost.',
 'vodurina': 'Uvećanica i pežorativ od voda.',
 'vokalizam': 'Sistem samoglasnika jednog jezika, ili jednog dijalekta (lingv.).',
 'volframov': 'Koji se odnosi na volfram, koji sadrži volfram (volframova ruda, kiselina, čelik).',
 'volonterstvo': 'Dobrovoljan, besplatan rad, volonterska služba.',
 'voltmetar': 'Sprava, instrument za merenje električnog napona (el.).',
 'volumenski': 'Koji se odnosi na volumen.',
 'voluntarizam': 'Filozofsko učenje po kome je volja, a ne um, osnova svega postojećeg (fil.); pol. nastojanje da se voljom političkih faktora i prinudom državne sile određuju i usmeravaju bitni procesi (lat.).',
 'voćarnica': 'Prodavnica voća.',
 'vrapčarka': '(U množini) najbrojniji red ptica (passeriformes) sa dobro razvijenim organom za pevanje; (u jednini) ptica iz tog reda (zool.).',
 'vračarina': 'Nagrada, naplata za vračanje.',
 'vražić': 'Umanjenica i nežni oblik od vrag.',
 'vrckavo': 'Okretno, tipko (vrckavo hodati); i duhovito (vrckavo ispričati vic).',
 'vrckavost': 'Osobina onoga koji je vrckav, onoga što je vrckavo.',
 'vrednosnica': 'Formular, isprava za novčane poštanske pošiljke, uputnica (poštanska vrednosnica).',
 'vremešnost': 'Stanje i osobina onoga koji je vremešan, onoga što je vremešno.',
 'vretenar': 'Zanatlija koji pravi vretena; i rod rečnih riba vretenasta tela (zool.); i vrsta puža.',
 'vrećast': 'Koji je kao vreća, sličan vreći (vrećasta torba).',
 'vrhovništvo': 'Vrhovna vlast; vrhovni organ vlasti (arh. ili ironično).',
 'vrištavo': 'Vrišteći, prodorno, piskavo (o oglašavanju); i bleštavo, drečavo (vrištavo obojeni zidovi).',
 'vrletnost': 'Osobina onoga što je vrletno, strmost, okomitost, krševitost; neprohodnost.',
 'vrludav': 'Koji vrluda, krivudav.',
 'vrtoglavac': 'Neuravnotežen, brljiv čovek; ćaknut čovek.',
 'vrčasto': 'Kao vrč, u obliku vrča (vrčasto udubljen).',
 'vrčić': 'Umanjenica od vrč.',
 'vulgarizam': 'Gruba, prostačka reč ili izraz u jeziku (lingv.); i prostakluk, nepristojnost uopšte.',
 'vulgata': 'Latinski prevod Biblije, delo svetog Jeronima, koji je prihvaćen kao službeni tekst u katoličkoj crkvi (lat.).',
 'vulkanizam': 'Skup vulkanskih pojava i promene koje one izazivaju na zemljinoj kori (geol.); i naučna teorija koja se bavi tim pojavama i koja pripisuje vulkanima presudan uticaj na stvaranje zemljine kore.',
 'vunara': 'Radionica ili fabrika za preradu vune, fabrika vunenih tkanina; i prodavnica vune.',
 'vunarski': 'Koji se odnosi na vunare i vunarstvo (vunarski kombinat, četka).',
 'vunarstvo': 'Prerada vune kao vrsta radinosti, zanata ili kao grana tekstilne industrije.',
 'vučki': 'Koji je kao u vuka; nemilosrdan, okrutan; zao (vučki skok, urlikanje, napad, pogled).',
 'zabacivati': 'Nesvršeni oblik glagola „zabaciti"; (zabacivati se) nehotično se okretati u stranu, zakretati se.',
 'zabavljenost': 'Zauzetost, angažovanost.',
 'zabitan': 'Teško pristupačan, zabačen (zabitno selo); preneseno: skriven, tajan (zabitni ugao svesti); i koji živi povučeno, zapostavljen; i zaostao (zabitna palanka, sredina).',
 'zabroditi': 'Početi broditi, zaploviti vodom (zabroditi morem); preneseno: krenuti na duži, teži put.',
 'zabuljiti': 'Zagledati, uperiti (pogled, oči); (zabuljiti se) zagledati se nepremice, izbečenih očiju.',
 'zabundati': 'Uviti, umotati u bundu, upoviti (dete je dobro zabundala); (zabundati se) utopliti se.',
 'zacrnjenje': 'Zatamnjenje, crnilo.',
 'zacrtavati': 'Nesvršeni oblik glagola „zacrtati".',
 'zadak': 'Zadnja strana, pozadina (plamen na zatku cevi); i stražnjica (udariti konja po zatku).',
 'zadihanost': 'Stanje onoga koji je zadihan.',
 'zadivljenost': 'Stanje onoga koji je zadivljen.',
 'zadovoljenost': 'Stanje onoga koji je zadovoljan nečim.',
 'zadovoljština': 'Zadovoljenje.',
 'zadrugarka': 'Žena zadrugar.',
 'zadubljenost': 'Stanje onoga koji je zadubljen, predanost nečemu, zamišljenost.',
 'zadubljivati': '(Zadubljivati se) nesvršeni oblik glagola „zadubiti se" (zadupsti se).',
 'zafrkati': 'Početi frkati (obično o konju, konjima); uporedi zafrktati.',
 'zafrknuti': 'Podvaliti nekome, prevariti nekoga, obično grubo se šaleći (razg.); (zafrknuti se) prevariti se, pregrešiti na svoju štetu.',
 'zafućkati': 'Početi fućkati.',
 'zagasitost': 'Stanje i osobina onoga što je zagasito.',
 'zaglupljenost': 'Stanje onoga koji je postao glup.',
 'zagospodariti': 'Postati gospodar, steći vrhovnu vlast (zagospodariti Beogradom); i nametnuti se za gospodara, uzeti vlast u svoje ruke (zagospodariti policijom).',
 'zagovornica': 'Žena zagovornik, pobornica, pristalica.',
 'zagurati': 'Gurati, utisnuti.',
 'zagušljivost': 'Stanje onoga što je zagušljivo; ustajalost vazduha.',
 'zahvaćati': 'Isto što i zahvatati.',
 'zakaliti': 'Kaljenjem pretvoriti gvožđe u čelik; preneseno: očeličiti, učiniti čvršćim (zakaliti kosu; dušu).',
 'zakartati': 'Izgubiti na kartama, prokockati (zakartati očevinu); (zakartati se) početi se kartati; zadržati se dugo kartajući.',
 'zakipeti': 'Dočeti kipeti, prelivati se preko rubova posude, provreti (o tečnosti); preneseno: uskipeti, uzavreti (pod uticajem jakih osećanja, gneva, mržnje i dr.).',
 'zakladni': 'Koji se odnosi na zaklad i zakladu, zadužbinski (zakladna bolnica, imovina).',
 'zakladnica': 'Dokument o zakladu, zakladi.',
 'zakladnik': 'Onaj koji daje, ulaže u zaklad i zaklade.',
 'zaklecati': 'Početi klecati, podrhtati (o nogama, kolenima).',
 'zaklonjenost': 'Stanje, položaj onoga koji je zaklonjen, onoga što je zaklonjeno.',
 'zakoturati': 'Početi koturati, zakotrljati; (zakoturati se) početi se koturati, zakotrljati se.',
 'zakošenost': 'Kos položaj nečega.',
 'zakrabuljiti': '(Zakrabuljiti se) spaviti sebi krabulju, maskirati se.',
 'zakret': 'Okret, zaokret.',
 'zakreštati': 'Početi kreštati, ispustiti kreštav glas (o pticama i sl.); preneseno: kreštavo progovoriti.',
 'zakuckati': 'U umanjenom značenju: zakucati.',
 'zakvocati': 'Početi kvocati.',
 'zamahati': 'Početi mahati; (zamahati se) zaljuljati se, zanjihati se.',
 'zamatati': 'Isto što i zamotavati.',
 'zamišljenost': 'Stanje onoga koji je zamišljen, zanesenost u mislima.',
 'zamrlost': 'Osobina i stanje onoga što je zamrlo, obamrlost; mrtvilo (zamrlost u očima; kretanja).',
 'zanemarenost': 'Stanje onoga što je zanemareno, zapuštenost.',
 'zanesenjački': 'Koji se odnosi na zanesenjake.',
 'zanesenjaštvo': 'Osobina onoga koji je zanesenjak.',
 'zaobljenje': 'Davanje, odnosno dobijanje celovitog oblika, zaokruženje; i zaobljena površina, telo ili deo tela.',
 'zaokupljivati': 'Isto što i zaokupljati.',
 'zapadnjaštvo': 'Pogledi, shvatanja, način života, kultura svojstveni zapadnoevropskoj sredini; sklonost onome što je zapadnjačko.',
 'zapasati': 'Privezati nešto oko pasa, struka, opasati (zapasati nož); i opkoliti, opsednuti; i zahvatiti, obuzeti.',
 'zapiljiti': 'Početi piljiti, nepremice gledati u nešto; (zapiljiti se) zagledati se.',
 'zaplenjivati': 'Nesvršeni oblik glagola „zapleniti".',
 'zapljuvati': 'Pljuvanjem zaladiti, zaprljati; i ispljuvati nekoga u znak prezrenja, popljuvati.',
 'zapostavljenost': 'Stanje onoga koji je zapostavljen, zanemarenost.',
 'zapuh': 'Nalet, strujanje vetra; i snežna masa nanesena vetrom, namet, smet.',
 'zapučak': 'Rupica na odeći kroz koju se provlači dugme.',
 'zaraznost': 'Osobina i stanje onoga koji je zarazan, onoga što je zarazno.',
 'zarobljenost': 'Stanje, položaj onoga koji je zarobljen, kome je oduzeta sloboda.',
 'zaružiti': 'Početi ružiti; prekoreti.',
 'zarđalost': 'Stanje onoga što je zarđalo.',
 'zaskok': 'Skok sa zaletom, skakanje; napad.',
 'zaslepljenost': 'Stanje i osobina onoga koji je zaslepljen, onoga što je zaslepljeno; preterana zanesenost u nečemu.',
 'zaslužnik': 'Onaj koji je zaslužan, koji ima zasluge.',
 'zastariti': 'Izaći iz upotrebe, običaja, mode i sl., postati nesavremen; pravn. izgubiti pravnu vrednost, važnost, prestati važiti; i postati trajAN, hroničan (o bolestima).',
 'zastavni': 'Koji se odnosi na zastavu.',
 'zastavnički': 'Koji se odnosi na zastavnike.',
 'zastranjenje': 'Skretanje s puta; i skretanje od osnovne misli, od suštine; zapadanje u greške, zablude; i zabluda, obmana, pogreška.',
 'zastrašenost': 'Stanje onoga koji je zastrašen.',
 'zastrugati': 'Početi strugati; preneseno: usteći, stinuti.',
 'zastupljenost': 'Prisutnost, prisustvo, postojanje, učešće, predstavljenost.',
 'zatamnjivati': 'Nesvršeni oblik glagola „zatamneti".',
 'zatelebati': '(Zatelebati se) jako se zaljubiti; i zablenuti se (razg.).',
 'zatoran': 'Koji zadire, uništava; strašan, jezovit.',
 'zatrovanje': 'Zatrovanost.',
 'zatrovanost': 'Stanje onoga koji je zatrovan, onoga što je zatrovano.',
 'zatrpanost': 'Stanje onoga što je zatrpano; preopterećenost.',
 'zatupljenost': 'Stanje onoga koji je zatupljen, onoga što je zatupljeno; otupelost.',
 'zatupljivati': 'Nesvršeni oblik glagola „zatupiti".',
 'zauljiti': 'Preliti, začiniti uljem (zauljiti salatu).',
 'zaustava': 'Zaustavljanje, zadržavanje; prepreka.',
 'zavaljati': 'Učiniti da se nešto počne valjati, da se počne kotrljati (zavaljati drvo; grudvu snega); i stvoriti valove na nečemu, uzburbati (zavaljati more); i valjanjem dati okruglast oblik nečemu (zavaljati komad testa); (zavaljati se) početi se valjati, zakotrljati se.',
 'zavarljiv': 'Koji zavarava, varljiv (zavarljiv san).',
 'zavađenost': 'Odnos među zavađenima, zavada.',
 'zaviknuti': 'Viknuti; uporedi uzviknuti.',
 'zavreti': 'Početi vreti, proključati, provreti (o vodi i sl.); preneseno: uskomešati se, uzmutiti se (zavri u njemu krv); i živo brujati, šumeti.',
 'zazimiti': 'Nastati, nastupati, bezlično o zimi; i zaći u zimu, biti zatečen zimom; i ostaviti, odbrojiti za hranjenje preko zime (stoku, pčele i sl.).',
 'začaranost': 'Stanje onoga koji je začaran, zamađijanost, opčinjenost.',
 'začepljenost': 'Stanje onoga što je začepljeno, zabušenost.',
 'začetnica': 'Žena pokretač, inicijator nečega; žena krivac, vinovnik nečega.',
 'zašarafiti': 'Isto što i zašrafiti.',
 'zašareniti': 'Učiniti šarenim, prošarati.',
 'zaštićenost': 'Obezbeđenost, sigurnost; otpornost, imunitet.',
 'zbrkanost': 'Osobina onoga što je zbrkano.',
 'zdebljati': '(Zdebljati se) postati debeo, pojiti se.',
 'zdrmati': 'Energično, snažno prodrmati, protresti; zadrmati, zatresti nečim; (zdrmati se) zaljuljati se, zadrhtati.',
 'zelenak': 'Zelen, nedozreo plod; i vrsta rečne ribe (zool.).',
 'zelenčica': 'Isto što i čiž (zool.).',
 'zelot': 'Oduševljeni pristalica, pobornik neke ideje; fanatik, zanesenjak (grč.).',
 'zemljast': 'Koji je po fizičkim osobinama sličan zemlji, trošan, sidan; pomešan sa zemljom (zemljasta primesa); i koji je po izgledu sličan zemlji, taman, mrk (zemljasta koža, lice).',
 'zemljovlasnik': 'Vlasnik zemlje, imanja, zemljoposednik.',
 'zera': 'Vrlo mala, neznatna količina nečega (tur.).',
 'zečar': 'Lovački pas koji lovi zečeve; i lovac na zečeve.',
 'zgođušan': 'U umanjenom značenju: zgodan; uporedi lepuškast.',
 'zgrušanost': 'Stanje onoga što je zgrušano.',
 'zgrčenost': 'Osobina i stanje onoga što je zgrčeno.',
 'zgurati': 'Gurajući smaknuti (nekoga, nešto) s nečega, oterati, potisnuti (zgurati sa stolice); i gurati, sabiti (zgurati nešto u džep); (zgurati se) zbiti se nagomilu.',
 'zidanica': 'Zidana kuća (od kamena, cigle).',
 'zlatnina': 'Predmeti od zlata, zlatni nakit, novac.',
 'zračnost': 'Osobina onoga koji je zračan, onoga što je zračno.',
 'zrcalan': 'Koji se odnosi na zrcalo, na ogledalo; koji je kao zrcalo (zrcalno staklo; pogled).',
 'zrcaliti': '(Zrcaliti se) odražavati svoj lik na glatkoj, sjajnoj površini; ogledati se; preneseno: ispoljavati se, videti se (o duševnim stanjima); i blistati, sijati se (o jezeru i sl.).',
 'zuban': 'Muškarac s velikim zubima (pež.); zool. (u množini) rod sisara iz reda kitova sa jednim ili više zuba, (u jednini) takav kit; agr. vrsta kukuruza krupnog zrna.',
 'zubarstvo': 'Zubarska delatnost; stomatologija.',
 'zubatost': 'Osobina onoga koji je zubat; oštrina, hladnoća.',
 'zubača': 'Žena velikih zuba (pež.); poljoprivredna alatka za ravnanje poorane zemlje, drljača; bot. korovna biljka.',
 'zumba': 'Sprava za bušenje rupica u papiru; sprava za poništavanje maraka bušenjem; i sprava za udaranje suvog žita (tur.).',
 'zvezdolik': 'Koji ima oblik zvezde, zvezdast.',
 'zvečak': 'Klapna u zvonu; i livadska biljka (bot.).',
 'zvrcnuti': 'Kratko zazvoniti; pozvoniti telefonom; i udariti lako i brzo, cvrknuti (zvrcnuti ga grančicom; prstom u čelo).',
 'zvrndati': 'Zvrjati, obično neskldano; kloparati (o vretenu, kolima); i brbljati, naklapati, tunđati.',
 'ćelaviti': 'Ostajati bez kose, postajati ćelav.',
 'ćoravost': 'Osobina, stanje onoga koji je ćorav; slepilo.',
 'ćulah': 'Mala kapa od valjanog sukna (tur.).',
 'ćupina': 'Uvećanica i pežorativ od ćup.',
 'ćurlik': 'Glas svirale; i cvrkut nekih ptica (jarebica, ševa i dr.) koji podseća na glas svirale; i isto što i ćurlika.',
 'ćurlin': 'Vrsta ptice iz reda močvarica, zlatar pijukavac (zool.).',
 'ćutek': 'Batina, štap; udarac (tur.).',
 'ćuteti': 'Primati čulima kakve utiske, osećati čulima (ćuteti vetar na licu); i uopšte osećati, doživljavati nešto (ćuteti poniženje).',
 'ćutilan': 'Koji se odnosi na čula, čulni; osećajan (ćutilan doživljaj; osoba).',
 'čakavizam': 'Jezička crta svojstvena čakavskom govoru; čakavski dijalekatski oblik (lingv.).',
 'čakavka': 'Ženska osoba koja govori čakavskim narečjem.',
 'čamno': 'Isto što i čamotno.',
 'čamotno': 'U čami; potišteno, tmurno, sumorno (provoditi vreme čamotno).',
 'čančica': 'Vrsta morske školjke (zool.).',
 'čaplinovski': 'Koji je u duhu, stilu Čarlija Čaplina, američkog filmskog režisera i glumca komičara britanskog porekla (čaplinovska komika).',
 'čarapar': 'Zanatlija koji izrađuje i prodaje čarape; radnik u fabrici čarapa.',
 'čaraparnica': 'Radionica za izradu čarapa; radnja u kojoj se prodaju čarape.',
 'čarapin': 'U izrazu „usta su mu kao čarapin početak" — za onoga koji ima velika, ružna usta.',
 'čarobnički': 'Koji se odnosi na čarobnike i čarobnice.',
 'čartizam': 'Masovni revolucionarni radnički pokret u Engleskoj u prvoj polovini XIX veka za dobijanje političkih prava i poboljšanje ekonomskog položaja radnika (pol., engl.).',
 'časovit': 'Koji traje čas, tren, kratkotrajan, trenutan, trenutačan (časovit bol, utisak).',
 'časovito': 'Za kratko vreme, na trenutak (časovito nestati, pojaviti se).',
 'časovničarstvo': 'Rad, zanimanje časovničara, časovničarski zanat.',
 'časovnički': 'Koji se odnosi na časovnike (časovnički mehanizam).',
 'častohlepno': 'Žudeći za počastima, častoljubivo.',
 'čavlić': 'Umanjenica od čavao.',
 'čađan': 'Koji potiče od čađi, koji je od čađi (čađana prevlaka); i isto što i čađav.',
 'čađara': 'Koliba, soba i sl. pocrnela od čađi.',
 'čađast': 'Pomalo čađav; mrk kao čađ, čađav (čađasta ptica, boja).',
 'čađavac': 'Onaj koji je uprljan čađi; min. mrk proziran kremen, kvarc, koji se upotrebljava kao poludragi kamen.',
 'čađavica': 'Ženska osoba uprljana čađu; pežorativno: stara puška isprljana čađu (puška čađavica); i isto što i čađara; agr. bolest voćaka i drugih biljaka u vidu crne navlake gljivica na lišću.',
 'čašast': 'Koji je kao čaša, koji je u obliku čaše.',
 'čedomoran': 'Koji mori, ubija čeda, čedoubilački.',
 'čehovljevski': 'Koji je u duhu književnog dela ruskog pisca Antona Pavloviča Čehova, majstora kratke priče (čehovljevski stil, jezik).',
 'čekalište': 'Mesto gde se čeka; i mesto na kome lovac čeka lovinu, čeka.',
 'čekinjaš': '(U množini) životinje iz reda papkara (nepreživara) čije je telo obraslo čekinjama; i kolutićavi crvi sa čekinjastim izraštajima; (u jednini) takva životinja, takav crv (zool.).',
 'čekirati': 'Prijaviti, prijavljivati let, putovanje na aerodromskom šalteru (engl.).',
 'čeličnost': 'Osobina ili stanje onoga koji je čeličan, onoga što je čelično; postojanost, izdržljivost, otpornost.',
 'čelništvo': 'Skup čelnika, rukovodstvo.',
 'čempresovina': 'Čempresovo drvo (kao građa).',
 'čeonjača': 'Čeona kost (anat.).',
 'čestoslavica': 'Rod zeljastih biljaka, razton (bot.).',
 'čestoća': 'Česta pojava nečega, učestalost, frekventnost (čestoća saobraćaja, nazeba); i mali razmak, gustina (čestoća sadnica).',
 'četinarski': 'Koji se odnosi na četinare, crnogorični (četinarsko drvo).',
 'četkarstvo': 'Četkarski zanat, izrada i prodaja četaka.',
 'četkast': 'Koji je nalik na četku (četkasti brkovi, brada).',
 'četnjak': 'Noćni leptir čije se gusenice hrane borovim iglicama (zool.).',
 'četrdesetica': 'Predmet označen brojem četrdeset (vozilo, soba i sl.).',
 'četrdesetina': 'Četrdeseti deo nečega (tri četrdesetine); i skup, zbir od četrdeset ili približno četrdeset jedinki, četrdesetak (četrdesetina vojnika).',
 'četrdesetnica': 'Pomen ili dača koja se daje pokojniku četrdeseti dan posle smrti; i veliki post pred Uskrs (crkv.).',
 'četrdesetogodišnjakinja': 'Žena koja ima četrdeset ili oko četrdeset godina.',
 'četrnaesterac': 'Stih od četrnaest slogova; i jelen čiji rogovi imaju četrnaest parožaka.',
 'četrnaestina': 'Četrnaesti deo nečega.',
 'četvoroglasno': 'U četiri glasa: četvoroglasno pevati (muz.).',
 'četvoromesečni': 'Koji se odnosi na period od četiri meseca — koji ima četiri meseca, traje četiri meseca, dobija ili daje se svaka četiri meseca i sl. (četvoromesečna beba, boravak, zarada, izveštaj).',
 'četvoronožan': 'Koji ima četiri noge (četvoronožna životinja).',
 'četvorosed': 'Automobil sa četiri sedišta.',
 'četvrtgodišnje': 'Svake četvrtine godine (izlaziti iz štampe četvrtgodišnje).',
 'čeznutljivost': 'Osobina i stanje onoga koji je čeznutljiv, onoga što je čeznutljivo, čežnjivost; čežnja.',
 'češerast': 'Koji je sličan češeru, nalik na češer.',
 'češljača': 'Rod morskih mekušaca, školjkaša (zool.).',
 'češljuga': 'Biljka sa bodljikastim stabljikama i bodljikastim cvetnim glavicama (bot.).',
 'češnjarka': 'Vrsta žabe koja se danju zakopava u zemlju, a čije kožne žlezde izlučuju sok koji miriše na češnjak (zool.).',
 'činjeničnost': 'Svojstvo onoga što je činjenično, činjenična zasnovanost.',
 'čipkarica': 'Žena čipkar.',
 'čipkarstvo': 'Čipkarski zanat, veština pravljenja čipki.',
 'čipkica': 'Umanjenica od čipka.',
 'čirast': 'Sličan čiru (čirasti izraštaj).',
 'čirav': 'Pun čireva (čiravo lice).',
 'čiravost': 'Stanje onoga koji je čirav, onoga što je čiravo (čiravost creva).',
 'čiraš': 'Onaj koji boluje od čira na želucu ili dvanaestopalačnom crevu.',
 'čirić': 'Umanjenica od čir.',
 'čistac': 'Slobodan, otvoren prostor, čistina; u izrazima „izvesti/isterati na čistac", „izići (s nekim) na čistac" — raščistiti, objasniti nešto što je bilo zamršeno, nejasno; „biti na čistacu" — biti jasno.',
 'čistokrvnost': 'Stanje i osobina onoga koji je čistokrvan (čistokrvnost rase, pasmine).',
 'čitaonički': 'Koji se odnosi na čitaonicu, čitaonice (čitaonički članovi).',
 'čitačica': 'Ženska osoba čitač.',
 'čitkost': 'Osobina onoga što je čitko, jasnoća, čitljivost (čitkost prevoda, rukopisa).',
 'čizmetina': 'Uvećanica i pežorativ od čizma.',
 'čičoka': 'Višegodišnja biljka slična suncokretu, čiji hranljivi gomolji služe za krmu (bot.).',
 'čiž': 'Vrsta ptice pevačice iz porodice zeba (zool.).',
 'člankonožac': '(U množini) najbrojnija skupina životinja (arthropoda), koja obuhvata insekte, pauke, stonoge i rakove, zglavkari; (u jednini) zglavkar (zool.).',
 'člankovit': 'Koji ima članke, segmente, zglavkast (člankoviti crvi); i koji ima čvorove ili kolenca (člankovite stabljike).',
 'člankovitost': 'Svojstvo onoga što je člankovito.',
 'čobančica': 'Umanjenica i nežni oblik od čobanka.',
 'čohar': 'Onaj koji pravi čohu ili odeću od čohe; trgovac koji prodaje čohu (ist.).',
 'črčkalo': 'Rđav, slab pisac, piskaralo, škrabalo; rđav, slab crtač (pež.).',
 'čudaštvo': 'Osobina onoga koji je čudak, osobenjaštvo, nastranost; čudački, osobenjački postupci, osobenjačko ponašanje.',
 'čudotvorstvo': 'Čudotvornost; čudotvorno delo, čudo.',
 'čudovišnost': 'Svojstvo, osobina onoga što je čudovišno.',
 'čunjasto': 'Kao čunj, u obliku čunja (čunjasto završena krošnja).',
 'čunjaš': 'Rod grabljivih morskih puževa (zool.).',
 'čunjašica': 'Rod pelagičkih morskih puževa prednjoškržnjaka s veoma malom kućicom (zool.).',
 'čupavica': 'Čupava, razbarušena ženska osoba.',
 'čupač': 'Onaj koji nešto čupa (npr. travu, perje i sl.).',
 'čupkast': 'Pomalo čupav, kuštrav, kovrčast (čupkasta brada).',
 'čupoglavac': 'Čupoglav, čupav muškarac, čupavac, čupavko.',
 'čuturaš': 'Onaj koji rado pije, koji je sklon piću, ispičutura (pež.).',
 'čuvarina': 'Nagrada, plata čuvaru za čuvanje.',
}

C = {
 'vilima': 'glosa fragmentarna (deo odrednice „duel"); značenje nejasno',
 'tonja': 'glosa OCR-nečitka (botanička) — nesigurno',
 'tosti': 'glosa fragmentarna; značenje nejasno',
 'vratan': 'glosa fragmentarna; značenje nejasno',
 'vori': 'glosa fragmentarna (deo odrednice „tribina"); značenje nejasno',
 'voš': 'glosa fragmentarna (deo odrednice „živeti"); značenje nejasno',
 'voša': 'glosa fragmentarna; značenje nejasno',
 'vulja': 'glosa fragmentarna; značenje nejasno',
 'zapišati': 'vulgarno (vulg. pomokriti); rečnik takve reči ne vodi',
 'zak': 'glosa fragmentarna; značenje nejasno',
 'zana': 'glosa fragmentarna (deo odrednice „zaneti"); značenje nejasno',
 'zareve': 'glosa fragmentarna; značenje nejasno',
 'zdeni': 'glosa fragmentarna (deo odrednice „gvozden"); značenje nejasno',
 'zdravcat': 'glosa nejasna (intenzivirajući oblik od „zdrav"?) — nesigurno',
 'Zelanda': 'deo višečlanog imena „Novi Zeland"; samostalno nepostojeće — vlasnica odlučuje',
 'Zelande': 'deo višečlanog imena „Novi Zeland"; samostalno nepostojeće — vlasnica odlučuje',
 'Zelandi': 'deo višečlanog imena „Novi Zeland"; samostalno nepostojeće — vlasnica odlučuje',
 'Zelandima': 'deo višečlanog imena „Novi Zeland"; samostalno nepostojeće — vlasnica odlučuje',
 'Zelandom': 'deo višečlanog imena „Novi Zeland"; samostalno nepostojeće — vlasnica odlučuje',
 'Zelandu': 'deo višečlanog imena „Novi Zeland"; samostalno nepostojeće — vlasnica odlučuje',
 'zika': 'glosa pogrešno uhvaćena (deo odrednice „azbuka"); značenje nejasno',
 'zike': 'glosa fragmentarna; značenje nejasno',
 'zilu': 'glosa fragmentarna (deo odrednice „kad"); značenje nejasno',
 'ziti': 'glosa fragmentarna; značenje nejasno',
 'znika': 'glosa fragmentarna; značenje nejasno',
 'ćama': 'glosa fragmentarna; značenje nejasno',
 'ćući': 'glosa fragmentarna (deo odrednice „obići"); značenje nejasno',
 'čangrizavac': 'glosa kružna (osnovni glagol „čangrizati" bez tumačenja ovde) — nesigurno',
 'čangrizavost': 'familija „čangrizav" — osnova nejasna — nesigurno',
 'čani': 'glosa fragmentarna; značenje nejasno',
 'čaporast': 'glosa kružna/OCR-nejasna (osnova „čaporak" nejasna) — nesigurno',
 'čati': 'glosa fragmentarna; značenje nejasno',
 'čelju': 'glosa fragmentarna; značenje nejasno',
 'čere': 'glosa fragmentarna; značenje nejasno',
 'čeri': 'glosa fragmentarna (deo odrednice „večer"); značenje nejasno',
 'čić': 'značenje nejasno (idiom „živeti kao čić"); vlasnica odlučuje',
 'čići': 'značenje nejasno (idiom „živeti kao čić"); vlasnica odlučuje',
 'čiš': 'moguće „čiš" (čelični nož za obeležavanje stabala); dodela glosa nesigurna',
 'čiši': 'gen. oblika „čiš"; dodela glosa nesigurna',
}
