# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 991–1320 (hramben … koštunjavost).

DEC = {
 'hramben': 'Koji se odnosi na hranu, prehrambeni.',
 'hranidba': 'Hranjenje, ishrana; način ishranjivanja (hranidba životinja, biljaka, useva).',
 'hranivo': 'Ono što služi za ishranu, hrana (hranivo za biljke, za životinje).',
 'hranjivost': 'Osobina onoga što je hranjivo, hranljivost.',
 'hrastik': 'Hrastova šuma.',
 'hrastovača': 'Predmet napravljen od hrastovine, hrastova batina, motka, hrastov štap.',
 'hrašće': 'Zbirna imenica od hrast; hrastova šuma, hrastik.',
 'hridinast': 'Koji je kao hrid; stenovit, hridovit (hridinasta obala).',
 'hripav': 'Koji je praćen hripom (hripav glas, kašalj).',
 'hrizolit': 'Vrsta dragog kamena bistre zelene boje (min., grč.).',
 'hrka': 'Hrkanje, šumno disanje pri spavanju sa otvorenim ustima.',
 'hrkač': 'Onaj koji hrče.',
 'hrnjavost': 'Osobina onoga koji je hrnjav, onoga što je hrnjavo.',
 'hrpteni': 'Koji se odnosi na hrbat, leđni, kičmeni (hrpteni pršljen, moždina).',
 'hrskati': 'Šumno drobiti ili lomiti zubima, krikati (hrskati koru hleba, orahe, lešnike); (hrskati se) odavati karakterističan, oštar, isprekidan šum lomeći se, krikajući se pod pritiskom.',
 'hrvatka': 'Vrsta hrvatske narodne kape crvene boje (etn., ist.).',
 'hulitelj': 'Onaj koji huli.',
 'humanistkinja': 'Žena humanista.',
 'humić': 'Umanjenica od hum.',
 'humorističan': 'Koji sadrži humora, prožet humorom, šaljiv, duhovit; koji je rađen u stilu humoristike (humoristična pripovetka, emisija, film); i sklon humoru, koji ima dara za humor (humorističan pisac).',
 'humoristkinja': 'Žena humorista.',
 'hungarizam': 'Mađarska reč ili mađarski jezički izraz u nekom drugom jeziku (lingv.).',
 'hvatište': 'Deo predmeta za koji se hvata; mesto oslonca (služiti kao hvatište, hvatište u steni).',
 'idiličnost': 'Stanje i osobina onoga što je idilično.',
 'igleni': 'Koji se odnosi na iglu (iglene uši); provući se kroz iglene uši — biti veoma snalažljiv, vešt.',
 'iglun': 'Vrsta morske ribe (zool.).',
 'ihtiolog': 'Proučavalac riba.',
 'ikavac': 'Onaj koji govori ikavski.',
 'ikavština': 'Ikavski način izgovora i pisanja (lingv.).',
 'ikolik': 'Pridevska neodređena zamenica: bilo koliki, ma koliki (da mi je ikoliko hleba pojesti).',
 'ikraš': 'Riba (ženka) puna ikre.',
 'ilegalka': 'Žena ilegalac.',
 'ilirac': 'Pristalica ilirskog pokreta, ilirizma.',
 'ilovast': 'Načinjen od ilovače, glinen (ilovasti sud, peć); i koji u sebi sadrži ilovaču, glinovit (ilovasto tlo, zemlja).',
 'iluminator': 'Prosvetitelj; svetlarnik; ist. srednjovekovni pisar, slikar koji je ornamentima ilustrovao crkvene knjige (lat.).',
 'imperativno': 'Na imperativan način, zapovednički; neodložno, neminovno (imperativno saopštiti, nalagati).',
 'impotentnost': 'Impotencija; nemoć, nesposobnost (duhovna, polna).',
 'individualitet': 'Osoba izrazite individualnosti; autoritet (epoha jakih individualiteta); i individualnost.',
 'indoktrinirati': 'Nametnuti, nametati neku doktrinu, silom usmeriti, usmeravati nečije mišljenje, stavove (indoktrinirati omladinu, narod).',
 'induktivno': 'Na induktivan način, induktivnim putem (induktivno dokazati).',
 'informativnost': 'Stanje, osobina onoga što je informativno.',
 'informbirovac': 'Pristalica rezolucije Informbiroa od juna 1948.',
 'inkarnirati': 'Oličiti, oličavati, ovaplotiti, ovaploćivati (ideju, svojstvo, lik i sl.).',
 'inkompatibilnost': 'Stanje onoga što je inkompatibilno, nesaglasnost.',
 'inovatorstvo': 'Delatnost inovatora, pronalazaštvo.',
 'inoverstvo': 'Drugačija vera, verska različitost.',
 'institucionalizovati': 'Pretvoriti, pretvarati u instituciju, ustanoviti, ustanovljivati (institucionalizovati saradnju).',
 'instruktivan': 'Poučan (instruktivan časopis).',
 'instrumentalizovati': 'Pretvoriti, pretvarati u oruđe, instrument za određene ciljeve (instrumentalizovati borbu za ljudska prava).',
 'integrativan': 'Koji služi integraciji, ujedinjenju (integrativan činilac, snaga).',
 'interdikt': 'Izričita naredba da se nešto ne sme izvršiti; ist. papina zabrana vršenja crkvenih obreda kao kaznena mera (lat.).',
 'interesantnost': 'Osobina onoga što je interesantno.',
 'internacionalac': 'Učesnik internacionale, pristalica internacionalizma, internacionalista; sport. igrač koji nastupa na međunarodnim takmičenjima; i igrač neke zemlje koji igra u inostranom klubu.',
 'internacionalan': 'Koji se odnosi na sve ili na mnoge narode, opšti, međunarodni (internacionalna ideja, komisija, dug).',
 'internacionalnost': 'Osobina onoga koji je internacionalan, onoga što je internacionalno.',
 'interpolirati': 'Naknadno umetati, umetnuti u tekst; falsifikovati dodavanjem novih reči ili rečenica; doda(va)ti, umetnuti, umetati.',
 'intervencionizam': 'Politika zasnovana na (vojnim, ekonomskim i sl.) intervencijama.',
 'intramuskularno': 'Na intramuskularan način (dati injekciju intramuskularno).',
 'inverzan': 'Koji je u inverziji, obrnut, preokrenut.',
 'inzulin': 'Hormon žlezde gušterače koji dolazi u krv i reguliše količinu šećera u organizmu (med.).',
 'iracionalizam': 'Filozofsko idealističko shvatanje po kome se suština sveta ne može objasniti razumom niti logički.',
 'isceliteljski': 'Koji isceljuje, koji dovodi do isceljenja (isceliteljska moć).',
 'isfenirati': 'Osušiti fenom (isfenirati kosu).',
 'ishlapljiv': 'Koji lako ishlapi, isparljiv.',
 'ishlapljivati': 'Nesvršeni oblik glagola „ishlapeti".',
 'iskoraknuti': 'Isto što i iskoračiti.',
 'iskoračivati': 'Nesvršeni oblik glagola „iskoračiti".',
 'iskorenjivati': 'Nesvršeni oblik glagola „iskoreniti".',
 'iskriti': 'Ispuštati iskre, varnice, varničiti (o vatri i dr.); preneseno: blistati, sijati, treperiti svetlucavo (o dragom kamenju, vodi i dr.); sevati (o očima); i izbijati poput iskre (o snazi, osećanju i sl.).',
 'iskrivljavati': 'Nesvršeni oblik glagola „iskriviti (se)".',
 'iskričavost': 'Osobina, stanje onoga što je iskričavo.',
 'iskrižati': 'Iseći, izrezati na kriške, na komade (iskrižati jabuku, lubenicu); i precrtati (iskrižati napisani tekst).',
 'iskucati': 'Udarcima proizvesti zvuk, otkucaje; oglasiti kucanjem, otkucati (o satu); izbaciti, izbiti kucanjem, udaranjem nešto iz ležišta (iskucati čep); i ispisati kucajući na pisaćoj mašini ili računaru (iskucati članak).',
 'iskupati': 'Dobro okupati (iskupati decu); (iskupati se) dobro se okupati.',
 'isparati': 'Rasparati nešto sašiveno, ocepiti, razderati (isparati platno, list iz knjige); i izbrazdati, iseći, raskomadati; (isparati se) izrebati se (po nogama idući kroz trnje).',
 'ispatiti': 'Izmučiti patnjama; (ispatiti se) namučiti se, napatiti se.',
 'isplivavati': 'Nesvršeni oblik glagola „isplivati".',
 'ispotpisivati': 'Potpisati veći broj dokumenata, pisama i sl.; potpisati neki dokument (o većem broju lica) (ispotpisivati sva akta, neku izjavu); (ispotpisivati se) potpisati se (o većem broju lica ili na više mesta).',
 'ispozdravljati': '(Ispozdravljati se) pozdraviti se sa većim brojem lica.',
 'isprašivati': 'Nesvršeni oblik glagola „isprašiti".',
 'isprdak': 'Ono što se malo, sitno rodilo, obično o detetu (ekspresivno).',
 'ispremešati': 'Izmešati, pomešati; zbrkati, isprefurati (ispremešati članke, sve po kući); (ispremešati se) izmešati se, pomešati se; zbrkati se.',
 'isprepletanost': 'Stanje onoga što je isprepletano.',
 'ispreskakati': 'Preskočiti više puta, više objekata (ispreskakati ograde); preneseno: nadmudriti nekoga vešto pobijajući njegove stavove u odgovoru.',
 'isprevrtati': 'Prevrnuti, prefuriti više predmeta; ispremešati, ispreturati (isprevrtati korpe, zemlju); (isprevrtati se) prevrnuti se, izvrnuti se.',
 'ispripovediti': 'Isto što i ispripovedati.',
 'isprogramirati': 'Nabraviti program; isplanirati.',
 'ispucavati': 'Nesvršeni oblik glagola „ispucati".',
 'ispupčiti': 'Isturiti, izbočiti, isprsiti (ispupčiti trbuh, grudi); i napućiti (ispupčiti usne); (ispupčiti se) isturiti se, izbočiti se.',
 'istaknutost': 'Osobina onoga što je istaknuto.',
 'istaložiti': 'Izdvojiti taloženjem; (istaložiti se) izdvojiti se taloženjem (o vodi i sl.).',
 'istestirati': 'Ispitati, proveriti pomoću testa (istestirati program, učenike).',
 'isteturati': 'Izići teturajući.',
 'istorodnost': 'Osobina onoga što je istorodno, srodnost.',
 'istočnica': 'Ona koja je izvor nečega, ona od koje što potiče (istočnica moje sreće).',
 'istrgati': 'Iskidati na komade, raskomadati (vuci su ovcu istrgali); i pocepati, poderati (istrgati šešir); (istrgati se) razbiti se na delove, razdvojiti se.',
 'isusovac': 'Pripadnik katoličkog kaluđerskog reda Družbe Isusove, jezuit.',
 'isušenost': 'Stanje i osobina onoga što je isušeno.',
 'ivančica': 'Biljka volovsko oko (bot.).',
 'izanalizirati': 'Izvršiti analizu.',
 'izbeliti': 'Učiniti belim (pranjem, iskuvavanjem, mazanjem i sl.).',
 'izbetonirati': 'Izraditi od betona, obložiti betonom (izbetonirati tunel).',
 'izbezumljenost': 'Osobina i stanje onoga koji je izbezumljen.',
 'izbirljivost': 'Osobina onoga koji je izbirljiv, probirljivost.',
 'izblebetati': 'Reći kojišta, izbrbljati; (izblebetati se) nepromišljeno reći, izbrbljati se.',
 'izbočiti': 'Dati čemu izbočen oblik, ispupčiti, isturiti (izbočiti trbuh, grudi); (izbočiti se) isturiti se, ispupčiti se.',
 'izdovoljiti': 'Zadovoljiti u punoj meri (izdovoljiti srce); (izdovoljiti se) zadovoljiti se u punoj meri.',
 'izdriblati': 'Driblajući prevariti.',
 'izdubina': 'Izdubljeno mesto, rupa; udubljenje.',
 'izdurati': 'Izdržati neki napor; istrajati u nekoj teškoj situaciji (izdurati od gladi, izdurati ove zime bez drva).',
 'izdušiti': 'Izbiti, izaći, isteći iz nečega (o gasovima); izvetriti; ispustiti vazduh (guma je izdušila); i izgovoriti, izustiti (izdušiti kroz plač); (izdušiti se) dati sebi oduška.',
 'izgalamiti': '(Izgalamiti se) izvikati se.',
 'izgladnelost': 'Stanje onoga koji je izgladneo; glad.',
 'izgladniti': 'Iznuriti, izmučiti nekoga glađu.',
 'izgrađenost': 'Osobina onoga što je izgrađeno, razvijenost.',
 'izgrliti': 'Izraziti osećanje prema nekome grleći ga duže; (izgrliti se) uzajamno se izgrliti.',
 'izgubljenost': 'Osobina i stanje onoga koji je izgubljen, onoga što je izgubljeno.',
 'izguliti': 'Guleći oštetiti, povrediti, oguliti; i iščupati, izvaditi naglim pokretom (izguliti kolac iz plota).',
 'izguravati': 'Nesvršeni oblik glagola „izgurati".',
 'izlizanost': 'Stanje onoga što je izlizano.',
 'izlučenje': 'Izdvajanje, isključenje; izlučevina (izlučenje mleka).',
 'izmiritelj': 'Onaj koji izmiruje, miri.',
 'izmudriti': 'Doći do nečega umovanjem, mudrovanjem, pronaći (izmudriti neku spravu); i smisliti, izmisliti.',
 'izniman': 'Koji predstavlja iznimku, izuzetan, poseban (izniman slučaj, položaj).',
 'izobara': '(Obično u množini) linija koja na meteorološkoj karti spaja mesta sa istim vazdušnim, barometarskim pritiskom (met., grč.).',
 'izobličenost': 'Stanje onoga koji je izobličen, onoga što je izobličeno.',
 'izobrazba': 'Stručno usavršavanje; obrazovanje, naobrazba.',
 'izoglosa': 'Linija koja obuhvata i povezuje mesta s istim dijalekatskim osobinama (lingv.).',
 'izohipsa': 'Linija na geografskoj karti koja spaja mesta iste nadmorske visine (geogr., grč.).',
 'izolacionizam': 'Težnja ka sopstvenom odvajanju, držanju od ostaloga sveta, obično kao politički pokret u nekoj zemlji.',
 'izranjati': 'Nesvršeni oblik glagola „izroniti".',
 'izravnanje': 'Izjednačenje; usaglašavanje, usklađenje.',
 'izračiti': 'Provetriti (izračiti sobu); (izračiti se) provetriti se, osvežiti se.',
 'izrađenost': 'Stanje, osobina onoga koji je izrađen, onoga što je izrađeno.',
 'izraženost': 'Svojstvo, osobina onoga što je izraženo.',
 'izreciv': 'Koji se može izreći, iskazati.',
 'izreklamirati': 'Napraviti reklamu, reklamirati više puta.',
 'izrezak': 'Deo koji se izreže, odseče od nečega, isecak (izrezak iz novina); i isto što i izrez.',
 'izrezivati': 'Nesvršeni oblik glagola „izrezati".',
 'izrigati': 'Rgajući izbaciti iz usta, povratiti, izbljuvati; preneseno: izbaciti naglo, u velikim količinama (izrigati plamen); i iskaliti gnev nad nekim.',
 'izumiteljica': 'Ženska osoba izumitelj.',
 'izvikivač': 'Onaj koji izvikuje, vičući saopštava (izvikivač parola).',
 'izvitoperiti': 'Saviti, iskriviti, izviti (izvitoperiti prste, motku); preneseno: izopačiti, iskriviti; (izvitoperiti se) saviti se, iskriviti se; preneseno: izobličiti se, izopačiti se.',
 'izvlakač': 'Naprava u sklopu zatvarača na vatrenom oružju kojom se izvlači čahura ili neispaljeni metak iz cevi ili ležišta (voj.).',
 'izvlastiti': 'Lišiti vlasništva, vlasničkog prava.',
 'izvrteti': 'Vrteći izbušiti, izdubiti (izvrteti rupu u zidu); preneseno razg. izdejstvovati, izmoliti (izvrteti kredit od banke).',
 'kabotaža': 'Obalska plovidba, obično između pristaništa (mala, velika kabotaža) (pom., fr.).',
 'kadiluk': 'Sudsko područje kadije; zvanje kadije (tur., ist.).',
 'kadli': 'Veznik koji označava da se nešto neočekivano dogodilo, nastalo: a to, a ono (obazre se, kadli njega nema).',
 'kaduljin': 'Koji pripada kadulji (kaduljin cvet, miris).',
 'kalac': 'Mlada trava; i vrsta biljke (bot.).',
 'kalan': 'Isto što i kaljav (arh., pesn.).',
 'kalibarski': 'Koji se odnosi na kalibar (kalibarsko gađanje).',
 'kaljužina': 'Uvećanica i pežorativ od kaljuga i kaljuža.',
 'kalkulant': 'Isto što i kalkulator; preneseno: proračunat čovek, račundžija.',
 'kaloričnost': 'Osobina onoga što je kalorično; kalorična vrednost nečega.',
 'kaluđerov': 'Koji pripada kaluđeru (kaluđerovo lice).',
 'kaluđerčić': 'Umanjenica i nežni oblik od kaluđer.',
 'kamenast': 'Tvrd kao kamen (kamenasta masa); i kameni, krševit.',
 'kamforovac': 'Kamforovo drvo (bot.).',
 'kamgarn': 'Vuneno predivo; tkanina od tog prediva (nem.).',
 'kamoli': 'Veznik koji (često uz „a") ističe da je ono što se govori prirodna posledica onoga što je već rečeno (nema ona ni momka, a kamoli verenika).',
 'kampanilizam': 'Lokalni, uskogrudi patriotizam (ital.).',
 'kanalni': 'Koji se odnosi na kanal (kanalni sistem, cev, voda).',
 'kanjac': 'Morska mediteranska riba koštunjača (zool.).',
 'kantovac': 'Pristalica Kantove filozofije.',
 'kapetanstvo': 'Zvanje, čin kapetana; kapetanska služba.',
 'kapetančić': 'Umanjenica i nežni oblik od kapetan.',
 'kapirati': 'Shvatati (shvatiti), razume(va)ti (razg., ital.).',
 'kapljevina': 'Mast koja istekne pri pečenju praseta, jagnjeta i sl., preštoc; tečnost uopšte.',
 'kaptaža': 'Prikupljanje i odvođenje podzemne vode pomoću naročitih instalacija; bazen od betona sagrađen iznad mesta gde izvire voda (fr.).',
 'kapula': 'Crni luk (agr.); i jelo od zgnječenog pasulja i luka (lat.).',
 'karbunkul': 'Prišt, čir (med., lat.).',
 'karcinogen': 'Koji se odnosi na karcinom, koji je u vezi s karcinomom (karcinogeno oboljenje).',
 'kardan': 'Mehanički zglob kojim se obrtanje prenosi s jednog vratila na drugo, kod vozila, mašina i sl. (maš.).',
 'karniša': 'Šipka iznad prozora, vrata i sl. za koju se pričvršćuje zavesa (fr.).',
 'kartirati': 'Izraditi kartu nekog terena; uneti, unositi podatke u kartu (kartirati teren); i opis(iv)ati, evidentirati (kartirati podatke, robu).',
 'kat': 'Sprat (kuća na dva kata); i red ili sloj nečega, niz, niska (katovi šljunka) (tur.).',
 'katarakt': 'Vodopad, slap na reci, potoku; i siva mrena, bolest očnog sočiva (med., grč.).',
 'kategoričan': 'Jasno određen, bezuslovan, odlučan (kategorična naredba, forma).',
 'kategoričnost': 'Osobina, svojstvo onoga što je kategorično, onoga koji je kategoričan.',
 'kateheta': 'Nastavnik kateheze, veroučitelj.',
 'kauk': 'Glas ćurke (uzvik).',
 'kaučukov': 'Koji pripada kaučuku, koji se odnosi na kaučuk (kaučukovo drvo).',
 'kaučukovac': 'Drvo koje luči kaučuk (bot.).',
 'kavovina': 'Surogat kafe, od mlevenog prženog ječma.',
 'kaštelan': 'U srednjem veku nadzornik tvrđave.',
 'keder': 'Sitna riba koja služi kao mamac za lov većih riba (rib., nem.).',
 'kedrovina': 'Kedrovo drvo.',
 'kenjac': 'Mađarac; pežorativno: tvrdoglav čovek.',
 'kenjkati': 'Povremeno plakati, kmeziti; biti bolešljiv, slabunjav.',
 'kerina': 'Uvećanica i pežorativ od ker.',
 'kestenik': 'Kestenova šuma.',
 'kestenjar': 'Kestenova šuma; i onaj koji peče i prodaje kestenje.',
 'kestenovina': 'Kestenovo drvo, kesten.',
 'kibernetičar': 'Stručnjak koji se bavi kibernetikom.',
 'kilavost': 'Stanje onoga koji je kilav; lenjost.',
 'kininovac': 'Isto što i kina, kinino drvo (bot.).',
 'kitina': 'Arh. sneg koji se zadržava na granama drveća; i cveće na granama voća, gusto lisnato granje; bot. vrsta jasmina.',
 'kitolov': 'Lov na kitove.',
 'kićenost': 'Osobina, svojstvo onoga koji je kićen, onoga što je kićeno (kićenost u arhitekturi, izraza).',
 'kičast': 'Koji ima osobine kiča, umetnički bezverdan (kičast tekst, grad).',
 'kladilac': 'Onaj koji se kladi, učesnik u opkladi.',
 'klančić': 'Umanjenica od klanac.',
 'klapati': 'Biti u redu, ići dobro, kako treba: negde nešto „ne klapa"; i biti tačan, odgovarati, podudarati se: sve je klapalo (razg.).',
 'klapina': 'Zelena kora, ljuska ploda nekih voćaka (oraha, badema i sl.).',
 'klasan': 'Koji se odnosi na klas, prekriven klasjem (klasno polje).',
 'klasić': 'Umanjenica i nežni oblik od klas.',
 'klasičnost': 'Svojstvo onoga što je klasično, što se odnosi na klasičnu književnost; lepota, savršenstvo (grčka klasičnost, klasičnost dela, pokreta).',
 'klauzura': 'Deo katoličkog samostana u koji nemaju pristupa svetovna lica; i vreme koje redovnici u samostanu provode u osamljenosti, molitvi i razmišljanju (lat.).',
 'klačina': 'Mesto gde se peče kreč; krečana.',
 'klenić': 'Umanjenica i nežni oblik od klen.',
 'klepac': 'Čekić za otkivanje kose; i čekić za oštrenje vodeničkog kamena.',
 'klepač': 'Onaj koji klepa, otkiva kosu.',
 'klicin': 'Koji pripada klici, koji se odnosi na klicu (klicin listić, koren).',
 'kliktavo': 'Sa usklicima, uz kliktanje; razdragano, veselo (kliktavo pevati, pričati).',
 'klimakteričan': 'Koji se odnosi na klimakterijum (klimakterične godine, pojave); i preloman, krizičan (klimakterični dani).',
 'klimatološki': 'Koji se odnosi na klimatologiju (klimatološko izučavanje, rasprava); i isto što i klimatski.',
 'klimavost': 'Osobina onoga koji je klimav, onoga što je klimavo.',
 'klincov': 'Krupan momak, klipan (ekspresivno).',
 'kliničar': 'Lekar koji kao naučni radnik radi na klinici.',
 'klipić': 'Umanjenica od klip.',
 'klipsati': 'Teško ići, jedva se vući.',
 'klisurina': 'Uvećanica od klisura.',
 'kljunak': 'Umanjenica i nežni oblik od kljun.',
 'kljunaš': 'Isto što i kljunar (zool.); i (množina) insekti s ustima produženim u rilicu, riličari.',
 'klobučar': 'Onaj koji izrađuje i prodaje klobuke, šeširdžija.',
 'klobučina': 'Vrsta gustog mekanog materijala od koga se prave klobuci, šeširi, papuče i sl.',
 'klokotaš': 'Vrsta orla, u izrazima „orao klokotaš", „veliki klokotaš" (zool.).',
 'klošarski': 'Koji se odnosi na klošare, svojstven klošarima (klošarski život).',
 'kmetovski': 'Koji se odnosi na kmeta i kmetove (kmetovski zakon, služba, disciplina).',
 'knap': 'Samo toliko koliko treba, taman, dovoljno: sve su izračunali da im je knap (nem., razg.).',
 'knjižarstvo': 'Izdavanje, prodaja i distribucija knjiga, časopisa i sl., izdavačka delatnost; i proučavanje knjige kao kulturne pojave i proizvodnje.',
 'knjižničar': 'Stručni službenik u knjižnici, bibliotekar.',
 'knjižničarstvo': 'Knjižničarski posao, bibliotekarstvo.',
 'koalirati': 'Uključiti, uključivati u koaliciju, ujedinjavati; (koalirati se) sklopiti, sklapati savez, koaliciju.',
 'kobasičarstvo': 'Kobasičarski posao, zanat.',
 'kobasičast': 'Koji ima izgled kobasice (kobasičast špalir).',
 'kodifikator': 'Sastavljač kodeksa, zakonika (pravn.).',
 'koketnost': 'Osobina onoga koji je koketan, onoga što je koketno; zavodljivost.',
 'kokotić': 'Umanjenica i nežni oblik od kokoš.',
 'kolaboracionizam': 'Saradnja s okupatorom u vreme Drugog svetskog rata.',
 'kolektivitet': 'Zajednica, kolektiv.',
 'kolektivizam': 'Doktrina koja ističe vrednost i značaj kolektivnosti, zajedništva (fil.); sklonost za kolektivni život, privrženost zajednici; ekon. poredak zasnovan na kolektivnoj svojini.',
 'kolektivnost': 'Osobina, stanje onoga što je kolektivno, združenost, kolektivizam.',
 'kolenski': 'Koji se odnosi na koleno (kolenski zglob, čašica).',
 'kolibrić': 'Kolibri; umanjenica i nežni oblik od kolibri.',
 'kolišno': 'U umanjenom značenju: koliko (kolišno nas je došlo).',
 'koljuška': 'Mala morska riba (zool.).',
 'kolutast': 'Koji je kao kolut, sličan kolutu (kolutast oblik, narukvica).',
 'kolutić': 'Umanjenica od kolut.',
 'komadni': 'Koji se sastoji od komada (komadni nameštaj, pošiljka).',
 'kombinatoran': 'Koji je pun kombinacija, koji se odlikuje kombinacijama (kombinatorna igra, igrač).',
 'kombinatorika': 'Pravljenje kombinacija, kombinovanje; sposobnost za kombinovanje.',
 'komemorativan': 'Koji se odnosi na komemoraciju; koji služi u znak sećanja (komemorativno veče u spomen velikom piscu).',
 'komesarstvo': 'Obavljanje komesarske dužnosti; zvanje komesara.',
 'komov': 'Koji pripada komu, načinjen od koma; uporedi komina (komova rakija).',
 'kompetentnost': 'Osobina onoga koji je kompetentan, kompetencija.',
 'kompozitan': 'Sastavljen od više delova, složen (kompozitna masa, cvet).',
 'kompozitorka': 'Ženska osoba kompozitor.',
 'komunjarski': 'Pežorativno: koji se odnosi na komunjare, koji pripada komunjarama, svojstven komunjarama i sl.',
 'koncertirati': 'Javno davati koncert, biti izvođač na koncertu (koncertirati u Novom Sadu).',
 'kondukterka': 'Ženska osoba kondukter.',
 'konfinirati': 'Graničiti, ograničavati nekome slobodu kretanja, internirati (lat., fr.).',
 'konfrontirati': 'Izaz(i)vati konfrontaciju nečega (nekoga), uporediti, upoređivati, suprotstaviti, suprotstavljati (konfrontirati dva suprotna gledišta); (konfrontirati se) dospe(va)ti u konfrontaciju, suprotstaviti se.',
 'konfucionizam': 'Religiozno-filozofsko učenje koje je zasnovao starokineski mislilac Konfucije.',
 'konopljarka': 'Naziv za neke ptice pevačice koje žive po ređim šumama (zool.).',
 'konsekventno': 'Na konsekventan način, dosledno (konsekventno graditi svoj ugled, sprovoditi odluke).',
 'konsolidovati': 'Izvršiti konsolidaciju nečega, učvrstiti, učvršćivati, srediti, sređivati (konsolidovati državu, položaj); (konsolidovati se) srediti se, stabilizovati se.',
 'konstantnost': 'Osobina onoga što je konstantno, postojanost, nepromenljivost (konstantnost kretanja).',
 'konstruktivizam': 'Pravac u arhitekturi i umetnosti nastao početkom XX veka koji naglašava elemente konstrukcije.',
 'konstruktivnost': 'Osobina, svojstvo onoga što je konstruktivno.',
 'kontinentalac': 'Čovek koji živi na kontinentu, kopnu, daleko od mora.',
 'kontinentalan': 'Koji se odnosi na kontinent; kopneni (kontinentalna zemlja, klima, način života).',
 'kontraalt': 'Najdublji ženski glas, duboki alt (muz., ital.).',
 'konveksnost': 'Osobina onoga što je konveksno, ispupčenost.',
 'konvergirati': 'Posta(ja)ti sličan; približiti se, približavati se nekoj zajedničkoj granici; steći se, sticati se u zajedničkoj tački (lat.).',
 'konvertibilnost': 'Svojstvo onoga što je konvertibilno, zamenljivost, promenljivost (konvertibilnost menice); i slobodna mogućnost zamene nacionalnog novca u zlato ili strane valute (fin.).',
 'konzervativizam': 'Konzervativni nazori i shvatanja, privrženost starom, a odbojnost prema novom, progresivnom.',
 'konzervativka': 'Žena konzervativnih pogleda.',
 'konzervativnost': 'Osobina onoga koji je konzervativan, onoga što je konzervativno; nazadnost, staromodnost.',
 'konzistentnost': 'Osobina, stanje onoga što je konzistentno.',
 'končan': 'Koji je načinjen, izrađen od konca (končana čarapa, bluza).',
 'koprenast': 'Koji je nalik na koprenu, mrežast, providan (koprenasta zastava, magla).',
 'koprivin': 'Koji pripada koprivi, koji se odnosi na koprivu.',
 'koprivnjak': 'Mesto gde rastu koprive, mesto zaraslo koprivom; zool. isto što i koprivar.',
 'kopula': 'Veza, spona; lingv. oblik pomoćnog glagola koji veže subjekt i imenski deo predikata; log. reč koja u svakom sudu povezuje subjekat s predikatom (lat.).',
 'kopčić': 'Umanjenica i nežni oblik od kopča.',
 'koreferat': 'Dopunski referat, izveštaj.',
 'korenjak': 'Mlada biljka nastala sađenjem grane ili korena, koja služi kao sadnica.',
 'koristoljubivost': 'Osobina onoga koji je koristoljubiv; koristoljublje.',
 'koritast': 'Koji ima oblik korita, sličan koritu (koritasto udubljenje, teren).',
 'korizmen': 'Koji se odnosi na korizmu (korizmeni post, korizmena nedelja).',
 'kormilariti': 'Rukovati kormilom; upravljati lađom, brodom i dr.; manevrisati brodom i sl.',
 'kornjaš': '(U množini) rod insekata sa dva para krila, tvrdokrilac; (u jednini) insekt iz tog roda (zool.).',
 'korpulentnost': 'Osobina i stanje onoga koji je korpulentan, telesno razvijen; krupnoća; ugojenost (lat.).',
 'kosar': 'Kovač koji pravi, kuje kose.',
 'kositren': 'Koji je od kositra, kalajni; koji ima boju kositra (kositrena kašika, tanjir).',
 'kosmopolitizam': 'Ideologija koja negira nacionalne osobenosti, shvatanje po kojem ne treba da postoje nacionalne i državne granice; težnja za zbližavanjem ljudi bez obzira na njihovu nacionalnu, konfesionalnu ili bilo kakvu drugu posebnu pripadnost.',
 'kosturina': 'Uvećanica i pežorativ od kost i kostur.',
 'koturak': 'Umanjenica od kotur; uporedi koturić.',
 'koturast': 'Sličan koturu — pretenast, okrugao i sl. (koturast oblik).',
 'kovaonica': 'Isto što i kovačnica.',
 'kočar': 'Ribar koji lovi pomoću koče; i vrsta ribarskog broda koji teglji koču (rib.).',
 'košarač': 'Onaj koji izrađuje košare i druge predmete od pruća, trske i sl., korpar.',
 'košaraštvo': 'Isto što i korparstvo; uporedi košarstvo.',
 'košarić': 'Umanjenica od košar.',
 'košnja': 'Košenje, kosidba.',
 'koštunjavost': 'Stanje i osobina, svojstvo onoga koji je koštunjav, odnosno onoga što je koštunjavo.',
 'insolventnost': 'Nesposobnost plaćanja; insolvencija (lat.).',
 'kopredsednik': 'Jedan od dva predsednika.',
 'grlobolja': 'Bolest grla, gušobolja.',
 'izrabiti': 'Iskoristiti, iskorišćavati nekoga, nešto.',
}

C = {
 'hruskavac': 'glosa samo uput na „hrskavac" koji nije u našem rečniku; značenje nesigurno',
 'karska': 'glosa pogrešno uhvaćena (tuđa odrednica „bijenale"); značenje nejasno',
 'karskih': 'glosa pogrešno uhvaćena (tuđa odrednica); značenje nejasno',
 'kavaši': 'glagolski oblik; u Matici samo unutar glosa — značenje nejasno',
 'kice': 'glosa fragmentarna; značenje nejasno',
 'klopcem': 'instrumental oblika „klopac"; glosa nejasna iz isečka',
 'kodili': 'glosa fragmentarna (isečak iz odrednice „puzavac"); značenje nejasno',
 'kona': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'kone': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'konom': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'konšaki': 'glosa fragmentarna (isečak iz odrednice „kidati"); značenje nejasno',
 'kontrirati': 'glosa odsečena u OCR-u — nepotpuna',
 'koromač': 'botanička glosa OCR-nečitka; čitljivo samo „višegodišnja biljka" — previše tanko',
 'kozlac': 'botanička glosa OCR-nečitka (rod nečitljiv) — nesigurno',
 'kovrčica': 'umanjenica; osnovna reč OCR-nejasna („kovrča"?) — nesigurno',
 'iže': 'glosa fragmentarna (deo odrednice „prestiž"); značenje nejasno',
 'izviranju': 'dativ gl. imenice „izviranje"; glosa nije uhvaćena — nesigurno',
 'iredentizam': 'glosa odsečena u OCR-u („nacionalni pokret u nekom ze-…") — nepotpuna',
 'kolutićavac': 'zoološka glosa OCR-nečitka — nesigurno',
}
