# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 661–990 (epigonski … hrakotina).

DEC = {
 'epigonski': 'Koji se odnosi na epigone (epigonsko delo, rad).',
 'epigramatičan': 'Koji se odnosi na epigrame, koji je kao u epigramima (epigramatičan stil, poezija).',
 'epigramatičar': 'Pisac epigrama.',
 'epistemološki': 'Sa stanovišta epistemologije, metodom epistemologije.',
 'epitelni': 'Koji se odnosi na epitel (epitelno tkivo, epitelne ćelije).',
 'epitrahilj': 'Deo liturgijske odeće pravoslavnih sveštenika u obliku duge široke trake sa izrezom za glavu (crkv., grč.).',
 'epizodičnost': 'Osobina onoga što je epizodično (epizodičnost radnje).',
 'eremit': 'Onaj koji se povukao od sveta, obično iz verskih ubeđenja; pustinjak, isposnik, usamljenik (grč.).',
 'eruptivnost': 'Osobina onoga što je eruptivno; naglost, neobuzdanost, žestina, silovitost (eruptivnost vulkana, plača).',
 'eshatolog': 'Sledbenik, stručnjak eshatologije.',
 'eshatološki': 'Koji se odnosi na eshatologiju; posmrtni, zagrobni.',
 'eskalator': 'Pokretna traka u obliku stepenica za masovno penjanje i silaženje (u metrou, velikim robnim kućama i sl.) (engl.).',
 'eskimka': 'Pripadnica eskimskog naroda.',
 'eskivaža': 'Veština izbegavanja neke obaveze, dužnosti (šatr.).',
 'estakada': 'Ograda od drvenih stubova; i platforma, most na stubovima za utovar i istovar; i barikada od stubova u reci za sprečavanje prilaza brodova (šp.).',
 'estetizam': 'Razvijeno osećanje za lepo, naročit smisao za lepotu forme; pridavanje velikog značaja formi umetničkog dela; jednostrani životni nazor po kome se sve posmatra sa estetskog stanovišta.',
 'etatistički': 'Koji se odnosi na etatizam (etatističke težnje).',
 'eteričnost': 'Osobina onoga što je eterično, fluidnost, nežnost, uzvišenost.',
 'eternit': 'Građevinski materijal od smese cementa i azbesta u obliku tankih ploča.',
 'eterski': 'Koji se odnosi na etar, eteričan, etarski (etersko ulje).',
 'etnogenetički': 'Koji se odnosi na etnogenezu.',
 'etnogeneza': 'Poreklo, postanak i razvoj nekog naroda (grč.).',
 'etnomuzikolog': 'Stručnjak za etnomuzikologiju.',
 'eugeničar': 'Onaj koji se bavi eugenikom, stručnjak za eugeniku.',
 'evangelizam': 'Evanđeosko učenje.',
 'evaporator': 'Uređaj za evaporaciju, isparivač.',
 'evazivan': 'Teško shvatljiv, neodređen, nejasan; dvosmislen, uvijen (evazivan odgovor).',
 'evidentičar': 'Stručno ili osposobljeno lice koje vodi evidenciju nečega.',
 'evidentnost': 'Osobina onoga što je evidentno, očiglednost, očevidnost, dokazanost.',
 'evin': 'Koji pripada Evi; u izrazu „u evinom kostimu" — potpuno naga, gola (o ženskoj osobi).',
 'evokativno': 'Na evokativan način, izazivajući evokacije (delovati evokativno).',
 'evokator': 'Onaj koji nešto evocira, koji oživljava u sećanju uspomenu na nekoga ili nešto (lat.).',
 'evolucionistički': 'Koji se odnosi na evolucionizam i evolucioniste (evolucionistička teorija).',
 'evolucionizam': 'Naučna ili filozofska doktrina zasnovana na učenju o evoluciji; pogled na svet po kome sve nastaje razvojem, evolucijom (lat.).',
 'evropeid': '(U množini) pripadnici bele ljudske rase, koja se odlikuje svetlom bojom kože, mekom kosom, visokim ravnim čelom i dr.; (u jednini) pripadnik te rase (antrop.).',
 'ezoterik': 'Onaj koji je upućen u suštinu nekog učenja (grč.).',
 'ezoteričan': 'Koji je pristupačan samo uskom krugu upućenih, unutrašnji, skriven, tajni; strogo naučan, stručan (ezoterična književnost, shvatanje).',
 'fabrikat': 'Proizvod izrađen u fabrici, fabrički proizvod.',
 'fabularan': 'Narativan.',
 'fabulativan': 'Koji se odnosi na fabulu (fabulativna postavka romana).',
 'fakinski': 'Koji se odnosi na fakine, svojstven fakinima (fakinska neotesanost, prostakluk).',
 'fakinčić': 'Umanjenica od fakin.',
 'fanatičnost': 'Osobina fanatika, slepa zanesenost nekom idejom, uverenjem i sl., fanatizam.',
 'fantastičnost': 'Osobina onoga što je fantastično, onoga koji je fantastičan (fantastičnost snova, misli, motiva).',
 'faringitis': 'Zapaljenje sluzokože ždrela (med., grč.).',
 'farmaceutkinja': 'Ženska osoba farmaceut.',
 'fasader': 'Građevinski radnik stručnjak za izradu fasada.',
 'fat': 'Stopa kao mera za visinu u vazduhoplovstvu (engl.).',
 'favoritkinja': 'Ženska osoba favorit.',
 'felah': 'Seljak, zemljoradnik (ar.).',
 'feljtonistika': 'Pisanje feljtona kao književna vrsta.',
 'feljtonistički': 'Koji se odnosi na feljtoniste i feljtonistiku, svojstven feljtonistima (feljtonistička književnost).',
 'feminizirati': 'Učiniti, uticati da nešto dobije ženske osobine (feminizirati glas, izgled); (feminizirati se) dobijati ženske osobine.',
 'fenirati': 'Sušiti, šušiti kosu pomoću fena (fenirati kosu).',
 'fenomenalnost': 'Osobina onoga što je fenomenalno, onoga koji je fenomenalan (fenomenalnost pamćenja).',
 'fermati': 'Poštovati, ceniti, obazirati se na nekoga: ona ne ferma nikoga (tur., razg.).',
 'fibrinogen': 'Belančevina krvne plazme koja pod uticajem određenog fermenta prelazi u nerastvorljiv oblik, fibrin (biol.).',
 'fibrom': 'Vrsta benignog tumora, otok vezivnog tkiva (med., lat.).',
 'fiksati': '(Fiksati se) ubrizgavati sebi drogu injekcijom, drogirati se (žarg.).',
 'filir': 'Sitan austrougarski novac (mađ., ist.).',
 'filistarstvo': 'Osobine filistara, filistarski duh, karakter; malograđanština, uskogrudost.',
 'filmolog': 'Stručnjak koji se bavi pitanjima filma.',
 'filogenetski': 'Koji se odnosi na filogenezu (filogenetski razvoj vrsta).',
 'filozofkinja': 'Ženska osoba filozof.',
 'filtrat': 'Filtrirana, proceđena tečnost.',
 'finalan': 'Koji se javlja, dešava na završetku, završni, konačan, krajnji (finalna utakmica); i gotov, završen, spreman za upotrebu (finalni proizvodi); lingv. finalne rečenice — namerne rečenice.',
 'fiola': 'Bočica s dugim uskim grlićem koja se upotrebljava za čuvanje lako isparljivih tečnosti; bočica za lekove i sl. (farm., fr.).',
 'fiskalan': 'Koji se odnosi na fisk, državnu blagajnu, na državne prihode i rashode; novčani (fiskalna pitanja; fiskalna godina — obračunska godina).',
 'fisura': 'Pukotina, brazda na nekom materijalu (kamenu, drvetu, metalu i dr.); anat. brazda, procep (obično na kostima ili na mozgu) (lat.).',
 'fićuk': 'Zvižduk: fićuk dece, sirene (onom.).',
 'fićukati': 'Proizvoditi fićuk, zviždati, zviždukati (onom.).',
 'flagrantnost': 'Osobina onoga što je flagrantno, očevidnost.',
 'flok': 'Malo trouglasto jedro na pramcu jedrenjače (pom., nem.).',
 'folkloristika': 'Proučavanje folklora.',
 'fonolog': 'Lingvista koji se bavi fonologijom.',
 'fonometar': 'Aparat za merenje jačine glasa, u eksperimentalnoj fonetici (grč.).',
 'formalistički': 'Koji se odnosi na formalizam i formaliste; koji se zasniva na formalizmu, formalan (formalistička logika).',
 'formatirati': 'Podeliti (disk, disketu) na staze i sektore, pripremiti za zapis.',
 'forumski': 'Koji se odnosi na forume — politička rukovodeća tela (sistem forumskog odlučivanja).',
 'fosilizirati': 'Pretvoriti, pretvarati u fosile; (fosilizirati se) pretvoriti se, pretvarati se u fosile, okameniti se, skamenjivati se.',
 'fosilno': 'U obliku fosila.',
 'fot': 'Jedinica jačine svetla u fotografiji (1 lumen).',
 'foteljaš': 'Funkcioner koji uporno nastoji da dođe na vlast i da se održi na vlasti.',
 'foteljica': 'Umanjenica od fotelja.',
 'fotogeničnost': 'Osobina onoga koji je fotogeničan, onoga što je fotogenično (fotogeničnost glumice).',
 'fotokopirnica': 'Prostorija, radnja u kojoj se vrši fotokopiranje.',
 'fotosfera': 'Vidljiva svetla površina sunca koja kontinuirano emituje spektar svetlosti (astr., grč.).',
 'fototeka': 'Zbirka, arhiva fotografija i fotografskih negativa; mesto gde se čuva ta zbirka (policijska, novinska fototeka) (grč.).',
 'frakcionaš': 'Član frakcije, grupaš (pol.).',
 'frankofilski': 'Koji se odnosi na frankofile.',
 'frankovac': 'Pripadnik, pristalica reakcionarne političke stranke u Hrvatskoj koja je radila protiv ujedinjenja južnoslovenskih naroda, a na čelu joj je bio Josip Frank (ist.).',
 'fratrić': 'Umanjenica i nežni oblik od fratar.',
 'frcati': 'Naglo izbijati, iskakati, vrcati; brizati (npr. o iskrama, suzama i sl.); (frcati se) goniti se, pariti se (o mačkama).',
 'frenetičnost': 'Osobina i stanje onoga što je frenetično (frenetičnost aplaudiranja).',
 'frustriranost': 'Stanje i osobina onoga koji je frustriran.',
 'frustrirati': 'Dovesti, dovoditi nekoga u stanje frustracije, izaz(i)vati frustraciju kod nekoga (frustrirana opozicija, omladina).',
 'fuka': 'Fijukanje, zvižduk, huka: fuka oluje (onom.).',
 'fular': 'Vrsta lake svilene tkanine (fr.).',
 'funkcionalizam': 'Pravac u savremenoj arhitekturi koji se zalaže za svrsishodnu i logičnu organizaciju životnog prostora, tražeći da građevina oblikom jasno izražava svoju funkciju.',
 'fusak': 'Krznena vreća u koju se uvlače noge i donji deo tela pri vožnji saonicama ili kolima po velikoj hladnoći (nem.).',
 'gadov': 'Gadan, odvratan čovek.',
 'galebica': 'Ženka galeba.',
 'galeta': 'Vrsta kolača, dvopek (ital.; obično u množini).',
 'galja': 'Crna ovca.',
 'galonja': 'Vo crne dlake; i ime takvom volu.',
 'galvanometar': 'Aparat za merenje jačine i napona slabih električnih struja (fiz.).',
 'ganga': '(Obično u množini) narodna pesma koja se izvodi na način primitivne polifonije, jednoliko (hercegovačka ganga).',
 'garažirati': 'Smestiti, smeštati motorno vozilo u garažu.',
 'gastritičar': 'Onaj koji boluje od gastritisa.',
 'gastronom': 'Veštak u spremanju dobrih, ukusnih jela; poznavalac i ljubitelj ukusnih jela, gurman, sladokusac.',
 'gastroskop': 'Aparat koji se provlači kroz jednjak do želuca radi pregleda sluzokože želuca (med.).',
 'gatarina': 'Nagrada, plata za gatanje; vračarina.',
 'gater': 'Višestruka mašinska testera s motornim pogonom (nem.).',
 'gavka': 'Vrsta morske ptice plovke sa obala severnih mora, iz porodice alcidae (zool.).',
 'gavranić': 'Umanjenica i nežni oblik od gavran; mladunče gavrana.',
 'gavun': 'Rod morskih riba iz porodice argentinidae; i jestiva morska riba iz tog roda (zool., ital.).',
 'gazelin': 'Koji pripada gazeli; koji je kao u gazele (gazelin hod).',
 'gaćan': 'Vrsta pitomog goluba čije su noge obrasle perjem; i petao čije su noge obrasle perjem; i onaj koji nosi upadljivo široke gaće.',
 'gegavac': 'Onaj koji se ljulja pri hodu.',
 'generalat': 'Oblast pod komandom jednog generala; uprava, nadleštvo te oblasti.',
 'geodet': 'Onaj koji se bavi geodezijom.',
 'geohemičar': 'Onaj koji se bavi geohemijom.',
 'geometričar': 'Onaj koji se bavi geometrijom.',
 'gerla': 'Privlačna mlađa ženska osoba, devojka (engl., žarg.).',
 'germanizirati': 'Izvršiti germanizaciju, ponemčiti, ponemčavati; (germanizirati se) ponemčiti se, ponemčavati se.',
 'germanka': 'Pripadnica germanske etničke grupe; Nemica.',
 'gestapovski': 'Koji se odnosi na gestapo i gestapovce (gestapovski oficir, metoda).',
 'gibljivost': 'Osobina onoga što je gibljivo, pokretljivost, gipkost (gibljivost tela).',
 'gipsan': 'Koji je načinjen od gipsa, u kome ima gipsa; uopšte koji se odnosi na gips (gipsani zavoj, figura; gipsani radovi).',
 'gipsoteka': 'Muzej ili odeljenje muzeja u kome su izloženi vajarski radovi izliveni u gipsu; zbirka takvih radova (grč.).',
 'glagoljaštvo': 'Vršenje katoličkih crkvenih obreda na staroslovenskom jeziku po knjigama pisanim glagoljicom; srednjovekovni pokret koji se zalagao i borio za to bogosluženje.',
 'glavarica': 'Žena glavar, starešina; i glavareva žena.',
 'glavatica': 'Vrsta velike pastrmke (zool.); i vrsta glavičaste salate (bot.); i igla s glavom, čioda.',
 'glavetina': 'Uvećanica i pežorativ od glava.',
 'glavočić': 'Umanjenica od glavoč.',
 'glačaonica': 'Odeljenje ili radionica u kojoj se nešto glača.',
 'gledateljstvo': 'Publika koja prisustvuje nekoj priredbi, predstavi; gledaoci.',
 'gležnjak': '(Obično u množini) omotač koji se nosi oko gležnjeva kao deo vojničke odeće; gumirana navlaka za gležanj kao deo fudbalske opreme (sport).',
 'gležnjača': 'Skočna, gležnja kost (anat.); i (obično u množini) deo skijaške opreme koji se navlači na gležanj povrh cipela; i dokolenica.',
 'glinac': 'Stena nastala očvršćivanjem gline (geol.).',
 'glinast': 'Koji ima u sebi gline, glinovit (glinasta zemlja).',
 'glinenac': '(U množini) minerali iz grupe silikata koji sačinjavaju 60% litosfere, silikati aluminijuma, natrijuma, kalcijuma i kalijuma, čijim raspadanjem nastaje glina; (u jednini) takav mineral (min.).',
 'gliptoteka': 'Zbirka vajarskih radova; muzej skulptura (grč.).',
 'glistina': 'Uvećanica i pežorativ od glista.',
 'gljivar': 'Onaj koji bere i prodaje gljive; i dobar poznavalac gljiva, ekspert za gljive.',
 'gljivarstvo': 'Gajenje gljiva, sakupljanje gljiva i trgovina njima; i nauka koja se bavi proučavanjem gljiva.',
 'globar': 'Onaj koji naplaćuje, uzima globu; i otimač, pljačkaš, nasilnik, ugnjetač.',
 'globulin': 'Prosta belančevina (obično u množini; hem.).',
 'glomaznost': 'Osobina onoga koji je glomazan, onoga što je glomazno; trapavost.',
 'glutamin': 'Amid jedne aminokiseline, važan organski sastojak biljnog i životinjskog tkiva (hem.).',
 'glušiti': 'Prigušivati (zvuk).',
 'gnezdište': 'Mesto gde se prave gnezda.',
 'gnjecavost': 'Stanje i osobina onoga što je gnjecavo; mekoća (gnjecavost hleba, gline).',
 'gnjidav': 'Koji ima gnjida, pun gnjida; preneseno: gadan, odvratan (gnjidava kosa; gnjidav život).',
 'godinica': 'Nežni oblik od godina; u želji „koliko ti žica, toliko godinica" — onome ko je obukao novo odelo, sa željom da ga dugo nosi.',
 'golemost': 'Osobina onoga koji je golem, onoga što je golemo; ogromnost.',
 'golgeterski': 'Koji se odnosi na golgotere.',
 'golišavac': 'Onaj koji je golišav, nedovoljno odeven (obično o detetu); preneseno: golja, golać, puki siromah; i goluždravo pišče, goluždravac.',
 'golišavost': 'Stanje i osobina onoga koji je golišav, onoga što je golišavo.',
 'golmanski': 'Koji se odnosi na golmana (golmanski prostor).',
 'golobradost': 'Stanje i osobina onoga koji je golobrad; ćosavost.',
 'goluždravac': 'Goluždravo pišče, goluždravi ptić; golišavo muško dete; preneseno pežorativno: nezreo, nedorastao, neiskusan mladić, žutokljunac, balavac.',
 'gomora': 'U izrazu „sodoma i gomora" — preneseno: leglo razvrata, nemorala; strahota, užas (prema imenima dva biblijska grada na Mrtvom moru, uništena zbog razvrata svojih žitelja).',
 'gorina': 'Uvećanica i pežorativ od gora.',
 'gorivost': 'Osobina, svojstvo onoga što je gorivo, što može da gori; zapaljivost, sagorljivost.',
 'gosparski': 'Koji se odnosi na gospare, koji pripada gosparima.',
 'gospodarić': 'Umanjenica od gospodar.',
 'gospodarstvenik': 'Stručnjak koji se bavi gospodarstvom, privredom; privrednik, ekonomist.',
 'gostionički': 'Koji se odnosi na gostionicu.',
 'gotovanstvo': 'Gotovanski način života, život na račun drugoga; nerad, lenčarenje, besposličarenje.',
 'grabik': 'Grabova šuma.',
 'gradištanac': 'Vrsta belog pasulja, po mestu Gradištu (agr.).',
 'graduirati': '(Po)deliti na grade, stepene i obeležiti, obeležavati ih (graduirati staklenu meru).',
 'grafem': 'Pismeni znak, slovo koje odgovara određenom glasu, fonemi (lingv., grč.).',
 'grandoman': 'Onaj koji pati od grandomanije.',
 'granularan': 'Koji je zrnate strukture, zrnast.',
 'granulirati': 'Pretvoriti, pretvarati neku masu, materiju u zrna.',
 'grašar': 'Rod zeljastih i grmolikih biljaka (bot.).',
 'grbavost': 'Osobina i stanje onoga koji je grbav, onoga što je grbavo; pogrbljenost, iskrivljenost, neravnost.',
 'grbovnik': 'Zbirka, pregled grbova.',
 'grebenić': 'Umanjenica od greben.',
 'grimizan': 'Koji je od grimiza (grimizna odeća, zavesa); i koji je boje grimiza, jarkocrven, purpuran (grimizna ruža, rumenilo, boja).',
 'grkokatolik': 'Pripadnik hrišćanske crkve istočnog obreda koji priznaje papu za vrhovnog poglavara; unijat.',
 'grkokatolički': 'Koji se odnosi na grkokatolike; unijatski.',
 'grlatost': 'Osobina onoga koji je grlat, onoga što je grlato.',
 'grličić': 'Grličin ptić, mladunče grlice.',
 'grmača': 'Vrsta jestive gljive mrke boje, koja raste u žbunju; i jestiva gljiva lisičarka (bot.).',
 'grmaš': 'Vrsta lišaja granastog talusa (bot.).',
 'grmić': 'Umanjenica od grm.',
 'grobarski': 'Koji se odnosi na grobare.',
 'grobina': 'Uvećanica i pežorativ od grob.',
 'grotesknost': 'Osobina onoga što je groteskno.',
 'grozničina': 'Uvećanica i pežorativ od groznica.',
 'grošić': 'Umanjenica i nežni oblik od groš; i sitan kovan novac uopšte, para.',
 'grudica': 'Umanjenica od gruda.',
 'grudičav': 'Pun grudica.',
 'grund': 'Osnovna boja, osnovni premaz preko kojeg se nanose druge boje (nem.).',
 'grupaški': 'Koji se odnosi na grupaše, frakcionaški (grupaška borba, delatnost).',
 'gubavost': 'Stanje bolesnika obolelog od gube.',
 'gudeti': 'Svirati na gudačkom instrumentu prevlačeći gudalom preko žica (gudeti uz gusle); i proizvoditi zvuke (o gudačkim instrumentima); preneseno: pevati, pevušiti izgovarajući reči kao kad se peva uz gusle.',
 'gumar': 'Radnik koji radi na izradi gume, proizvoda od gume ili na gumiranju.',
 'gumast': 'Koji je sličan gumi, žilav; koji sadrži gumu (gumasta knedla, sir; gumasta smola).',
 'gumilastika': 'Elastična, tanka guma koja se utkiva u tkaninu; tkanina protkana gumenim vlaknima.',
 'gumirati': 'Prevući, prevlačiti ili protkati, protkivati, impregnirati gumom (gumirano platno, odelo, točkovi, traka).',
 'gurmanstvo': 'Svojstvo onoga koji je gurman.',
 'guseničav': 'Pun gusenica.',
 'guskica': 'Umanjenica i nežni oblik od guska; i glupa mlada ženska osoba.',
 'gustin': 'Skrobno brašno koje se upotrebljava za gušnjavanje poslastica.',
 'guvernadur': 'Zastupnik mletačke vlasti u doba protektorata Mletačke republike nad Crnom Gorom; kasnije opštecrnogorski starešina, najznačajnija ličnost posle vladike i mitropolita, glavar (ist., ital.).',
 'guvernadurstvo': 'Zvanje i čast guvernadura; vladavina, vlast guvernadura (ist.).',
 'guvernerski': 'Koji se odnosi na guvernere.',
 'guć': 'Uzvik za vabljenje svinja, obično ponovljeno.',
 'guštak': 'Gusta šuma, čestar, gustiš.',
 'gušteračin': 'Koji se odnosi na gušteraču, koji pripada gušterači (gušteračin sok).',
 'guščarica': 'Ona koja čuva ili gaji guske; i (u množini, zool.) red vodenih ptica s kožicom za plivanje između prednjih prstiju (patke, guske, labudovi).',
 'guščarnik': 'Živinarnik za guske, gušinjak.',
 'guščetina': 'Uvećanica i pežorativ od guska; i guščije meso.',
 'gužvica': 'Umanjenica od gužva.',
 'gvaš': 'Vrsta akvarela, tehnika slikanja gustim namazom naročitih vodenih boja kod koje se svetlosno nijansiranje postiže mešanjem pigmenta s belom bojom; i slika izrađena takvom tehnikom (slik., fr.).',
 'gvelf': 'Pristalica pape i vladajuće kuće gvelfa u srednjovekovnoj Italiji (ist., ital.).',
 'habit': 'Odeća katoličkih sveštenika, redovnička odeća (ital.).',
 'halabučiti': 'Dizati halabuku, galamiti, larmati, vikati.',
 'halucinantnost': 'Osobina onoga što je halucinantno.',
 'hamada': 'Pusta krečnjačka visoravan bez peska; kamenita, krečnjačka pustinja Sahare (ar.).',
 'hanumica': 'Umanjenica i nežni oblik od hanuma.',
 'hap': 'Uzvik: razgovorno za podražavanje naglog hvatanja; i za podražavanje žucanja (onom.).',
 'hasna': 'Korist: od toga je slaba hasna (tur.).',
 'hatib': 'Islamski veroučitelj i propovednik, imam (tur.).',
 'haubičar': 'Artiljerac, topđija koji opslužuje haubicu.',
 'hedonistički': 'Koji se odnosi na hedonizam i hedoniste, svojstven hedonistima (hedonističko shvatanje, učenje).',
 'hegemonizam': 'Težnja za hegemonijom; sprovođenje hegemonije.',
 'heksagonalan': 'Šestougaon (grč.).',
 'heksagram': 'Šestokraka (Davidova) zvezda, simbol jevrejstva (grč.).',
 'helenizirati': 'Nametnuti, nametati nekome helenski jezik, kulturu, običaje i dr., grčizirati; (helenizirati se) primiti, primati helenske osobine, jezik i kulturu.',
 'heliocentričan': 'Kome je sunce u središtu; heliocentrični sistem — Kopernikova teorija po kojoj je sunce u središtu sveta a oko njega se kreću sve planete (astr.).',
 'heliotropizam': 'Svojstvo biljaka da se okreću prema sunčevom svetlu, fototropizam.',
 'helot': 'Rob zemljoradnik u staroj Sparti (ist., grč.).',
 'hematin': 'Krvna boja, hemijski slična hlorofilu, koja nastaje hidrolizom hemoglobina (med., grč.).',
 'hematit': 'Mineral, najvažnija ruda gvožđa, oksid gvožđa crvenkaste boje (min., grč.).',
 'hemogram': 'Krvna slika dobijena laboratorijskom analizom, prikaz stanja krvi u svrhu dijagnoze — broj eritrocita, leukocita, količina hemoglobina i dr. (med.).',
 'hemoliza': 'Raspadanje crvenih krvnih zrnaca (med.).',
 'hemostatik': '(Obično u množini) sredstvo za zaustavljanje krvarenja (med.).',
 'hendikepirati': 'Dovesti, dovoditi nekoga u nepovoljan položaj, nauditi, stvoriti, stvarati smetnje nekome (hendikepiran u ostvarenju svoje uloge).',
 'heraldičar': 'Naučnik koji se bavi heraldikom.',
 'herceginja': 'Žena hercega, vojvotkinja; i hercegova žena (ist.).',
 'hereditarno': 'Nasledno (hereditarno opterećen).',
 'heretičan': 'Koji sadrži ili pokazuje herezu, svojstven hereticima, heretički (heretično učenje).',
 'hermafroditizam': 'Pojava oba pola kod nekog bića, dvopolnost; postojanje ženskih i muških žlezda u organizmu jedne iste jedinke.',
 'hermeneutika': 'Nauka o tumačenju tekstova — biblijskih, naučnih, istorijskih, književnih i dr. (grč.).',
 'hermetik': 'Pristalica, sledbenik hermetizma; pesnik koji peva, stvara u duhu hermetizma.',
 'hermetizam': 'Pravac u poeziji između dva svetska rata, koji se razvio iz simbolizma, čije su glavne odlike lirično, višeznačno, tajanstveno izražavanje i isticanje emotivne vrednosti reči (knjiž.).',
 'heruvika': 'Crkvena pesma u pravoslavnom bogosluženju koja se peva pri iznošenju svetih darova.',
 'hes': 'Muz. hromatski sniženi ton „ha".',
 'heterogenost': 'Osobina onoga što je heterogeno, raznorodnost, raznovrsnost (heterogenost sastava).',
 'heteromorfan': 'Koji je različitog oblika, drukčiji po obliku (grč.).',
 'heteromorfizam': 'Javljanje neke materije u više oblika, naročito ugljenika (grč.).',
 'hibernirati': 'Zamrznuti, zamrzavati, zalediti, zaleđivati.',
 'hidrauličar': 'Inženjer hidraulike.',
 'hidrid': '(Obično u množini) jedinjenje nekog elementa s vodonikom (hem.).',
 'hidrirati': 'Izvršiti spajanje nezasićenih organskih jedinjenja s vodonikom pomoću katalizatora (hem.).',
 'hidrobus': 'Manji motorni putnički brod za krstarenje po lukama, rekama i kanalima.',
 'hidrodrom': 'Uzletište i sletište hidroaviona (grč.).',
 'hidroenergetika': 'Nauka o iskorišćavanju vodene energije.',
 'hidrofit': 'Biljka koja živi u vodi, delimično ili potpuno; vodena biljka (bot.).',
 'hidrogenerator': 'Električni generator koji pokreće vodena turbina.',
 'hidrogliser': 'Vrsta lakog i vrlo brzog glisera.',
 'hidrograf': 'Stručnjak za hidrografiju.',
 'hidromehaničar': 'Stručnjak za hidromehaniku.',
 'hidrometar': 'Sprava za merenje brzine proticanja tečnosti i gasova (fiz., grč.).',
 'hidronim': 'Ime neke vodene površine — reke, jezera, mora, okeana (lingv., grč.).',
 'hidrostatika': 'Deo hidromehanike koji proučava mirovanje tečnosti i uronjenih tela (grč.).',
 'hidrozoa': '(U množini) klasa dupljara u koju spadaju polipi i meduze; (u jednini) dupljar iz te klase (zool., grč.).',
 'higrograf': 'Instrument za beleženje promena vlažnosti vazduha (grč.).',
 'higrometar': 'Sprava za merenje relativne vlažnosti vazduha, vlažomer (grč.).',
 'higrostat': 'Uređaj za održavanje stalne vlažnosti vazduha u zatvorenim prostorijama.',
 'hihotati': '(Hihotati se) glasno, grohotom se smejati, kikotati se.',
 'himba': 'Licemerje, hipokrizija.',
 'himben': 'Licemeran, dvoličan.',
 'hiperaciditet': 'Prekomerna količina sone kiseline u želudačnom soku.',
 'hiperbolika': 'Preuveličavanje, preterivanje.',
 'hipermangan': 'Tamnoljubičasti kristali kalijum-permanganata, koji se rastvoreni u vodi koriste kao dezinfekciono sredstvo (hem.).',
 'hiperproduktivan': 'Koji preterano, mnogo proizvodi.',
 'hiperproduktivnost': 'Osobina onoga koji je hiperproduktivan.',
 'hiperrealizam': 'Umetnički, obično slikarski pravac koji teži savršeno vernom prikazivanju predmeta, pojava (um.).',
 'hipersenzibilan': 'Preterano osetljiv, preosetljiv.',
 'hipersenzibilnost': 'Osobina onoga koji je hipersenzibilan, preosetljivost.',
 'hipertoničan': 'Koji boluje od hipertonije.',
 'hipnotizam': 'Veština hipnotisanja; pojave u vezi sa hipnozom.',
 'hipnotizerski': 'Na hipnotizerski način, kao hipnotizer (hipnotizerski uspavati).',
 'hipohondričan': 'Koji pati od hipohondrije.',
 'hipotetičnost': 'Osobina onoga što je hipotetično, zasnovanost na hipotezi, verovatnoća (hipotetičnost suda).',
 'hipotoničan': 'Koji ima snižen krvni pritisak.',
 'hipsometar': 'Sprava za merenje nadmorske visine, vrsta barometra (grč.).',
 'hiromant': 'Onaj koji se bavi hiromantijom.',
 'hispanistika': 'Nauka o španskom jeziku i književnosti pisanoj na tom jeziku (lingv., lat.).',
 'hispanizam': 'Osobenost španskog jezika; španski jezički izraz u nekom jeziku (lingv., lat.).',
 'histerizirati': 'Učiniti histeričnim, izaz(i)vati histeriju kod nekoga (histerizirati mase).',
 'histeričnost': 'Osobina i stanje onoga koji je histeričan, onoga što je histerično.',
 'hitin': 'Organska materija, polisaharid sličan celulozi, koji daje čvrstinu spoljnom omotaču (oklopu) zglavkara i nalazi se u ćelijskoj opni gljiva (grč.).',
 'hitlerovski': 'Koji je u duhu hitlerizma, nacizma, nacistički (hitlerovska politika).',
 'hladetina': 'Ohlađeni želatinasti sok od iskuvanih kostiju i mesa, pihtije (kuv.).',
 'hladetinast': 'Koji je kao hladetina, pihtijast, drhtav (hladetinasta masa).',
 'hladionički': 'Koji se odnosi na hladionike i na hladionice (hladionički uređaj).',
 'hlačice': 'Umanjenica od hlače (množina).',
 'hmeljar': 'Proizvođač, uzgajivač hmelja; berač hmelja.',
 'hmeljara': 'Ostava, magacin za smeštaj hmelja.',
 'hmeljarstvo': 'Proizvodnja, gajenje hmelja (kao privredna grana).',
 'hmeljište': 'Zemljište, njiva zasađena hmeljom, odnosno na kojoj se gajio hmelj.',
 'hobistički': 'Koji se odnosi na hobiste.',
 'hodočasnica': 'Žena koja ide na hodočašće.',
 'holesterin': 'Složena hemijska materija, jednovalentni alkohol u mastima čija povišena količina u krvi dovodi do arterioskleroze (hem.).',
 'holizam': 'Učenje da organizam kao celina usmerava fizičke i hemijske procese u živim bićima (biol.); psih. načelo da se pojedinačne psihičke pojave moraju posmatrati u sklopu psihičke celine (grč.).',
 'homerski': 'Koji je u stilu Homera, kao kod Homera, starogrčkog pesnika kome se pripisuju Ilijada i Odiseja (homerski stil, stih); i jako veliki, ogroman (homerska galama).',
 'homiletika': 'Pravila za sastavljanje crkvenih propovedi (grč.).',
 'homoniman': 'Koji je istog glasovnog sastava a različitog značenja (homonimni niz).',
 'horizontalnost': 'Horizontalan položaj.',
 'hospitant': 'Onaj koji hospituje, gost slušalac na predavanjima (lat.).',
 'hrakotina': 'Ispljuvak, sluz izbačena hrakanjem.',
}

C = {
 'eurska': 'verovatno OCR-pokvarena „evrika" (uzvik radosti pri otkriću); oblik „eurska" nije srpska reč',
 'Filipin': 'u Matici samo „Filipini"; oblik „Filipin" nije potvrđen (verovatno isečak pri uvoženju)',
 'fićure': 'glosa fragmentarna (deo glosa o stilskim figurama); oblik nejasan',
 'fukati': 'vulgarno (vulg. polno opštiti); rečnik takve reči ne vodi',
 'gaka': 'glosa OCR-nečitka (zoološki naziv); značenje nesigurno',
 'gasta': 'glosa fragmentarna; značenje nejasno',
 'govnar': 'pogrdna reč na blok-listi generatora; rečnik takve reči ne vodi',
 'guz': 'vulgarno (na blok-listi generatora); rečnik takve reči ne vodi',
 'grafizam': 'glosa odsečena („način slikanja koji se primenjuje u…") — nepotpuna',
 'hanja': 'glosa fragmentarna (deo glosa o dresuri konja); značenje nejasno',
 'haši': 'glosa fragmentarna (deo glosa o jahanju); značenje nejasno',
 'hovana': 'glosa fragmentarna; značenje nejasno',
}
