# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 2311–2640 (pristavljati … sandolina).

DEC = {
 'pristavljati': 'Nesvršeni oblik glagola „pristaviti".',
 'pristupnik': 'Onaj koji je stupio u neku organizaciju.',
 'pristupnina': 'Novac koji se plaća pri stupanju u neku organizaciju.',
 'pritvorenica': 'Žena pritvorenik.',
 'privatnica': 'Žena privatnik.',
 'privetrina': 'Mesto izloženo vetru; pom. strana broda koja je na udaru vetra.',
 'privezanost': 'Stanje onoga koji je uz nešto čvrsto privezan, koji je s nekim ili nečim povezan; i privrženost, odanost, vernost prema kome.',
 'prizdraviti': 'Malo, donekle ozdraviti, ne ozdraviti sasvim.',
 'priznatost': 'Osobina onoga koji je priznat.',
 'prišarafiti': 'Učvrstiti šrafovima, vijkama; zašrafiti.',
 'prišivak': 'Nešto što je naknadno prišiveno, uporedi zakrpa; preneseno: naknadan, nevažan dodatak (njegovo učenje je samo prišivak pravoj nauci); i nadimak (obično pogrdan).',
 'priženiti': 'Oženiti uvodeći u ženinu kuću, učiniti domazetom (priženili su slugu); (priženiti se) ženidbom ući u ženinu kuću, postati domazet.',
 'prljavica': 'Prljava žena.',
 'probavljivost': 'Osobina onoga što je probavljivo.',
 'probitačnost': 'Osobina onoga koji je probitačan, onoga što je probitačno.',
 'problematizovati': 'Postaviti ili uočiti kakvu pojavu kao problem koji treba ispitati; i dovesti u pitanje nešto što se nije smatralo problemom, proglasiti nešto problemom.',
 'problematičnost': 'Osobina onoga što je problematično.',
 'proceniteljski': 'Koji se odnosi na procenitelje.',
 'prodisati': 'Početi disati.',
 'produhoviti': 'Ispuniti duhovnim životom, prožeti duhovnošću (bol ga je produhovila).',
 'produhovljenje': 'Produhovljenost.',
 'produhovljivati': 'Nesvršeni oblik glagola „produhoviti"; uporedi produhovljavati.',
 'produkovati': 'Proizvoditi, stvarati (produkovati skupu robu).',
 'profilaktičan': 'Zaštitni, preventivni (profilaktičan lek, vakcina).',
 'profiterstvo': 'Profiterske osobine, svojstva.',
 'profućkati': 'Lakomisleno, uludo potrošiti, straćati (profućkati novac, mladost).',
 'prognanica': 'Žena prognanik.',
 'prognanički': 'Koji se odnosi na prognanike i na prognanice.',
 'programator': 'Deo na mašini za pranje veša kojim se programira trajanje i način pranja.',
 'proizvodnost': 'Sposobnost, kapacitet proizvodnje; proizvodnja.',
 'prokliziti': 'Klizeći proći; preneseno: neprimetno proći, minuti, proteći (o vremenu).',
 'prokuhati': 'Isto što i prokuvati.',
 'prokuhavati': 'Nesvršeni oblik glagola „prokuhati".',
 'prokuljati': 'Početi kuljati, silovito, snažno prodreti (o tečnosti, dimu, pari i dr.); i krenuti, doći u masi, u velikom broju (iz bioskopa je prokuljala reka ljudi); i iznenada se pojaviti, iskrsnuti.',
 'prolupati': 'Početi proizvoditi šumove koji ukazuju na kvar (o motoru automobila); šaljivo: doživeti psihičku krizu.',
 'promarširati': 'Marširajući proći.',
 'promašenost': 'Stanje onoga što je promašeno.',
 'promašivati': 'Nesvršeni oblik glagola „promašiti".',
 'prominentnost': 'Osobina onoga koji je prominentan i onoga što je prominentno.',
 'promočiti': 'Učiniti sasvim mokrim, vlažnim, natopiti vlagom, prokvasiti (kiša je sasvim promočila zemlju); (promočiti se) postati sasvim mokar, vlažan.',
 'promutiti': 'Promešati, izmešati.',
 'pronalazaštvo': 'Sposobnost pronalaženja; rad, aktivnost pronalazača.',
 'propalost': 'Svojstvo, stanje fizičkog ili duhovnog propadanja.',
 'proparati': 'Rasparati, isparati; raseći, razrezati, poderati, pocepati; i pojaviti se velikim intenzitetom, neočekivano, naglo i nakratko (nebom je proparala munja).',
 'propišati': 'U izrazu „propišati krv" — pretrpeti veliku neugodnost, nevolju; (propišati se) početi mnogo i često pišati, mokriti.',
 'propuhivati': 'Nesvršeni oblik glagola „propuhati".',
 'propustljivost': 'Osobina, stanje onoga što je propustljivo.',
 'proračunatost': 'Svojstvo onoga koji je proračunat, onoga što je proračunato.',
 'proređenost': 'Svojstvo, stanje onoga što je proređeno.',
 'prosenjak': 'Vrsta jestive gljive (bot.); i isto što i prosenica.',
 'prosperitetan': 'Koji se povoljno razvija, napredan, uspešan (prosperitetan posao).',
 'prostatitis': 'Zapaljenje prostate (med.).',
 'prosuditelj': 'Onaj koji prosuđuje, onaj koji donosi kakav sud, prosuđivač.',
 'prosvetarski': 'Koji se odnosi na prosvetare (prosvetarski rad).',
 'prosvetiteljstvo': 'Prosvetiteljski rad, prosvećivanje; ist. filozofski, kulturni i društveni pokret u Evropi u XVIII veku koji se temelji na ideji zdravog razuma i narodnog obrazovanja, prosvećenost.',
 'protek': 'Kraj, isticanje određenog vremenskog perioda.',
 'protekcionizam': 'Sistem mera ekonomske politike — uvođenje posebnih uvoznih carina, smanjenje izvoznih dažbina i dr. za određenu robu — usmerenih na zaštitu kakve industrijske ili poljoprivredne proizvodnje (ekon.).',
 'protonotar': 'Glavni notar, beležnik; ist. u feudalnoj Hrvatskoj, dostojanstvenik koji je čuvao državni pečat (grč.-lat.).',
 'protozoa': '(Obično u množini) najniži jednoćelijski životinjski organizam (zool.).',
 'prouzrokovač': 'Onaj koji, ono što prouzrokuje, izaziva nešto.',
 'prouzročavati': 'Nesvršeni oblik glagola „prouzročiti".',
 'prozaičnost': 'Osobina onoga koji je prozaičan, onoga što je prozaično.',
 'pročelnica': 'Ženska osoba pročelnik.',
 'pročešljavati': 'Nesvršeni oblik glagola „pročešljati".',
 'pročistač': 'Uređaj za pročišćavanje (pročistač vazduha).',
 'proširenost': 'Osobina, stanje onoga što je prošireno.',
 'prošvrljati': 'Švrljajući proći, probazati, prošumarati, prolutati (u veče bi prošvrljao oko kuće).',
 'prpošan': 'Samovoljan, prkosan; obestan (prpošan mladić); i koji odražava takve osobine (prpošan pogled).',
 'prpošno': 'Na prpošan način, prkosno, pustopašno.',
 'prskavac': 'Biljka čije čahure pri dodiru prskaju (bot.).',
 'prsobran': 'Nasip, bedem koji štiti od neprijateljske vatre, grudobran.',
 'prudovit': 'Koji ima mnogo prudova, koji obiluje prudovima.',
 'prutina': 'Uvećanica od prut.',
 'prutka': 'Naziv za više vrsta ptica: mala prutka, mrka prutka, pegava prutka (zool.).',
 'prvoligašica': 'Ženski sportski klub (ređe sportiskinja) koji igra u prvoj ligi.',
 'prvoplasiran': 'Koji je osvojio prvo ili neko od najviših mesta na takmičenju (prvoplasirana ekipa).',
 'prštav': 'Koji pršti.',
 'psihologizirati': 'Prikazivati, opisivati psihološke, duševne osobine, stanja (obično ih preterano naglašavajući, ističući).',
 'pucački': 'Koji se odnosi na pucače i pucanje.',
 'puhača': 'Vrsta žabe (zool.).',
 'pulin': 'Mali ovčarski pas.',
 'pulman': 'Vrsta udobnog železničkog vagona (prema imenu izumitelja).',
 'punokrvnost': 'Svojstvo, stanje onoga koji je punokrvan, onoga što je punokrvno.',
 'punomastan': 'Koji sadrži u sebi masne sastojke, iz kojih nije vađena masnoća (punomasni sir, punomasno mleko).',
 'punomoćni': 'Koji ima punomoć (punomoćni zastupnik).',
 'pupavka': 'Vrsta otrovne pečurke (bot.).',
 'purgerica': 'Ženska osoba purger.',
 'puritanizam': 'Protestantsko-reformatorski pokret u Engleskoj u XVI i XVII veku za uklanjanje ostataka katolicizma u anglikanskoj crkvi (ist.); i isto što i purizam.',
 'puritanstvo': 'Purizam, puritanizam.',
 'pustinjaštvo': 'Pustinjački život.',
 'pustopašnost': 'Osobina onoga koji je pustopašan; postupak onoga koji je pustopašan.',
 'putak': 'Nežni oblik od put (stegla mati u naručje sina, putak hvata u brda daleka).',
 'racionalizator': 'Pronalazač načina kojim se proizvodnja racionalizuje.',
 'racionalizatorstvo': 'Težnja za racionalizacijom proizvodnje; racionalizacija.',
 'radikalnost': 'Svojstvo onoga koji je radikalan, onoga što je radikalno; radikalizam.',
 'radionuklid': '(Obično u množini) radioaktivni element (hem.).',
 'radićevac': 'Pristalica ili član Hrvatske seljačke stranke, čiji je šef bio Stjepan Radić (ist.).',
 'radiša': 'Radan, vredan čovek, dobar radnik.',
 'radišnost': 'Osobina onoga koji je radišan, marljivost, vrednoća.',
 'raga': 'Mršav, iznemogao, islužen konj; staro, rđavo kljuse.',
 'rahitičar': 'Onaj koji je bolestan od rahitisa.',
 'rahitičnost': 'Osobina i stanje onoga koji je rahitičan, onoga što je rahitično.',
 'ramenica': 'Gornji deo ruke koji prelazi u rame (anat.).',
 'ramstek': 'Komad, odrezak pečenog goveđeg mesa od stražnjeg dela (kuv., engl.).',
 'ranj': 'Vrsta hrasta, sladun (bot.).',
 'rasadnički': 'Koji se odnosi na rasadnike, koji pripada rasadniku.',
 'rascvat': 'Stanje biljaka (livada, šuma) u punom razvoju cvetanja, cvetnosti (šuma u rascvatu, trešnja u rascvatu); preneseno: pun razvoj, procvat (kulturni rascvat).',
 'rashlađenje': 'Osveženje, rashlada; preneseno: gubitak interesa za nešto, ravnodušnost posle oduševljenja.',
 'raskoliti': 'Raseći u dva dela, rascepiti (raskoliti glavu); (raskoliti se) rascepiti se.',
 'raskuštrati': '(Raskuštrati se) postati kuštrav, raščupati se, razbarušiti se (o kosi).',
 'raskužiti': 'Uništiti uzročnike kuže, zaraznih bolesti i sl.; dezinfikovati.',
 'raskvašenost': 'Osobina, stanje onoga što je raskvašeno.',
 'raslinje': '(Zbirno, množina) biljke, rastinje.',
 'raspadljiv': 'Koji se može raspasti, koji se lako raspada (raspadljiva kora).',
 'raspadljivost': 'Osobina, stanje onoga što je raspadljivo.',
 'raspaljenost': 'Osobina, stanje onoga koji je raspaljen, onoga što je raspaljeno.',
 'raspaljivost': 'Osobina onoga koji je raspaljiv.',
 'raspačavati': 'Nesvršeni oblik glagola „raspačati".',
 'raspevanost': 'Osobina, stanje onoga što je raspevano; raspoloženje za pesmu, veselost.',
 'rasplesati': '(Rasplesati se) predati se plesu, razigrati se (devojke se rasplesale).',
 'rasplodište': 'Mesto gde se nešto rasplođava, leglo (rasplodište vašiju).',
 'raspoloženost': 'Osobina, stanje onoga koji je dobro raspoložen; veselost.',
 'raspoređenost': 'Stanje onoga što je raspoređeno, uklopljeno u raspored (raspoređenost ritmova).',
 'raspravni': 'Koji se odnosi na raspravu (raspravno načelo).',
 'rasprostranjenje': 'Rasprostranjenost, raširenost.',
 'rastaliti': 'Zarevanjem pretvoriti u tečno stanje (rastaliti gvožđe); (rastaliti se) preći nakon izlaganja toploti u tečno stanje (o nekom čvrstom telu).',
 'rastanjiti': 'Pritiskivanjem ili rastezanjem učiniti tanjim (rastanjiti testo); i razrediti, razblažiti (rastanjiti kafu); (rastanjiti se) postati tanji, razrediti se.',
 'rastavljiv': 'Koji se može rastaviti na delove, raščlanljiv.',
 'rasterećenost': 'Stanje onoga koji je rasterećen, onoga što je rasterećeno.',
 'rastrežnjenje': 'Povratak u trezno (trezveno) stanje (rastrežnjenje posle pijanke, od zanosa).',
 'rastrganost': 'Osobina onoga što je rastrgano, iscepkanost.',
 'rastrošan': 'Koji rasipnički troši, rasipan (rastrošan čovek).',
 'rastrošno': 'Rasipnički, rasipno (rastrošno živeti).',
 'rastrošnost': 'Osobina onoga koji je rastrošan, rasipništvo.',
 'rastvorljivost': 'Osobina onoga što je rastvorljivo, sposobnost rastvaranja.',
 'ravnokrilac': '(U množini) red insekata ravnog pokrilja, pravokrilci; (u jednini) takav insekt (zool.).',
 'raz': 'Prefiks u složenim glagolima i njihovim izvedenicama; označava deljenje, odvajanje, međusobno udaljavanje i sl.',
 'razbaštinjenje': 'Lišenje baštine, naslednih prava, oduzimanje baštine.',
 'razbesniti': 'Izazvati kod nekoga bes, srdžbu, učiniti besnim, razjariti, ražestiti (razbesniti psa, učitelja).',
 'razdrobljenost': 'Stanje i osobina onoga što je razdrobljeno, izmrvljenost; usitnjenost, rasparčanost (feudalna razdrobljenost).',
 'razdruženje': 'Raspad neke zajednice, razlaz; deoba, podela (razdruženje poslovnih partnera).',
 'razdružiti': 'Izazvati raskid, razdor među združenima; raskinuti, rasturiti neku vezu.',
 'razduženje': 'Vraćanje duga uz oslobođenje od dužničke obaveze, prestanak dužničkog odnosa; i oslobođenje od određene dužnosti, zadatka, obaveze.',
 'razglasni': 'Koji služi za razglas, za razglašavanje, objavljivanje (razglasna stanica, uređaj).',
 'razglašenost': 'Stanje i osobina onoga što je razglašeno, onoga koji je razglašen; čuvenje; slava.',
 'razgolićenje': 'Obnaženje; obnaženost, nagost.',
 'razgovetnost': 'Osobina ili stanje onoga što je razgovetno, jasnoća, razumljivost.',
 'razgovorljivost': 'Osobina onoga koji je razgovorljiv, pričljivost, govorljivost.',
 'razgranatost': 'Stanje i osobina onoga što je razgranato, razvijenost (razgranatost drveta, krošnje; poslova).',
 'razigravanje': 'Glagolska imenica od razigravati (se); sport. isto što i plej-of.',
 'razlagač': 'Ono što izaziva razlaganje, rastvarač (razlagač organskih materija).',
 'razlučivost': 'Osobina onoga što je razlučivo.',
 'razmahati': 'Pokrenuti snažno, živo, na sve strane; početi snažno mahati nečim (razmahati ruke, zastavom); i učiniti da nešto uzme maha, podstaći (razmahati razvoj, privredu, rat).',
 'razmatrač': 'Onaj koji nešto razmatra, proučava, analizira.',
 'razmetan': 'Koji neumereno, nemilice troši, rasipan.',
 'razmetnik': 'Onaj koji je razmetan, rasipnik.',
 'razmetno': 'Na razmetan način, rasipnički.',
 'razmetnost': 'Osobina onoga koji je razmetan, rasipnost.',
 'razminirati': 'Očistiti, osloboditi od mina, minirani teren (razminirati polje).',
 'razmrviti': 'Samleti, razdrobiti, smrskati (razmrviti orahe); i uništiti, satrti (razmrviti snagu).',
 'raznježiti': 'Ispuniti, obuzeti osećanjem nežnosti; ganuti (raznježiti nečiju dušu).',
 'raznosačica': 'Žena raznosač.',
 'razobličavati': 'Nesvršeni oblik glagola „razobličiti".',
 'razorenje': 'Razor, uništenje (razorenje tvrđave).',
 'razrađenost': 'Osobina onoga što je razrađeno, detaljna obrada.',
 'razrednica': 'Nastavnica koja je razrednik, razredni starešina (šk.).',
 'razrednik': 'Nastavnik koji je zadužen da brine o jednom razredu, razredni starešina (šk.).',
 'razredništvo': 'Dužnost razrednika.',
 'razrezivati': 'Nesvršeni oblik glagola „razrezati".',
 'razrešiv': 'Koji se može razrešiti.',
 'razvaljati': 'Valjajući razvući, istanjiti (razvaljati testo).',
 'razvedenica': 'Žena koja se razvela od muža, raspuštenica.',
 'razvedenost': 'Stanje onoga što je razvedeno; proširenost; razuđenost, razgranatost (razvedenost obale); i stanje onoga koji je razveden.',
 'razvlašćivati': 'Nesvršeni oblik glagola „razvlastiti".',
 'razvučenost': 'Osobina i stanje onoga što je razvučeno (razvučenost priče, kompozicije; govora).',
 'rašljast': 'Koji je u obliku rašalja, rakljast (rašljast štap).',
 'rašomon': 'Zapleten, nejasan događaj o kome se različito priča; protivrečne interpretacije jednog istog događaja (prema japanskom filmu „Rašomon" A. Kurosawe).',
 'raštimati': 'Olabaviti žice na muzičkom instrumentu, učiniti ga nepodobnim za harmonično sviranje (nem.).',
 'raščupanost': 'Stanje, osobina onoga koji je raščupan, onoga što je raščupano.',
 'ražariti': 'Podstaći, raspaliti (vatru, žar); i učiniti vrelim, jako zagrejati, usijati (ražariti gvožđe); (ražariti se) jako se zagrejati, raspaliti se, usijati se.',
 'reakcionarstvo': 'Reakcionarnost.',
 'reaktivnost': 'Osobina, stanje onoga što je reaktivno.',
 'reanimirati': 'Vratiti, vraćati u život, oživeti, oživljavati (reanimirati utopljenika; preneseno: društveni poredak).',
 'rebalansirati': 'Ponovo dovesti, dovoditi u ravnotežu, uravnoteživati (rebalansirati planove).',
 'rebreni': 'Koji se odnosi na rebra, koji pripada rebrima (rebrena hrskavica).',
 'rebrenica': 'Krilo na prozoru nalik na rebra, žaluzina (obično u množini).',
 'recidivizam': 'Pojava koja ima karakter recidiva; ponavljanje kriminalnog dela od istog počinioca.',
 'redić': 'Umanjenica i nežni oblik od red.',
 'redovitost': 'Osobina, stanje onoga što je redovito.',
 'redovništvo': 'Redovnička služba; redovnički stalež, redovnici.',
 'reduktivan': 'Koji se može redukovati.',
 'reduktor': 'Uređaj koji smanjuje brzinu obrtanja pomoću prenosnika (tehn.); hem. sredstvo za oslobađanje metala od kiseonika, sumpora, soli i sl.',
 'refleksan': 'Koji se odnosi na svetlosne i sl. reflekse, refleksiju (refleksna svetlost, staklo); i koji se odnosi na fiziološke reflekse, koji se događa kao refleks, nehotičan, nesvestan, spontan (refleksno grčenje, reakcija, kretnja).',
 'refleksivnost': 'Osobina onoga što je refleksivno, misaonost (refleksivnost u umetnosti).',
 'reformizam': 'Struja u marksističkom i radničkom pokretu koja nastoji da ostvari socijalne promene reformama, bez socijalističke revolucije i diktature proletarijata (lat.).',
 'regentstvo': 'Vladavina regenta; kraljevsko namesništvo.',
 'registratura': 'Kancelarija gde se nalazi registar i čuvaju akta, registratura.',
 'regresirati': 'Vratiti se, vraćati se na niži stupanj razvitka, nazadovati; i da(va)ti naknadu, odštetu, pomoć (regresirati poljoprivredu); (regresirati se) dobijati naknadu, odštetu, pomoć.',
 'regresivnost': 'Osobina, stanje onoga koji je regresivan, onoga što je regresivno.',
 'regularnost': 'Osobina onoga što je regularno, redovnost, pravilnost.',
 'regulativan': 'Koji se odnosi na regulativ, usmeravajući (regulativan princip).',
 'rekognoscirati': 'Izvideti, izviđati, osmotriti, osmatrati u vojne, naučne i dr. svrhe (rekognoscirati teren) (voj.); i prizna(va)ti, potvrditi, potvrđivati ispravnost nečega na osnovu prethodnog pregleda i ispitivanja.',
 'rekreativan': 'Koji služi za rekreaciju, odmor, okrepljenje (rekreativna nastava, teren).',
 'rekreirati': 'Okrepiti, okrepljivati, osvežiti, osvežavati; razonoditi, zabaviti; (rekreirati se) odmoriti se, okrepiti se.',
 'rektorstvo': 'Vršenje dužnosti rektora.',
 'remac': 'Novi vojnik, rekrut (voj., žarg.).',
 'remenica': 'Točak mašine preko koje se prebacuje, zateže remen (maš.).',
 'remenčić': 'Umanjenica od remen.',
 'remis': 'Odlaganje roka plaćanja, isplate; i popust pri plaćanju, rabat (lat.).',
 'remorkaža': 'Vuča, tegljenje, vučenje šlepova (fr.).',
 'rendgenogram': 'Rendgenski snimak.',
 'renegatstvo': 'Renegatski postupak, odpadništvo, izdajstvo; i (zbirno) renegati.',
 'rentabilnost': 'Osobina onoga što je rentabilno, unosnost, korisnost; odnos dobiti prema uloženoj vrednosti.',
 'repar': 'Prodavac repe ili repnog semena; „noćni repar" — vrsta insekta, repina sovica (zool.).',
 'repin': 'Koji pripada repi, koji se odnosi na repu (repin list, koren).',
 'reponja': 'Repata životinja, životinja koja ima izrazito dug rep (vuk, pas); preneseno pežorativno o čoveku; i (narodno) đavo, nečastivi.',
 'reprezentativnost': 'Osobina onoga što je reprezentativno.',
 'reprizirati': 'Ponovo izvesti, izvoditi, da(va)ti reprizu nečega (reprizirati televizijsku seriju).',
 'republikanizam': 'Političko opredeljenje za republiku.',
 'resantiman': 'Bolno sećanje koje pobuđuje želju za osvetom, zlopamćenje, osvetoljubivost (fr.).',
 'resoperka': '(U množini) podred devonskih riba koštljoriba, danas sačuvan samo jedan oblik; (u jednini) takva riba (zool.).',
 'respektabilnost': 'Osobina, svojstvo onoga što je respektabilno (respektabilnost mlađeg prema starijem).',
 'retina': 'Mrežnica, mrežnjača oka (anat., lat.).',
 'retoričar': 'Onaj koji se bavi retorikom.',
 'retrospektivan': 'Koji se odnosi na retrospektivu, retrospekciju, unazadni (retrospektivno pričanje, pogled na likovno stvaralaštvo, izložba).',
 'retušer': 'Ispravljač, doderivač (obično fotografija i natpisa).',
 'reumatičnost': 'Stanje onoga što je reumatično.',
 'revanšistički': 'Koji teži za revanšom, osvetoljubiv (revanšistički članak).',
 'reverenda': 'Dugačka sveštenička haljina katoličkih i evangelističkih sveštenika, mantija (lat.).',
 'revitalizovati': 'Oživeti, oživljavati, obnoviti, obnavljati (revitalizovati ceo organizam; preneseno: centar grada).',
 'revizionizam': 'Težnja, nastojanje da se nešto preispita i revidira, izmeni, promeni; i zahtev za promenom nekog ugovora, naročito granica.',
 'revolucionarstvo': 'Revolucionarno raspoloženje, revolucionarni duh; revolucionarnost.',
 'rezigniranost': 'Stanje onoga koji je reziniran, pomirenost sa sudbinom, ravnodušnost.',
 'rezignirati': '(Po)miriti se sa sudbinom, pred(av)ati se sudbini; povući se, povlačiti se sa posla, sa službe.',
 'rezistentan': 'Koji daje, pruža otpor, odporan, izdržljiv, postojan.',
 'rezistentnost': 'Osobina, stanje onoga koji je rezistentan, onoga što je rezistentno; otpornost (rezistentnost vojnika, kabine).',
 'reznik': 'Jednogodišnja loza orezana na više okaca.',
 'rezuckati': 'Umanjeno: rezati.',
 'rezultatski': 'Koji se odnosi na rezultat, rezultate.',
 'rešetar': 'Majstor koji pravi rešeta; prodavac rešeta; preneseno: onaj koji detaljno istražuje greške, krivice; onaj koji svakome i svemu nalazi zamerke, cepidlaka.',
 'režnjić': 'Umanjenica od režanj.',
 'ricinusov': 'Koji se odnosi na ricinus, koji potiče od ricinusa (ricinusovo ulje).',
 'rika': 'Prodoran, snažan glas nekih životinja (goveda, lavova); preneseno: snažan, prodoran glas ili zvuk (rika topova, motora).',
 'rilce': 'Umanjenica od rilo.',
 'rilja': 'Radnik koji rilja zemlju.',
 'rimokatolički': 'Katolički (rimokatolička crkva).',
 'rinfuza': 'Roba koja je u rasutom stanju, bez vreće i omota, refuza (lat.).',
 'rinitis': 'Upala sluznice nosa s pojačanim lučenjem sluzi (med., grč.).',
 'riskantnost': 'Rizičnost.',
 'rizičnost': 'Osobina, stanje onoga što je rizično; opasnost.',
 'robica': 'Umanjenica i nežni oblik od roba.',
 'rodnica': 'Spoljni deo ženskog polnog organa (anat., lat.).',
 'rodoljuban': 'Isto što i rodoljubiv.',
 'rodoljupka': 'Žena rodoljub.',
 'rohada': 'Isto što i rokada (šah, šp.).',
 'romantičnost': 'Osobina onoga što je romantično (romantičnost prizora).',
 'romančić': 'Umanjenica i/ili ironično od roman.',
 'rondela': 'Okrugli zasad u vrtu, parku (fr.).',
 'rosište': 'Temperatura na kojoj neka materija prelazi iz parnog u tekuće stanje, temperatura kondenzacije.',
 'rotator': 'Aparat za umnožavanje kopija, ciklostil (lat.).',
 'roška': 'Plod u čauri sa jednom semenkom (bot.).',
 'rožina': 'Uvećanica od rog; i koštano, okoštalo tkivo (nokta, kopita).',
 'rubinov': 'Koji ima svojstva, osobine rubina (crvenilo rubinove boje).',
 'rudariti': 'Raditi u rudniku, biti rudar; preneseno: intenzivno istraživati.',
 'rudast': 'Koji ima meku gustu kosu, dlaku, vunu; kovrdžav, kudrav; i riđ, riđkast.',
 'rudelj': 'Drvo slično javoru i klenu (bot.).',
 'rudež': 'Dlake, brada, kosa; uvojak, pramen (rudež od ćebeta, kose).',
 'rudica': 'Dlačice na vunenoj ili svilenoj tkanini; i obojena vuna, pređa; pređa od finije, mekše tkanine.',
 'rudimentaran': 'Koji je tek u začetku, početni, osnovni, elementaran (rudimentarno stanje); i zaostao u razvitku, zakržljao (rudimentarni organi).',
 'rugalac': 'Onaj koji se ruga, područivač.',
 'rukavina': 'Uvećanica i pežorativ od rukav.',
 'rukica': 'Umanjenica i nežni oblik od ruka, ručica.',
 'rukopolagati': 'Nesvršeni oblik glagola „rukopoložiti".',
 'rukovoditeljica': 'Žena rukovodilac.',
 'runce': 'Umanjenica od runo.',
 'runja': 'Dlaka na životinjama i nekim delovima ljudskog tela (runja na grudima); i dlaka na tkanini (runja na peškiru) — obično u množini.',
 'rupičavost': 'Osobina onoga što je rupičavo, rupičastost.',
 'rusificirati': 'Da(va)ti nečemu ruski karakter.',
 'rustika': 'Vrsta zida od četvrtastog grubo tesanog kamena (arhitektura); i stil, način gradnje, izrade nameštaja i sl. sa elementima seoske izrade (lat.).',
 'ruševnost': 'Stanje onoga što je ruševno, trošnost, ruiniranost.',
 'sablažnjivost': 'Osobina onoga koji je sablažnjiv, onoga što je sablažnjivo (sablažnjivost prizora).',
 'sabljar': 'Onaj koji pravi sablje.',
 'safalada': 'Vrsta kratke, debele, nesušene kobasice (ital.).',
 'saigračica': 'Žena saigrač.',
 'sakralnost': 'Osobina onoga što je sakralno, svetost, posvećenost.',
 'sakristan': 'Crkvenjak, zvonar.',
 'salaški': 'Koji se odnosi na salaše (salaški momak).',
 'salonit': 'Proizvod od azbestnih vlakana i cementa, koji ima široku primenu u građevinarstvu.',
 'salpa': 'Vrsta jestive morske ribe sa žutim prugama na telu (zool.).',
 'salčić': 'Vrsta poslastice, kolač od lisnatog testa premazanog salom (kuv.; najčešće u množini).',
 'samilostan': 'Sažaljiv, saosećajan (samilosna ruka, sestra, pogled).',
 'samoanaliza': 'Analiza samoga sebe, svojih postupaka.',
 'samobitnost': 'Stanje, osobina onoga koji je samobitan (boriti se za svoju samobitnost).',
 'samokažnjavanje': 'Kažnjavanje samoga sebe.',
 'samokritika': 'Kritički stav prema samome sebi, sopstvenom radu, postupcima i sl.; kritikovanje samoga sebe.',
 'samokritičan': 'Koji sam sebe kritikuje, prosuđuje, ocenjuje (umetnici su retko samokritični).',
 'samokritičnost': 'Osobina onoga koji je samokritičan; moć, sposobnost zapažanja, uočavanja sopstvenih nedostataka.',
 'samooplodnja': 'Oplđenje dvopolnih biljaka, samooprašivanje, autoamija (biol.).',
 'samopotvrđivanje': 'Potvrđivanje samoga sebe i svoje vrednosti (samopotvrđivanje čoveka u svim domenima života, na radu).',
 'samoreklama': 'Reklamiranje samoga sebe.',
 'samoupravljač': 'Učesnik u samoupravljanju.',
 'samozaborav': 'Zaboravljanje na sebe i svoje lične interese radi opšteg dobra i ljubavi prema drugima (davati svakome do samozaborava).',
 'samozavaravanje': 'Varanje, zavaravanje samoga sebe, suverisanje sebi onoga što ne odgovara stvarnosti (pribeći samozavaravanju).',
 'samozaštita': 'Zaštita sebe i svojih prava sopstvenim snagama i sredstvima.',
 'sandolina': 'Vrsta uskog i lakog čamca, obično sa jednim sedištem i jednim parom vesala (ital.).',
}

C = {
 'pričepiti': 'glosa OCR-nečitka — nesigurno',
 'prohteti': 'glosa odsečena; nesigurno (bezlični glagol, verovatno „zaželeti se")',
 'Prokuplja': 'oblik grada Prokuplje; Matica ne vodi toponim — vlasnica odlučuje (u rečniku „Prokuplje": grad u Toplici)',
 'Prokupljama': 'oblik grada Prokuplje; Matica ne vodi toponim — vlasnica odlučuje',
 'Prokuplji': 'oblik grada Prokuplje; Matica ne vodi toponim — vlasnica odlučuje',
 'Prokupljom': 'oblik grada Prokuplje; Matica ne vodi toponim — vlasnica odlučuje',
 'Prokuplju': 'oblik grada Prokuplje; Matica ne vodi toponim — vlasnica odlučuje',
 'prokurvati': 'vulgarno (kurva-familija); rečnik takve reči ne vodi',
 'prištav': 'glosa OCR-nečitka; osnova („prištev") nejasna',
 'prištičav': 'glosa OCR-nečitka; osnova („prištev") nejasna',
 'pupaš': 'glagolski oblik; glosa samo uput na nejasnu reč („puditi"?) — nesigurno',
 'puriši': 'glosa fragmentarna; značenje nejasno',
 'ratina': 'glosa nejasna (osnova „rit" višeznačna) — nesigurno',
 'razmazivanje': 'glosa fragmentarna; značenje nejasno',
 'ražina': 'uvećanica; osnovna reč („raž"?) nejasna — nesigurno',
 'ree': 'glosa OCR-nečitka; značenje nejasno',
 'renje': 'glosa fragmentarna; značenje nejasno',
 'renjima': 'glosa fragmentarna; značenje nejasno',
 'reta': 'glosa fragmentarna; osnovna reč nejasna',
 'rice': 'glosa fragmentarna; značenje nejasno',
 'ritina': 'glosa nejasna (osnova „rit" višeznačna) — nesigurno',
 'rumenjak': 'botanička glosa OCR-nečitka (latinica nečitljiva) — nesigurno',
 'runka': 'botanička glosa OCR-nečitka — nesigurno',
 'sadan': 'glosa fragmentarna; značenje nejasno',
}
