# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 1981–2310 (patronaža … prispavati).

DEC = {
 'patronaža': 'Staranje o nekome, obično o bolesnom ili nemoćnom licu (fr.).',
 'patronažni': 'Koji se odnosi na patronažu (patronažna služba, sestra).',
 'paušalac': 'Onaj koji plaća paušalni iznos (obično o poreskom obvezniku).',
 'paziteljica': 'Ona koja pazi na nešto, na nekoga, koja pazeći čuva nešto, nekoga, brine se o nečemu, nekome (kućna paziteljica, paziteljica dece).',
 'pedesetorica': 'Pedeset muških osoba.',
 'pelcer': 'Mladica koja služi za presađivanje, pre svega cveća (nem.).',
 'pelješiti': 'Uzimati nekome silom, na prevaru ili na drugi način nešto vredno, obično novac; uporedi guliti: pelješio ga je na kartama (razg.).',
 'pepsin': 'Ferment želudačnog soka koji pomaže varenju belančevina (hem., grč.).',
 'perfekcionizam': 'Savrshenstvo, maksimum koji se može postići u radu, kvalitetu, ostvarenju nečega (engl.-fr.).',
 'perikarditis': 'Upala perikarda, srčane opne (med., grč.).',
 'personifikovati': '(Pri)davati ljudske osobine životinjama, stvarima i dr., prikaz(iv)ati ideje, apstraktne pojmove u obliku živih bića (lat.).',
 'perušati': 'Čupati perje s peradi (kokoš, gusku i sl.); i komšati (kukuruz); preneseno: izrabljivati, pljačkati nekoga.',
 'perverznost': 'Osobina onoga koji je perverzan, onoga što je perverzno.',
 'peskar': 'Onaj koji vadi, prosejava i prodaje pesak.',
 'peterac': 'Prostor ispred gola na fudbalskom igralištu oivičen pravougaonom linijom, golmanski prostor (sport); i kazneni udarac, penal u vaterpolu koji se izvodi s pet metara udaljenosti od gola.',
 'petnaestogodišnjak': 'Dečak od petnaest godina.',
 'petogodišnjica': 'Navršenih pet godina od nekog događaja (nečijeg rođenja, venčanja i dr.); dan proslave navršene godišnjice takvog događaja.',
 'petrograf': 'Stručnjak za petrografiju (grč.).',
 'pev': 'Izvođenje melodijskih tonova glasom, pevanje; i poj ptice pevačice.',
 'pećica': 'Umanjenica od peć; mala rerna.',
 'pečenjak': 'Mlad, nedozreo klip kukuruza; i takav klip kukuruza pečen na žaru, uporedi purenjak.',
 'pikati': 'Udarati nogom, šutirati loptu (fr.).',
 'pikirati': 'Obrus(ava)ti se okomito na cilj, o avionu (avij., fr.); preneseno: želeti domoći se nečega, imati nešto (pikirati na kolače, na bolje radno mesto).',
 'piknjica': 'Bubuljica; sitna tačkica; uopšte nešto veoma malo, jedva vidljivo (mrlja, ubod i dr.).',
 'piknuti': 'Lako udariti, šutnuti (loptu ili dr.).',
 'pisanica': 'Šareno uskršnje jaje.',
 'plakatni': 'Koji se odnosi na plakate.',
 'plastificirati': 'Presvući, presvlačiti nešto specijalnom plastičnom masom (plastificirati korice knjige).',
 'plastić': 'Umanjenica od plast.',
 'plebiscitaran': 'Koji je u vezi s plebiscitom; odlučen plebiscitom, opštenarodnom odlukom.',
 'plebiscitarno': 'Na plebiscitaran način, voljom naroda, plebiscitom.',
 'pleonastičan': 'Suvišno upotrebljen, već kazan na drugi način (pleonastičan izraz).',
 'plikavac': 'Vrsta bojnog otrova.',
 'plitica': 'Plitka zdela, plitka činija, čanak; i malo, plitko udubljenje, udubina.',
 'pljuca': 'Bljuvaonica (razg.); preneseno prezrivo: usta.',
 'plodište': 'Mesto gde se zameće plod, gde se nešto rađa (plodište jegulja, gljiva).',
 'plodotvoran': 'Plodan, plodonosan.',
 'plodov': 'Koji pripada plodu (plodova grančica).',
 'plovidben': 'Koji je u vezi s plovidbom (plovidbeni red vožnje, propis).',
 'pobacivati': 'Nesvršeni oblik glagola „pobaciti".',
 'pobediv': 'Koji se može pobediti.',
 'pobeliti': 'Učiniti nešto belim, obojiti u belo.',
 'pobiberiti': 'Posuti, začiniti biberom.',
 'pocakliti': 'Prevući slojem cakline, glazure (pocakliti zemljane sudove).',
 'pocrniti': 'Učiniti crnim ili crnjim (devojka krejonom pocrnila obrve).',
 'podalek': 'Prilično dalek, dosta udaljen.',
 'podarivati': 'Nesvršeni oblik glagola „podariti".',
 'podbradnik': 'Traka, kojom se šlem pričvršćuje pod bradom da bi se održao na glavi.',
 'podesnost': 'Osobina onoga što je podesno.',
 'podgorac': 'Čovek iz podgorine.',
 'podgorina': 'Kraj, teren koji se nalazi pod gorom, ispod planine.',
 'podivljalost': 'Osobina, stanje onoga koji je podivljao.',
 'podlački': 'Na podlački način, poput podlaca.',
 'podleteti': 'Leteći stići ispod nečega (vrapci podleteše ispod strehe); i pasti ili baciti se pod nešto (podleteti pod auto).',
 'podložak': 'Ono što je podloženo ispod nečega, podmetač.',
 'podnošljivost': 'Osobina onoga koji se može podneti, onoga što se može podneti; osobina onoga koji nešto može podneti.',
 'podozrivost': 'Osobina onoga koji je podozriv.',
 'podrapati': 'Iskidati na komadiće, poderati (podrapati košulju); (podrapati se) pocepati se, poderati se; preneseno: potući se (deca se podrapala).',
 'podrazred': 'U sistematizaciji: deo razreda koji sadrži jedinke istih ili sličnih osobina (sisari se dele na tri podrazredа); u klasifikaciji: deo razreda koji sadrži predmete, pojave i sl. istih ili sličnih osobina.',
 'podražiti': 'Uticati nečim na organizam ili njegov pojedini organ izazivajući reakciju (podražiti žuč); i neznatno nadražiti, malo izazvati (podražiti svраб); preneseno: rečima podstaći na neku akciju (podražiti na sukob).',
 'podržavljenje': 'Proces ostvarivanja državne nadležnosti, vlasništva itd. nad nečim.',
 'podsvestan': 'Koji se nalazi u podsvesti, koji je karakterističan za podsvest; nagonski, instinktivan (podsvestan strah, odluka).',
 'podulje': 'Isto što i poduže.',
 'podust': 'Isto što i skobalj (zool.).',
 'poduzetništvo': 'Isto što i preduzetništvo.',
 'podvižništvo': 'Podvižnikov način života.',
 'podvoljak': 'Debeli kožni nabor(i) ispod brade; mesto sličnog izgleda na vratu nekih životinja.',
 'podvrnuti': 'Zavrnuti kraj(eve) nečega prema unutra ili ispod nečega (podvrnuti rukave).',
 'podzidati': 'Izraditi podzid, učvrstiti podzidom.',
 'poentilizam': 'Način slikanja pomoću crta i tačkica; takav smer u slikarstvu s početka XX veka, blizak impresionizmu (fr.).',
 'pogibati': 'Nesvršeni oblik glagola „poginuti".',
 'pogodben': 'Koji se odnosi na pogodbu; lingv. pogodbena rečenica — zavisna rečenica kojom se izriče uslov za realizovanje onoga što se iznosi glavnom rečenicom, uslovna rečenica.',
 'pogrbljenost': 'Osobina ili stanje onoga koji je pogrbljen.',
 'pogrebnina': 'Cena pogreba.',
 'pogrešivost': 'Osobina onoga koji je pogrešiv.',
 'pohrana': 'Čuvanje, staranje, briga (zastava je predata muzeju na pohranu).',
 'pohranjivati': 'Nesvršeni oblik glagola „pohraniti".',
 'pokopavati': 'Nesvršeni oblik glagola „pokopati".',
 'pokroviteljica': 'Žena pokrovitelj.',
 'pokrštenica': 'Ona koja se pokrstila.',
 'pokusati': 'Kusajući pojesti.',
 'pokvarljivost': 'Osobina onoga što je pokvarljivo, kvarljivost.',
 'polifon': 'Višeglasan, mnogoglasan (polifona kompozicija).',
 'poliglot': 'Onaj koji govori više jezika (grč.).',
 'polihistor': 'Stručnjak za više nauka; sveznalica (grč.).',
 'poliptih': 'Slika sastavljena od više delova (grč.).',
 'politikantstvo': 'Vođenje politike na politikantski način ili takva akcija u politici.',
 'politkom': 'Politički komesar.',
 'polonistika': 'Nauka o poljskom jeziku i poljskoj književnosti (lat.).',
 'polovinka': 'Polovina cele note (muz.).',
 'polugica': 'Umanjenica od pola; uporedi polužica.',
 'polukružnica': 'Polovina kružnice (geom.); i ono što je u obliku polovine kružnice.',
 'polukvalifikovan': 'Koji nema potpunu kvalifikaciju (polukvalifikovan radnik).',
 'polulegalan': 'Delimično legalan (polulegalan posao).',
 'poluprilika': 'Delimično povoljna šansa da se postigne pogodak (sport).',
 'polusvestan': 'Koji nije sasvim svestan.',
 'polučasovni': 'Koji traje pola časa; koji se javlja na pola časa (polučasovni razgovor; otkucaj sata).',
 'pomađariti': 'Učiniti nekoga Mađarom; (pomađariti se) postati Mađar.',
 'pomičnost': 'Osobina, svojstvo onoga što je pomično; pokretljivost.',
 'pomodarski': 'Koji se odnosi na pomodare.',
 'pomodriti': 'Učiniti modrim.',
 'pomućenost': 'Stanje onoga koji je pomućen.',
 'popapati': 'Pojesti (dečje).',
 'popapriti': 'Posuti tučenom paprikom ili biberom; zaljutiti.',
 'poplaćati': 'Platiti sve jedno za drugim (poplaćati račune).',
 'popržiti': 'Ispržiti (na masti, ulju ili žaru); i opržiti, opaliti.',
 'popudbina': 'Hrana i piće za putovanje; i putni trošak.',
 'porazbacati': 'Razbacati sve, na sve strane.',
 'poredben': 'Koji se zasniva na poredbi, poređenju, uporedni (poredbena gramatika, anatomija); lingv. koji izražava poredbu, poređenje, koji služi za tu svrhu (poredbena kopula).',
 'poribljavati': 'Nesvršeni oblik glagola „poribiti".',
 'porobljavati': 'Nesvršeni oblik glagola „porobiti".',
 'porodiljstvo': 'Grana medicinske nauke koja se bavi trudnoćom i porođajem; takva nauka kao školski predmet.',
 'portretni': 'Koji se odnosi na portrete (portretna škola).',
 'porudžbenica': 'Narudžbenica.',
 'porugati': '(Porugati se) malo se narugati (porugati se detetu).',
 'porumeniti': 'Učiniti nešto rumenim.',
 'posavac': 'Čovek iz Posavine; i (posavac) konj ili pas iz Posavine.',
 'posediti': 'Učiniti sedim (kosu i sl.).',
 'poseljačiti': 'Učiniti seljakom, nametnuti seљački način života; (poseljačiti se) postati seljak, prihvatiti seљački način života; preneseno pežorativno: postati prost, necivilizovan.',
 'poseniliti': 'Postati senilan, izlapeti (deda je posenilio).',
 'poslastičarstvo': 'Posao, zanimanje poslastičara.',
 'poslovodstvo': 'Tim ljudi koji rukovodi poslovima jednog preduzeća (član poslovodstva); i zgrade ili prostorije u kojima taj tim ljudi radi (ići u poslovodstvo); i vođenje poslova.',
 'poslušnica': 'Ona koja je poslušna.',
 'posmrtnina': 'Ostavština posle smrti; i novčana pomoć koja se daje porodici pokojnika za pogreb.',
 'pospanac': 'Onaj koji voli da mnogo spava.',
 'pospešenje': 'Ubrzanje.',
 'posramljenost': 'Stanje onoga koji je posramljen.',
 'postiditi': 'Učiniti da se neko stidi, izazvati u nekome osećaj stida (postiditi prijatelja).',
 'postmoderan': 'Koji se javlja posle modernizma; karakterističan za doba postmoderne (postmoderna književnost).',
 'postmodernizam': 'Filozofski, estetski, umetnički itd. pokret s kraja XX veka koji u sebi sintetiše odlike modernih ideja odbacujući ideološki atažman.',
 'posustalost': 'Svojstvo, osobina onoga koji je posustao.',
 'potamnjenje': 'Potamnelost.',
 'potcrtavati': 'Nesvršeni oblik glagola „potcrtati".',
 'pothranjenost': 'Stanje onoga koji je pothranjen.',
 'potkontinent': 'Veliki deo kontinenta (azijski potkontinent).',
 'potkovanost': 'Osobina onoga koji je potkovan; preneseno: snabdevenost znanjem; stečeno znanje (potkovanost u nauci; školska potkovanost).',
 'potkožnjak': 'Potkožni čir (med.).',
 'potkupljivač': 'Onaj koji nekoga potkupljuje.',
 'potkupljivost': 'Osobina onoga koji je potkupljiv.',
 'potlačenost': 'Stanje onoga koji je potlačen (potlačenost robova).',
 'potolina': 'Udubljenje na površini zemlje koje je ispod nivoa obližnjeg mora (geogr.).',
 'potplat': 'Donji deo obuće u obliku stopala, kojim se gazi po tlu; đon.',
 'potpredsednički': 'Koji se odnosi na potpredsednike i potpredsednice.',
 'poučljivost': 'Osobina onoga koji je poučljiv, onoga što je poučljivo.',
 'povaljati': 'Rušeći oboriti na zemlju, srušiti sve redom (povaljati stabla); i valjajući, gazeći učiniti da nešto polegne (trava, žito); i valjajući izravnati nešto (testo, zemljište).',
 'povenuti': 'Prestati cvetati i zeleneti se, uvenuti (povenulo cveće); preneseno: izgubiti svežinu, boju (povenulo lice).',
 'poveseliti': 'Učiniti nekoga veselim (poveseliti šalama dete); (poveseliti se) provesti izvesno vreme u veselju; obradovati se.',
 'povikivati': 'Nesvršeni oblik glagola „povikati".',
 'povisilica': 'Znak koji obeležava da se nota koja za njim sledi povišava za polustepen (muz.).',
 'povisivati': 'Nesvršeni oblik glagola „povisiti"; uporedi povišavati.',
 'povodan': 'Bogat vodom, nadošao (o reci, potoku).',
 'povraz': 'Pokretna, lučna drška, ručica vedra ili košla (za nošenje ili vešanje); i traka za nošenje na torbi ili rancu; i tanka elastična nit od najlona i sl. za ribolov.',
 'povremenost': 'Osobina ili stanje onoga što je povremeno.',
 'povređenost': 'Svojstvo ili stanje onoga koji je povređen, onoga što je povređeno (povređenost noge).',
 'pozeleniti': 'Učiniti zelenim.',
 'pozerstvo': 'Ponašanje pozera; pozerski gest ili postupak.',
 'poznatost': 'Svojstvo, stanje onoga što je poznato.',
 'počerupati': '(Počerupati se) početi se čerupati, potući se (dečaci su se počerupali).',
 'počiniteljica': 'Ženska osoba počinitelj.',
 'pošljunčati': 'Posuti šljunkom (pošljunčati stazu).',
 'pošteđivati': 'Nesvršeni oblik glagola „poštedeti".',
 'požežanin': 'Stanovnik Požege; onaj koji je iz Požege.',
 'požutiti': 'Učiniti žutim.',
 'prakticizam': 'Shvatanje kojim se daje prednost praksi nad teorijom (fil.); i smisao za trenutne potrebe na štetu nekih principa.',
 'pramenka': 'Vrsta ovce grube vune koja visi u pramenovima (zool.).',
 'pranarod': 'Prvobitni narod iz kojeg je nastalo više srodnih naroda.',
 'praskavac': 'Gas koji eksplodira kada se upali (hem.).',
 'praskavo': 'Uz prasak, sa praskom.',
 'praslika': 'Prvobitna slika nečega prema kojoj su docnije načinjene druge; i idealna, zamišljena slika (praslika željene žene).',
 'prastanovnik': 'Prvobitni, iskonski stanovnik (Iliri su prastanovnici Balkana).',
 'pratvar': 'Osnovna, prvobitna stvar.',
 'praunučica': 'Umanjenica od praunuka.',
 'pravdoljublje': 'Ljubav prema pravdi.',
 'pravednica': 'Ženska osoba pravednik.',
 'pravokutnik': 'Isto što i pravougaonik (mat.).',
 'pravovernik': 'Onaj koji se pridržava vere, propisa koje ona nalaže.',
 'pravovernost': 'Svojstvo i stanje onoga koji je pravoveran.',
 'pravovremen': 'Koji se dešava na vreme ili u pravo vreme (pravovremen dolazak voza, intervencija doktora).',
 'prašnički': 'Koji se odnosi na prašnik i prašnicu.',
 'prebolan': 'Izuzetno, jako bolestan (često kao pojačanje uz „bolan"); i koji izaziva prejak bol.',
 'precrknuti': 'Naglo umreti, svisnuti (od žalosti, kakve nesreće i sl.).',
 'precrn': 'Suviše crn, vrlo crn.',
 'predalek': 'Suviše dalek, udaljen.',
 'predarežljiv': 'Suviše, preterano darežljiv.',
 'predavačica': 'Žena predavač.',
 'predilica': 'Mašina za izradu i obradu pređe.',
 'predioničarski': 'Koji se odnosi na predioničare i predionice.',
 'predispit': 'Uvodni, uslovni ispit.',
 'predistraga': 'Istraga pre glavne istraге.',
 'predodređenje': 'Predodređenost.',
 'predodređivati': 'Nesvršeni oblik glagola „predodrediti".',
 'predominantan': 'Prvenstven; nadmoćan, najjači (predominantan cilj, borac).',
 'predominantnost': 'Osobina onoga koji je predominaнtan, onoga što je predominantno.',
 'predrevolucionaran': 'Koji se odnosi na vreme pre revolucije; koji nosi karakteristike takvog vremena (predrevolucionarna godina; ustanak).',
 'predriblati': 'Driblingom prevariti protivničkog igrača (sport, engl.).',
 'preduverenje': 'Isto što i predubeđenje.',
 'preduzetnost': 'Preduzimljivost.',
 'predživot': 'Život koji prethodi sadašnjem životu.',
 'prefabrikat': 'Prerađevina.',
 'prefabrikovati': 'Preraditi u fabrici.',
 'preferirati': 'Da(va)ti prednost (nekome, nečemu), više ceniti, više voleti.',
 'preforsirati': 'Izložiti prevelikom napomru, premoriti (preforsirati konja); i preterano istaci, previše naglasiti.',
 'prehitar': 'Vrlo hitar.',
 'prehrabar': 'Izuzetno, vrlo hrabar.',
 'prehramben': 'Koji se odnosi na prehranu, koji služi za prehranu (prehrambeni proizvodi); prehrambena industrija — industrijska grana koja se bavi preradom sirovina za prehranu ljudi i stoke.',
 'prekasan': 'Previše, suviše kasan.',
 'prekiseo': 'Previše kiseo.',
 'prekitnjast': 'Previše kitnjast.',
 'prekrcati': 'Premestiti, prebaciti tovar s jednog broda na drugi, s jednog mesta na drugo, pretovariti; i nakrcati, natrpati preko mere (prekrcati brod); (prekrcati se) preći iz jednog u drugo prevozno sredstvo.',
 'prekrotak': 'Previše, suviše krотak.',
 'prekrupan': 'Suviše, previše krupan.',
 'prekrupiti': 'Načiniti prekrupu (prekrupiti kukuruz).',
 'prekvalifikovati': 'Učiniti da neko promeni kvalifikovanost (prekvalifikovati radnike); (prekvalifikovati se) steći novu kvalifikaciju.',
 'prelatura': 'Služba, položaj prelata.',
 'preliminaran': 'Prethodni, pripremni (preliminaran ugovor).',
 'preljut': 'Suviše, previše ljut.',
 'premlaćivati': 'Nesvršeni oblik glagola „premlatiti".',
 'premontirati': 'Naknadno, drugačije montirati (premontirati film).',
 'premostiv': 'Koji se može premостiti (premostiv kanal).',
 'preokupiranost': 'Preokupacija.',
 'preopterećenost': 'Svojstvo ili stanje onoga koji je preopterećen, onoga što je preopterećeno (preopterećenost broda, dece).',
 'preotmen': 'Suviše otmen.',
 'preovladavati': 'Nesvršeni oblik glagola „preovladati".',
 'preparkirati': 'Ponovo i drugačije parkirati vozilo; (preparkirati se) promeniti mesto parkiranja vozila kojim se upravlja.',
 'prepiti': 'Dati nekome previše alkoholnog pića da se opije; (prepiti se) opiti se preko mere.',
 'preplavljivati': 'Nesvršeni oblik glagola „preplaviti".',
 'preplašenost': 'Stanje onoga koji je preplašen.',
 'preporoditelj': 'Preporodilac.',
 'prepotentnost': 'Osobina onoga koji je prepotentan.',
 'prepunjenost': 'Stanje onoga što je prepunjeno.',
 'prepuzati': 'Bužući, puzeći preći (prepuzati čistinu).',
 'preradikalan': 'Suviše radikalan.',
 'preraspodeliti': 'Obaviti novu, drugačiju raspodelu; raspodeliti uopšte, iznova.',
 'prerasporediti': 'Izvršiti nov raspored (prerasporediti uloge); (prerasporediti se) izvršiti nov raspored između sebe.',
 'preredak': 'Suviše redak.',
 'prerez': 'Rezultat prerezivanja; mesto gde je nešto prerezano, presek.',
 'preroniti': 'Roneći stići s jedne na drugu obalu (preroniti kanal).',
 'prerumen': 'Jako rumen; suviše rumen (pupoljak prerumen).',
 'presbiro': 'Ustanova, služba za davanje informacija medijima (vladin presbiro, olimpijski presbiro) (fr.).',
 'presiguran': 'Suviše siguran.',
 'preslikač': 'Sličica koju je moguće preslikati, otpisnuti na neku podlogu.',
 'presnimavati': 'Nesvršeni oblik glagola „presnimiti".',
 'prestravljenost': 'Stanje onoga koji je prestravljen.',
 'presuđivati': 'Nesvršeni oblik glagola „presuditi".',
 'presvoditi': 'Podići svod preko nečega (presvoditi reку mostom) (arhitektura).',
 'pretaman': 'Suviše taman.',
 'pretezati': 'Nesvršeni oblik glagola „pretegnuti".',
 'pretisak': 'Odisak pisma ili slike na naročit papir i zatim prenošenje na drugu podlogu.',
 'pretkazanje': 'Proricanje, proročanstvo.',
 'pretkazati': 'Predvideti, proreći (pretkazati poplavu); (pretkazati se) unapred se pokazati.',
 'pretovarenost': 'Stanje, svojstvo onoga što je pretovareno, onoga koji je pretovaren; preopterećenost.',
 'pretplatnica': 'Žena pretplatnik.',
 'pretpranje': 'Pranje koje prethedi glavnom pranju (kao prvi program u mašinama za pranje rublja).',
 'pretrom': 'Odveć, previše trom.',
 'pretruo': 'Previše truo.',
 'pretrčavati': 'Nesvršeni oblik glagola „pretrčati".',
 'preturoban': 'Odveć, previše turoban, žalostan.',
 'pretvorivost': 'Osobina onoga koji je pretvoriv, onoga što je pretvorivo.',
 'pretvornik': 'Onaj koji se pretvara, licemer, dvoličnjak.',
 'preuranjenost': 'Svojstvo onoga što je preuranjeno.',
 'preuzbuditi': '(Preuzbuditi se) preterano, prekomerno se uzbuditi.',
 'preuzvišenost': 'Titula visokih svetovnih i crkvenih dostojanstvenika.',
 'preučeno': 'Previše, odveć učeno.',
 'preveseo': 'Preterano, suviše veseo.',
 'prevladavati': 'Nesvršeni oblik glagola „prevladati".',
 'prevodljiv': 'Prevodiv.',
 'prevodnica': 'Uređaj na pregrađenim rekama ili velikim kanalima kojim se plovna sredstva prevode iz nižeg vodostaja u viši i obratno.',
 'prevoznina': 'Taksa koja se plaća za prevoz.',
 'prevratništvo': 'Delovanje prevratnika; ideja prevrata.',
 'prevredan': 'Veoma izuzetno vredan.',
 'prezaduženost': 'Stanje onoga koji je prezadužen.',
 'prezaposlenost': 'Stanje onoga koji je prezaposlen.',
 'prezentski': 'Koji se odnosi na prezent (prezentska osnova).',
 'prezimenjakinja': 'Ženska osoba prezimenjak.',
 'prezimljavati': 'Nesvršeni oblik glagola „prezimiti".',
 'prezrelost': 'Stanje onoga koji je prezreo, onoga što je prezrelo.',
 'prezrenje': 'Prezir.',
 'prečestit': 'Vrlo čestit, previše čestit.',
 'prečistač': 'Uređaj za prečišćavanje, filter.',
 'prešarati': 'Suviše išarati, ušareniti; i povući mnogo crta preko napisanog, precrtati više puta.',
 'prešetati': 'Šetajući preći (neki prostor, mesto).',
 'prešećeriti': 'Previše, suviše zašećeriti.',
 'prešišati': 'Prestići; nadmašiti (prešišati nekoga u trku; u uspehu) (razg.).',
 'prežderati': '(Prežderati se) previše se nažderati (ekspresivno).',
 'prežestok': 'Previše žestok.',
 'prhak': 'Koji se lako mrvi, rasipa, sipak (prhak gips, zemlja); i nejak, slab (prhka snaga).',
 'prhati': 'Nesvršeni oblik glagola „prhnuti".',
 'prhutati': 'Umanjeno: prhati.',
 'približnost': 'Svojstvo, osobina onoga što je približno.',
 'prideljivati': 'Nesvršeni oblik glagola „prideliti".',
 'pridobivati': 'Nesvršeni oblik glagola „pridobiti".',
 'prigorac': 'Čovek iz prigorja.',
 'prihvatljivost': 'Svojstvo onoga što je prihvatljivo.',
 'prikleštiti': 'Kleštima stegnuti; pritisnuvši povrediti, prizgnječiti; preneseno: primorati, prisiliti nekoga da ostane negde (prikleštena je u krevetu).',
 'priključnica': 'Kutija kojom se priključuje električna struja; uporedi priključak.',
 'prikованost': 'Stanje onoga koji je prikovan, onoga što je prikovano.',
 'prikrivenost': 'Osobina ili stanje onoga koji se prikriva, onoga što je prikriveno.',
 'prikupljenost': 'Stanje u kojem je nešto u velikom broju na jednom mestu skupljeno.',
 'prilepljiv': 'Koji se lako lepi.',
 'primas': 'Najviši crkveni dostojanstvenik u jednoj zemlji (lat.).',
 'primenljivost': 'Osobina i stanje onoga koji je primenljiv, mogućnost primene u datom slučaju; uporedi primenjivost.',
 'primerenost': 'Stanje onoga što odgovara čemu.',
 'primešati': 'Mešajući dodati, pridodati (primešati u supu malo kajmaka; preneseno: primešati istini hiljadu laži); (primešati se) pomešati se s nekim, pridružiti se.',
 'primitivka': 'Žena primitivac.',
 'prionljiv': 'Koji lako prianja (prionljive ružičaste glave čička).',
 'priorat': 'Priorova služba; i područje na kojem prior vrši službu.',
 'pripadništvo': 'Svojstvo, stanje onoga koji pripada komе ili čemu, pripadanje.',
 'pripomena': 'Napomena.',
 'pripovedačica': 'Žena pripovedač.',
 'pripovediti': 'Ispričati.',
 'priprostost': 'Osobina onoga koji je priprost, onoga što je priprosto.',
 'pripržiti': 'Malo, ne sasvim ispržiti.',
 'pripust': 'Puštanje ženke mužjaku radi oplođavanja (obično o kravi ili kobili).',
 'pripuštati': 'Nesvršeni oblik glagola „pripustiti".',
 'priraslica': 'Patološko srastanje dvaju organа ili dveju struktura (med.).',
 'prisnažiti': 'Učiniti snažnijim, jačim, ojačati, osnažiti, okrepiti.',
 'prispavati': 'Nesvršeni oblik glagola „prispati".',
}

C = {
 'pav': 'glosa fragmentarna; značenje nejasno',
 'pavati': 'glosa fragmentarna; značenje nesigurno',
 'pedološkom': 'glosa fragmentarna (deo tuđe odrednice); značenje nejasno',
 'periši': 'glosa fragmentarna; značenje nejasno',
 'peš': 'glosa samo uput (OCR-nečitljiv); značenje nejasno',
 'peševima': 'glosa samo uput (OCR-nečitljiv); značenje nejasno',
 'pina': 'glosa fragmentarna (deo odrednice „vetrić"); značenje nejasno',
 'popizditi': 'vulgarno (razg. vulg. po Matici); rečnik takve reči ne vodi',
 'posranac': 'gruba reč (srati-familija); rečnik takve reči ne vodi',
 'posrati': 'vulgarno (vulg. izvršiti veliku nuždu); rečnik takve reči ne vodi',
 'pova': 'glosa fragmentarna; značenje nejasno',
 'požarstvo': 'glosa OCR-nejasna (vojnička služba?) — nesigurno',
 'preponašica': 'ženski oblik od „preponaš"; osnovna reč nejasna',
 'priređivanje': 'pogođen kolofon rečnika, ne prava odrednica; glosa neuhvaćena — nesigurno',
}
