# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 331–660 (citogenetika … epiglotis).

DEC = {
 'citogenetika': 'Grana biologije koja izučava građu i funkcije ćelije u vezi sa nasleđem.',
 'citoplazma': 'Ćelijska protoplazma, osnovni vodenasti prozirni deo ćelije u kojem se nalazi jedro (biol.).',
 'cmariti': 'Peći, pržiti (na masti, ulju): cmariti slaninu; i (o sirovom drvetu) vištati goreći.',
 'crepar': 'Onaj koji pravi crepove.',
 'crepić': 'Umanjenica od crep.',
 'crevar': 'Mesar koji se bavi prerađivanjem, obradom creva i njihovom prodajom.',
 'crnjuša': 'Rod grmolikih, ređe drvenastih biljaka iz familije vresova (bot.).',
 'crnogorični': 'Koji se odnosi na crnogoricu; koji se sastoji od crnogorice (crnogorična šuma).',
 'crnokošuljaš': 'Čovek koji nosi crnu košulju; italijanski fašista (ist.).',
 'crnčiti': 'Raditi težak, naporan posao, dirinčiti (crnčiti u polju) — razgovorno.',
 'crnčić': 'Umanjenica od crnac; mlad crnac; dečak crnac.',
 'crpilište': 'Mesto gde se nešto crpi (crpilište nafte).',
 'crtačica': 'Žena crtač.',
 'crvenoglav': 'Koji je crvene glave, obično o insektu (crvenoglava buba).',
 'crvenokljun': 'Koji ima crven kljun (crvenokljuna ptica).',
 'crvljivost': 'Osobina, stanje onoga što je crvljivo (crvljivost ploda).',
 'crvolik': 'Koji liči na crva, koji ima oblik crva.',
 'crvov': 'Koji pripada crvu.',
 'cuca': 'Čovek iz plemena Cuce u Crnoj Gori.',
 'cuki': 'Pas, pseto, psetance (nežni oblik).',
 'curak': 'Tanki neprekidni mlaz tečnosti (curak krvi, vode, znoja).',
 'curetina': 'Uvećanica i pežorativ od cura.',
 'cvatnja': 'Cvetanje; doba cvetanja.',
 'cvetina': 'Uvećanica od cvet.',
 'cvetište': 'Vrh cvetne peteljke na kojoj stoji cvet, cvetna loza (bot.).',
 'cvećarica': 'Žena cvećar; cvećarka.',
 'cvećarstvo': 'Grana poljoprivrede koja se bavi gajenjem cveća.',
 'cvikla': 'Umetak u obliku klina na suknji ili pantalonama: suknja sa cviklama (nem.).',
 'cvilež': 'Cviljenje (cvilež deteta, psa).',
 'cvrk': 'Glas cvrčaka (onomatopeja).',
 'cvrčkov': 'Koji pripada cvrčku, koji se odnosi na cvrčka (cvrčkova pesma).',
 'dalmatika': 'Svečana ukrašena odeća poreklom iz kasnorimskog doba koju su nosili vladari, pape i biskupi; katoličko liturgijsko ruho (lat.).',
 'darda': '(Obično u vezi: igrati darde) vrsta kartaške igre.',
 'darvinistički': 'Koji se odnosi na darvinizam i darviniste (darvinistička teorija).',
 'davalaštvo': 'Akcija, običaj davanja (dobrovoljno davalaštvo krvi).',
 'daždeti': 'Padati (o kiši), kišiti; i donositi, ispuštati iz sebe kišu (o oblaku) — obično bezlično.',
 'debelokoštvo': 'Osobina onoga koji je debelokožan.',
 'decentno': 'Pristojno, uljudno; skromno, suzdržljivo.',
 'decentnost': 'Osobina onoga koji je decentan; pristojnost, uljudnost; skromnost, suzdržljivost.',
 'decimalan': 'Koji se odnosi na decimale, desetni (decimalni broj, razlomak, zapeta); koji se zasniva na podeli na deset delova, dekadni (mat.).',
 'defanzivac': 'Sportista koji igra izrazito defanzivno (sport).',
 'deinstalirati': 'Ukloniti, uklanjati ono što je instalirano (obično neki kompjuterski program).',
 'dekorativnost': 'Osobina onoga što je dekorativno.',
 'dekstrin': 'Žutkasti prašak, ugljeni hidrat koji se dobija iz skroba, a upotrebljava se kao lepak, sredstvo za gušnjavanje i očvršćivanje pri apreturi (hem.).',
 'dekubitus': 'Rana na delovima tela izloženim pritisku kod nepokretnih bolesnika koji dugo leže (med.).',
 'delegatkinja': 'Žena delegat, izaslanica.',
 'delin': 'Vrsta pamučne tkanine.',
 'delovodnik': 'Delovodni protokol (adm.).',
 'demistifikovati': 'Ukloniti, uklanjati obmane s nečega, prikaz(iv)ati u pravom svetlu, razobličiti, razobličavati (demistifikovati politiku).',
 'demokratizam': 'Demokratska načela, shvatanja, ideje, težnje; demokratski duh, demokratičnost.',
 'demokratkinja': 'Žena demokrata.',
 'denominirati': 'Izvršiti denominaciju.',
 'dentin': 'Koštano tkivo zuba (anat.).',
 'depilator': 'Kozmetičko sredstvo za uklanjanje dlaka s tela.',
 'depresivnost': 'Stanje i osobina onoga koji je depresivan, onoga što je depresivno.',
 'deprimiranost': 'Stanje onoga koji je deprimiran; obeshrabrenost, malodušnost; potištenost, utučenost.',
 'deratizirati': 'Izvršiti deratizaciju.',
 'dereze': 'Pomagalo od gvožđa sa zupcima koje se stavlja na obuću radi lakšeg hoda po klizavom tlu i ledu (sport; množina).',
 'derivirati': 'Izvesti, izvoditi (naročito novi oblik, novu reč i dr.) iz nečega; i proizići, proizilaziti, nastajati iz nečega.',
 'dermatološki': 'Koji se odnosi na dermatologe i dermatologiju (dermatološko odeljenje).',
 'dernuti': 'Snažno udariti, lupiti, mlatnuti, tresnuti (dernuti šakom o sto); i pasti, tresnuti; jako pucati, prasnuti.',
 'derutnost': 'Derutno stanje, zapuštenost, oronulost, trošnost.',
 'des': 'Muz. za pola stepena sniženi ton „de".',
 'desetinka': 'Deseti deo sekunde (pretrčati stazu za 5 sekundi i 2 desetinke).',
 'desetorostruk': 'Deset puta veći, desetostruk.',
 'desetorostruko': 'Deset puta više, jače (desetorostruko više).',
 'despik': 'Rod višegodišnjih mediteranskih zeljastih biljaka (bot.).',
 'despotstvo': 'Despotovo zvanje, dostojanstvo; despotova vladavina, despotovanje; i despotovina — oblik uređenja zemlje kojom vlada despot (ist.).',
 'destilator': 'Aparat, uređaj za destilaciju; i onaj koji vrši destilaciju.',
 'destruktivac': 'Onaj koji deluje destruktivno; rušilac.',
 'destruktivnost': 'Osobina onoga koji je destruktivan, onoga što je destruktivno; razorno, štetno, pogubno dejstvo.',
 'deterministički': 'Koji se odnosi na determinizam i deterministe (determinističko shvatanje, škola, gledište).',
 'detronizirati': 'Svrgnuti, svrgavati, zbaci(va)ti s prestola.',
 'devastirati': 'Opustošiti, uništiti, uništavati (devastirati šume).',
 'devedesetak': 'Oko devedeset, približno devedeset (osoba, predmeta i dr.).',
 'deveničar': 'Onaj koji pravi i prodaje devenice (vrstu kobasice nadevene mesom).',
 'deverić': 'Umanjenica i nežni oblik od dever.',
 'devetnaestogodišnjak': 'Onaj koji ima devetnaest godina.',
 'devetnica': 'Molitva koja se čita svaki dan, uzastopno, za devet dana (crkv.).',
 'dezertirati': 'Samovoljno pobeći, bežati iz vojske, s fronta, iz borbe (voj.); preneseno: nedostojno se izvući, izvlačiti iz teške situacije.',
 'dezinformator': 'Onaj koji lažno, netačno obaveštava.',
 'dezorganizator': 'Onaj koji vrši dezorganizaciju.',
 'dešifrant': 'Onaj koji se bavi dešifrovanjem.',
 'dielektričan': 'Koji razdvaja dva provodnika i sprečava protok struje između dva različito naelektrisana tela, izolacioni (dielektrično telo, sredstvo).',
 'dihtovati': 'Biti čvrsto priljubljen, dobro nalegati, ne propuštati (vazduh, tečnost), biti nepropusan na spojevima (nem., tehn.).',
 'dimorfizam': 'Pojava da jedinke jedne vrste imaju dva različita oblika (biol.).',
 'dinamitaš': 'Radnik koji rukuje dinamitom, miner; i onaj koji vrši diverzije dinamitom.',
 'dinamizirati': 'Učiniti dinamičnim; dovesti, dovoditi u živo, dinamično kretanje.',
 'dinamometar': 'Naprava, sprava za merenje sile.',
 'dinarka': 'Žena dinarske rase, dinarskog etničkog i antropološkog tipa.',
 'dingač': 'Vrsta crnog grožđa s poluostrva Pelješca; vino od tog grožđa, nazvano po selu Dingaču (agr.).',
 'dinjar': 'Prodavac dinja.',
 'dinjin': 'Koji se odnosi na dinju, koji je od dinje (dinjino seme, kora).',
 'diplomatkinja': 'Ženska osoba diplomata.',
 'direktorstvo': 'Dužnost, služba direktora; položaj, zvanje direktora.',
 'disalica': 'Maska za podvodno disanje.',
 'disciplinarno': 'Isto što i disciplinski.',
 'disidentstvo': 'Disidentski stav, disidentsko držanje.',
 'diskograf': 'Onaj koji se bavi diskografijom.',
 'diskontinuitet': 'Isprekidanost, nepovezanost.',
 'diskriminator': 'Uređaj za demodulaciju radio-talasa s frekventnom modulacijom (fazni, frekvencijski diskriminator) (el.).',
 'disocirati': 'Prekinuti, prekidati asocijativno povezane pojave, procese (psih.); i rastaviti, rastavljati, razložiti, razlagati (hem.).',
 'disproporcionalan': 'Koji pokazuje disproporciju, nesrazmeran, neskaldan (disproporcionalan odnos, visina).',
 'disproporcionalno': 'Na disproporcionalan način, nesrazmerno, neskladno.',
 'distingviran': 'Koji se razlikuje od drugih, uglađen, otmen; istaknut (distingvirana dama).',
 'distinktivan': 'Koji odvaja, razlikuje dve stvari, dva pojma i sl. (distinktivno obeležje).',
 'distrofičar': 'Onaj koji je oboleo od distrofije.',
 'divergirati': 'Razići se, razilaziti se, udalji(va)ti se jedno od drugog; biol. razvi(ja)ti različite osobine pod uticajem različitih životnih uslova.',
 'divokozin': 'Koji se odnosi na divokozu, koji pripada divokozi; koji je kao u divokoze (divokozina koža, hitrost).',
 'dizaličar': 'Onaj koji rukuje, upravlja dizalicom.',
 'dobavni': 'Koji se odnosi na dobavu, nabavni (dobavni ugovor, rok).',
 'dobran': 'Dosta velik, poveć, priličan (dobran parče, suma novca).',
 'dobraš': 'Đak koji ima dobar uspeh u školi (šatr.).',
 'dobrosusedstvo': 'Dobrosusedski, prijateljski odnosi.',
 'dobrotvorka': 'Žena dobročinitelj, dobročiniteljka.',
 'docrtavati': 'Nesvršeni oblik glagola „docrtati".',
 'dogledati': 'Dobaciti pogledom do nečega udaljenog, sagledati.',
 'dogmatički': 'Na dogmatičan način, svojstveno dogmatičarima (shvatiti nešto dogmatički).',
 'dogmatičnost': 'Osobina onoga što je dogmatično; privrženost dogmama, slepo prihvatanje dogmi, dogmatizam.',
 'dogon': 'Dogonjenje, dostizanje (dogon stoke); i dovoženje, dovoz tereta na tovarnoj životinji ili zaprežnom vozilu (dogon drva).',
 'dogotoviti': 'Dovršiti gotovljenje, pripremanje, spravljanje jela, pripremiti (dogotoviti ručak).',
 'dohrana': 'Dodatak redovnoj ishrani, dopunska ishrana, dohranjivanje, prihrana (uzeti nekoga na dohranu); i ono čime se neko dohranjuje, dopunska hrana.',
 'dokazivost': 'Mogućnost dokazivanja.',
 'dokačiti': 'Zakačiti, zahvatiti, okrznuti (dokačiti nogom, metkom); razg. napasti nekoga u razgovoru; (dokačiti se) zavaditi se, posvađati se.',
 'doker': 'Radnik koji radi na doku, lučki radnik.',
 'doklizati': '(Doklizati se) dospeti do nekog mesta klizajući se.',
 'doktorand': 'Onaj koji se sprema za doktorski ispit; kandidat za doktorski stepen.',
 'dokumentaristički': 'Koji se odnosi na dokumentariste, svojstven dokumentaristima (dokumentaristički zapis).',
 'dokupljivati': 'Nesvršeni oblik glagola „dokupliti".',
 'dokučivost': 'Osobina onoga što je dokučivo, dostupno umu; razumljivost, shvatljivost.',
 'dolepršati': 'Doći, stići lepršajući, doleteti.',
 'doljanin': 'Stanovnik dola, dolje, dolinac.',
 'dolutati': 'Doći, stići ljuljajući.',
 'dominantnost': 'Stanje i osobina onoga što je dominantno; biol. dominantan učinak gena jednog roditelja nad odgovarajućim genom drugog roditelja.',
 'domić': 'Umanjenica i nežni oblik od dom.',
 'donkihotski': 'Koji se odnosi na Don Kihota, svojstven Don Kihotu; koji ne odgovara duhu vremena, nesavremen i nerealan, romantično zanesenjački (donkihotski poduhvat).',
 'donžuanski': 'Koji se odnosi na Donžuane, zavodnički.',
 'donžuanstvo': 'Osobina Donžuana, donžuanski postupci, zavodništvo.',
 'doplutati': 'Stići plutajući, doploviti nošen vodom.',
 'dopustivost': 'Osobina onoga što je dopustivo, prihvatljivost.',
 'doraslost': 'Stanje i osobina onoga koji je dorastao, zrelost.',
 'dorečenost': 'Osobina onoga što je dorečeno; završenost iskaza, zaokruženost.',
 'dosanjati': 'Dovršiti sanjanje, san, odsanjati do kraja, dosanjati; preneseno: doživeti ostvarenje svojih snova, želja.',
 'dosita': 'Do sitosti, do potpunog zadovoljenja potrebe za jelom i pićem (jesti dosita, piti dosita); i do mile volje (dosita uživati, smejati se).',
 'doskočljiv': 'Domišljat, dovitljiv, snalažljiv; duhovit.',
 'dosnivati': 'Nesvršeni oblik glagola „dosnovati".',
 'dostavljački': 'Koji se odnosi na dostavljače.',
 'dotegliti': 'Dovući plovni objekat tegljenjem, remorkirati (dotegliti brod, teglenicu); i dovući nekoga zakinuvši svom snagom (dotegliti nekoga za kosu).',
 'doveslati': 'Doći, pristići veslajući (doveslati do obale); i dovesti, doterati veslajući (doveslati barku).',
 'dozimetar': 'Sprava za merenje doze, količine radioaktivnog ili rendgenskog zračenja.',
 'doškolovanje': 'Završetak naknadnog školovanja.',
 'došuljati': 'Isto što i došunjati se (tiho i neprimetno se približiti).',
 'doživljenje': 'Spoznaja nečega, ono što se doživi, doživljaj; doživljenost.',
 'dragovoljnost': 'Osobina onoga što je dragovoljno; dobra volja.',
 'draguljarstvo': 'Draguljarski zanat, draguljarsko zanimanje.',
 'dramatičarka': 'Žena dramatičara.',
 'dražbovatelj': 'Onaj koji učestvuje na dražbi kao kupac, penuđač, licitant.',
 'dražbovati': 'Izložiti, izlagati dražbi, proda(va)ti na dražbi; izvršiti dražbu, licitirati.',
 'drenić': 'Umanjenica od dren.',
 'drenjak': 'Isto što i drenak (plod drena, crvena kiselkasta bobica).',
 'driti': '(Driti se) snažno se razlegati, odjekivati (o pesmi, glasu, zvuku).',
 'drpiti': 'Grubo uhvatiti, grabiti, ščepati; grubo zahvatiti, potkačiti; razg. ukrasti, oteti, zdipiti.',
 'drugorođeni': 'Koji je rođen drugi po redu (drugorođeni brat, sestra).',
 'drukati': 'Podvrgavati pritisku, pritiskati, obično više puta (drukati kočnicu) (nem.); žarg. odavati, potkazivati, obično policiji, cinkariti (drukati prijatelje).',
 'društvenost': 'Osobina onoga koji je društven, onoga što je društveno.',
 'druželjubivost': 'Osobina onoga koji je druželjubiv, druželjubiv odnos prema ljudima.',
 'družić': 'Umanjenica i nežni oblik od drug.',
 'drvenina': 'Drveni deo kućnog nameštaja, drvenarija.',
 'drvodeljstvo': 'Drvodeljski zanat, posao.',
 'drvoprerađivač': 'Radnik koji se bavi preradom drveta.',
 'drvorezbar': 'Onaj koji izrađuje drvene rezbarije, drvorezac.',
 'drvorezbarstvo': 'Drvorezbarska veština, tehnika oblikovanja ili ukrašavanja drvenih predmeta dletom, duborez, drvorez.',
 'državnica': 'Žena državnik.',
 'državništvo': 'Smisao za vođenje državničkih poslova, državnička veština, mudrost; i (zbirno) državnici, diplomatija.',
 'državotvornost': 'Osobina onoga koji je državotvoran, onoga što je državotvorno; aktivnost na stvaranju i jačanju države.',
 'dualistički': 'Koji se odnosi na dualizam i dualiste (dualističko učenje).',
 'dubić': 'Umanjenica i nežni oblik od dub.',
 'dudinjak': 'Voćnjak zasađen dudovima; dudov gaj.',
 'dudov': 'Koji se odnosi na dud, koji pripada dudu, koji je od duda (dudov list, drvo).',
 'dudovača': 'Rakija od dudinja.',
 'dugmetara': 'Harmonika na dugmeta, umesto dirki.',
 'dugokljun': 'Koji ima dug kljun (dugokljuna roda).',
 'dugoprugaš': 'Atletičar koji trči na dugim stazama, preko 3.000 metara (sport).',
 'dugorog': 'Koji ima duge rogove (dugoroga antilopa).',
 'dugorun': 'Koji ima dugo runo (dugoruna ovca).',
 'duhovništvo': '(Zbirno) duhovnički stalež; duhovnici, sveštenstvo, kler; i duhovnički poziv, duhovnička služba.',
 'dupljina': 'Velika duplja; duplja uopšte.',
 'dućančić': 'Umanjenica i nežni oblik od dućan.',
 'dušebrižnički': 'Koji se odnosi na dušebrižnike (dušebrižnička misija, služba).',
 'duždević': 'Duždev sin.',
 'dvadesetogodišnjica': 'Navršena dvadeseta godina od nekog događaja; proslava, pomen tog događaja (dvadesetogodišnjica nečije smrti, rođenja).',
 'dvestagodišnjica': 'Dvestota godina od nekog događaja; proslava tog događaja.',
 'dvizac': 'Ovan ili jarac u drugoj godini života.',
 'dvocevan': 'Koji ima dve cevi (dvocevna puška, dvocevni pištolj).',
 'dvokratan': 'Koji se vrši, zbiva, pojavljuje i sl. dva puta, u dva maha (dvokratna pomoć, bolovanje, radno vreme).',
 'dvoličnjak': 'Dvolican čovek, licemer.',
 'dvomesečan': 'Koji ima dva meseca; koji traje dva meseca, koji služi za dva meseca i sl. (dvomesečna beba, vežba, plata).',
 'dvomesečnik': 'List ili časopis koji izlazi jedanput u dva meseca.',
 'dvopotezni': 'Koji se izvodi, rešava u dva poteza, o šahovskim problemima (dvopotezni mat, kombinacija) (šah).',
 'dvoranski': 'Na način svojstven dvoranima; preneseno: ulizički, udvorički.',
 'dvored': 'Dva paralelna reda, niza ljudi, životinja ili predmeta (dvored ljudi, drva).',
 'dvoruk': 'Koji ima dve ruke.',
 'dvospratan': 'Koji ima dva sprata (dvospratna kuća).',
 'dvosupnica': '(U množini) biljke skrivenosemenice sa dve supke, dva kotiledona u semenu, dikotiledone biljke; (u jednini) takva biljka (bot.).',
 'dvotrećinski': 'Koji čini dve, odnosno više od dve trećine nečega (dvotrećinska većina, sastav); i koji ima dve trećine (dvotrećinski takt).',
 'dvotrupac': 'Avion, brod i sl. koji ima dva trupa (avion dvotrupac, brod dvotrupac).',
 'dvoznačnost': 'Osobina onoga što je dvoznačno; mat. dvojaka vrednost, dvojako rešenje (dvoznačnost funkcije); i dvojak smisao, dvosmislenost.',
 'dvočlan': 'Koji se sastoji iz dva člana, iz dva sastavna dela, dvodelni (dvočlani izraz, naziv, ime).',
 'džainizam': 'Religiozno-filozofsko učenje u Indiji sa asketskim načelima sličnim budizmu.',
 'džambaski': 'Koji se odnosi na džambase, svojstven džambasima; lukav, prepredenjački.',
 'džepić': 'Umanjenica od džep.',
 'dževa': 'Vika, galama; dići dževu (tur.).',
 'džoger': 'Onaj koji se bavi džogingom (engl.).',
 'džogirati': 'Baviti se džogingom.',
 'džuma': 'Svečana muslimanska molitva u džamiji petkom u podne (tur.).',
 'ebonitni': 'Koji je od ebonita (ebonitni štapić).',
 'edematozan': 'Zahvaćen edemom, otečen, podbuo (edematozno tkivo, lice).',
 'efe': 'Lučno kretanje lopte (u fudbalu, bilijaru i sl.) izazvano udarcem koji nije upravljen u njenu sredinu (fr.).',
 'efemeride': 'Godišnjak, tablice koje za neki period vremena unapred donose podatke o kretanju nebeskih tela i drugim promenama (astr., grč.; množina).',
 'egal': 'Ravno, jednako; svejedno (fr.).',
 'egalitarizam': 'Izjednačenje, jednakost u političkom, socijalnom, kulturnom i dr. smislu; shvatanje koje teži ostvarenju potpune jednakosti među ljudima (fr.).',
 'egida': 'Grč. mit. štit s glavom gorgone; preneseno: zaštita, okrilje, pokroviteljstvo (pod nečijom egidom — pod nečijim okriljem).',
 'egocentrik': 'Egocentričan čovek.',
 'egoističnost': 'Osobina onoga koji je egoističan, egoizam.',
 'egzekutorski': 'Koji se odnosi na egzekutore, svojstven egzekutorima (egzekutorska surovost).',
 'egzemplaran': 'Koji služi kao primer, uzor; primeran, uzoran (egzemplarna knjiga, prevod); i koji služi kao opomena radi odvraćanja od sličnih dela (egzemplarna kazna, globa).',
 'egzemplarno': 'Primereno, uzorno; tako da služi kao poučan, zastrašujući primer (egzemplarno kazniti).',
 'egzosfera': 'Spoljni sloj zemljine atmosfere, iznad 600 km (grč.).',
 'egzoterman': 'Koji se vrši, obavlja uz razvijanje, ispuštanje toplote, pri kojem se oslobađa toplota, o hemijskim procesima (egzotermna hemijska reakcija) (hem.).',
 'egzotičnost': 'Osobina onoga što je egzotično; egzotičan predmet ili egzotična pojava.',
 'ehe': 'Uzvik u iznenađenju, čuđenju, divljenju i sl.; i u suprotstavljanju, neslaganju.',
 'ekipirati': 'Opremiti, opremati, snabde(va)ti potrebnim ljudstvom ili opremom (ekipirati posadu); (ekipirati se) opremiti se.',
 'eklektičan': 'Sastavljen od raznorodnih delova, elemenata; napabirčen, skrpljen (eklektičan sistem, poezija).',
 'ekliptički': 'Koji se odnosi na ekliptiku.',
 'ekonomat': 'Odeljenje u preduzeću ili ustanovi koje se brine o nabavci, čuvanju i raspodeli potrošnog materijala (bolnički ekonomat); i služba ekonoma.',
 'ekonomistkinja': 'Žena ekonomista.',
 'ekonomizam': 'Oportunistička struja u međunarodnom, prvenstveno ruskom, socijaldemokratskom pokretu prema kojoj je osnovni zadatak radničke klase samo ekonomska borba protiv kapitalista, a ne i politička (ist.).',
 'ekscentar': 'Kružna ploča, disk ekscentrično učvršćen na osovinu (maš., lat.).',
 'eksirati': 'Ispijati na eks (šatr.).',
 'ekskavator': 'Građevinska mašina za iskopavanje i prenošenje zemlje, ruda, jalovine i dr., koja se kreće na gusenicama ili šinama (lat.).',
 'ekskluzivizam': 'Sklonost ekskluzivnosti, isključivosti; ekskluzivnost (literarni ekskluzivizam).',
 'ekspander': 'Gimnastička sprava za jačanje ručnih mišića, sa elastičnim žicama koje se rastežu između dve drške (sport).',
 'ekspanzionizam': 'Ekspanzivna politika, sklonost ekspanziji; osvajačke, imperijalističke težnje.',
 'eksplantat': 'Presađeno tkivo (med.).',
 'eksplantirati': 'Izvršiti eksplantaciju (eksplantirati bubrege).',
 'eksplicitnost': 'Osobina onoga što je eksplicitno, izričitost, jasnost.',
 'eksponiranost': 'Osobina onoga što je eksponirano, izloženo; isticanje u javnosti.',
 'eksponirati': 'Izložiti, izlagati, prikaz(iv)ati, pokaz(iv)ati (eksponirati sliku, snagu); razviti, razraditi književno delo; fot. izložiti fotografski materijal dejstvu svetlosti.',
 'ekspresionistkinja': 'Ženska osoba ekspresionista.',
 'ekspresivno': 'Na ekspresivan način, izrazito, izražajno, upečatljivo (ekspresivno prikazati, naslikati).',
 'ekstatičan': 'Koji je u stanju ekstaze; pun zanosa, ushićenja (ekstatično divljenje).',
 'ekstatičnost': 'Osobina onoga što je ekstatično, velika zanesenost, zanos, ekstaza.',
 'ekstenzor': 'Mišić koji isteže, ispravlja ud; istežač (anat.).',
 'ekstrahirati': 'Izdojiti, izdvajati ekstrakcijom; izvući, izvlačiti.',
 'ekstraprofit': 'Višak iznad prosečnog profita, posebna, natprosečna zarada ostvarena zbog povoljnijih uslova poslovanja.',
 'ekstremistički': 'Koji se odnosi na ekstremizam i ekstremiste (ekstremistička shvatanja).',
 'ekstremnost': 'Osobina onoga što je ekstremno, ekstremizam.',
 'ekstruder': 'Vrsta pužne prese koja se upotrebljava za izvlačenje cevi i profila od plastičnih masa (tehn.).',
 'eksudat': 'Gnojna ili krvava tečnost koja se skuplja u telesnim dupljama usled zapaljenja maramica koje obavijaju te duplje; skupljanje tečnosti u organizmu (med.).',
 'ektoderm': 'Spoljni sloj na zametku; spoljni klicin list (biol., grč.).',
 'ekvilibrirati': 'Održati, održavati ravnotežu.',
 'ekvilibristika': 'Veština održavanja ravnoteže; izvođenje takve veštine, akrobatika.',
 'elaborirati': 'Podrobnije obraditi, razraditi, raščlaniti (elaborirati temu) (engl.).',
 'elastika': 'Elastična gumena vrpca.',
 'elegično': 'Setno, tužno (reći elegično).',
 'elegičnost': 'Osobina onoga koji je elegičan, onoga što je elegično; seta, tuga.',
 'električnost': 'Naelektrisanost, naelektrisanje (stepen električnosti).',
 'elektroakustika': 'Grana elektrotehnike koja se bavi pretvaranjem zvučnih titranja u električna i obrnuto.',
 'elektrodinamički': 'Koji se odnosi na elektrodinamiku.',
 'elektroencefalograf': 'Aparat za elektroencefalografiju (med.).',
 'elektroencefalogram': 'Grafički snimak bioelektrične struje u mozgu (med.).',
 'elektroenergetika': 'Nauka o iskorišćavanju električne energije; elektroprivreda.',
 'elektrofiltar': 'Uređaj za uklanjanje prašine iz industrijskih gasova koji deluje na principu privlačnih sila elektroda sa statičkim nabojem.',
 'elektrofor': 'Sprava za proizvodnju statičkog elektriciteta pomoću influencije (fiz.).',
 'elektrolitički': 'Koji se odnosi na elektrolizu i elektrolit (elektrolitička disocijacija, posuda).',
 'elektromehaničar': 'Stručnjak koji popravlja i održava električna postrojenja i električne uređaje, električar.',
 'elektrometalurg': 'Elektrometalurški radnik.',
 'elektroničar': 'Stručnjak za elektroniku, inženjer elektronike.',
 'elektrostatika': 'Grana nauke o elektricitetu koja proučava statički elektricitet i njegovo delovanje.',
 'elektroterapeut': 'Stručnjak za elektroterapiju (med.).',
 'elektrovod': 'Vod, sprovodnik električne struje, električna žica.',
 'elektročelik': 'Visokokvalitetni, specijalni čelik proizveden u električnoj industrijskoj peći.',
 'elementarnost': 'Osobina onoga što je elementarno; stihijska snaga, stihijnost.',
 'elipsoid': 'Ovalno, jajasto geometrijsko telo koje nastaje obrtanjem elipse oko jedne njene ose (mat.).',
 'elipsoidan': 'Koji ima oblik elipsoida (elipsoidna semenka).',
 'eliptičnost': 'Eliptičan, jajast oblik (eliptičnost zemlje); i eliptično izražavanje, sažetost (eliptičnost rečenice).',
 'elitnost': 'Osobina onoga koji je elitan, onoga što je elitno.',
 'emanatizam': 'Učenje istočnjačkih naroda o emanaciji (teol.).',
 'emancipator': 'Pobornik emancipacije.',
 'emanirati': 'Izbiti(ja)ti, izvirati, zračiti iz nečega; ispuštati, zračiti iz sebe (emanirati radost, strah); (emanirati se) izvirati, ispoljiti se, manifestovati se.',
 'emboličan': 'Koji ima emboliju (embolična arterija).',
 'embriolog': 'Stručnjak za embriologiju.',
 'emigrantkinja': 'Žena emigrant.',
 'eminentnost': 'Osobina onoga koji je eminentan, onoga što je eminentno.',
 'empiriokriticizam': 'Idealistički pravac nastao u drugoj polovini XIX veka; učenje po kome osnov saznanja predstavljaju subjektivni osećaji i doživljavanja (fil.).',
 'empiriokritičar': 'Pristalica empiriokriticizma.',
 'encefalogram': 'Snimak mozga dobijen encefalografijom (med.).',
 'enciklopedistički': 'Koji se odnosi na enciklopedizam i enciklopediste (enciklopedistički prikaz).',
 'enciklopedizam': 'Enciklopedijska obrazovanost, poznavanje više oblasti znanja; enciklopedijski način izlaganja; ist. napredni prosvetiteljski i filozofski pogledi francuskih enciklopedista iz XVIII veka.',
 'endemičnost': 'Osobina onoga što je endemično, postojanje endemije (endemičnost bolesti).',
 'endoderm': 'Sloj ćelija u unutrašnjosti biljnih organa, korena, stabla (bot.); zool. unutrašnji sloj ćelija gastrule višećelijskih životinja iz kog se razvijaju probavni organi, organi za disanje i žlezde s unutrašnjim lučenjem.',
 'endokard': 'Unutrašnja srčana opna (anat.).',
 'endokrinolog': 'Stručnjak koji se bavi endokrinologijom.',
 'endoplazma': 'Unutrašnji deo ćelije (biol.).',
 'endosperm': 'Rezervno hranljivo tkivo u semenkama koje služi za ishranu klice (bot.).',
 'energetičar': 'Stručnjak za energetiku; inženjer energetike.',
 'enervantno': 'Na enervantan način, razdražljivo (delovati enervantno).',
 'enkaustika': 'Tehnika slikanja bojama pomešanim s rastopljenim voskom (grč.).',
 'eol': 'Bog vetrova kod starih Grka (mit.).',
 'epifit': '(U množini) biljke koje žive na delovima drugih biljaka, ali ne uzimaju hranu od njih; (u jednini) takva biljka (bot.).',
 'epiglotis': 'Elastični hrskavičavi grkljanski poklopac (anat., grč.).',
}

C = {
 'com': 'glosa fragmentarna (isečak iz odrednice „čvor"); oblik nejasan, verovatno strana reč',
 'dente': 'glosa fragmentarna („dent, ~ uspeh"); značenje nejasno',
 'deši': 'glosa fragmentarna (isečak iz tuđe odrednice); značenje nejasno',
 'dici': 'glosa fragmentarna (isečak iz odrednice „roditi"); značenje nejasno',
 'dica': 'glosa fragmentarna (isečak iz odrednice „krupan"); značenje nejasno',
 'dili': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'dilom': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'diti': 'glosa fragmentarna (deo izraza); značenje nejasno',
 'dite': 'glosa fragmentarna (isečak); značenje nejasno',
 'dotakati': 'glagol; glosa OCR-nečitka, parnački oblik nejasan — nesigurno',
 'drkan': 'vulgarno (vulg. masturbirati); rečnik takve reči ne vodi',
 'drkati': 'vulgarno (vulg. masturbirati); rečnik takve reči ne vodi',
 'draščić': 'glosa pomešana (umanjenica + muškatno drvo); značenje nesigurno',
 'dražica': 'umanjenica; osnovna reč OCR-nečitka („drfla"?) — nesigurno',
 'dumnica': 'umanjenica i nežni oblik od „dumna"; osnovna reč nejasna — nesigurno',
 'biljarica': 'glosa upućuje na „biljar", ali naš rečnik vodi „biljar" kao igru kuglama; Matica osnovnu reč nema čitljivo — nesigurno',
 'Cveta': 'oblik ženskog imena Cveta; Matica ga ne vodi kao ime (samo kao oblik reči „cvet") — vlasnica odlučuje',
 'Cvetama': 'oblik imena Cveta; Matica ga ne vodi kao ime — vlasnica odlučuje',
 'Cvete': 'oblik imena Cveta; Matica ga ne vodi kao ime — vlasnica odlučuje',
 'Cveto': 'oblik imena (Cveta/Cveto); Matica ga ne vodi kao ime — vlasnica odlučuje',
 'Cvetom': 'oblik imena Cveta; Matica ga ne vodi kao ime — vlasnica odlučuje',
 'Cvetu': 'oblik imena Cveta; Matica ga ne vodi kao ime — vlasnica odlučuje',
 'cveto': 'verovatno vokativ muškog imena Cveto; Matica ne vodi — vlasnica odlučuje',
}

# Ručno izvedena objašnjenja (broje se u korpu A, ne B):
IZVEDENO = {
 'cvetama': 'Oblik reči cvet (lepi, šareni deo biljke iz kog kasnije nastaje plod ili seme).',
}
