# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 1651–1980 (monografski … patogeneza).

DEC = {
 'monografski': 'Koji se odnosi na monografiju (monografski rad).',
 'monopolistički': 'Koji se odnosi na monopolizam i monopoliste (monopolistička organizacija, sistem, udruženje).',
 'monopolizam': 'Sistem zasnovan na monopolu; monopol.',
 'monosaharid': 'Šećer najprostijeg sastava, koji sadrži šest ugljenikovih atoma u lancu, npr. glikoza, fruktoza (hem.).',
 'monosilabičan': 'Jednosložan (lingv.).',
 'montirač': 'Sprava, mašina za montiranje (montirač guma).',
 'monumentalnost': 'Osobina onoga što je monumentalno, onoga koji je monumentalan; masivnost, grandioznost, impozantnost; veličanstvenost.',
 'moralizator': 'Onaj koji morališe, moralizira, propoveda strogo poštovanje moralnih normi; uporedi moralist(a).',
 'morbile': 'Zarazna, virusna, obično dečja bolest s ospom, ospice; uporedi male boginje (med., množina).',
 'moreška': 'Ples, igra poreklom iz Španije, koja u tradicionalnim nošnjama prikazuje borbu mačevima između dve protivničke grupe (ital.).',
 'morfinizam': 'Hronično trovanje organizma izazvano dužim uzimanjem morfijuma.',
 'morfonološki': 'Koji se odnosi na morfonologiju; morfonološke alternacije — alternacije glasova na morfemskoj granici (lingv.).',
 'mostina': 'Uvećanica i pežorativ od most.',
 'motivisanost': 'Osobina onoga što je motivisano.',
 'motociklizam': 'Treniranje, vežbanje vožnje motociklom i takmičenje u vožnji motociklom kao sportska grana (sport).',
 'motonautika': 'Vožnja, odnosno takmičenje u vožnji motornim čamcima (sport).',
 'moćnost': 'Debljina rudnog, mineralnog ili uopšte zemljišnog sloja (geol.).',
 'močvarnost': 'Osobina, stanje onoga što je močvarno.',
 'mrazić': 'Umanjenica od mraz; slab mraz.',
 'mrazno': 'Kao mraz; kao na mrazu.',
 'mračak': 'Umanjenica i nežni oblik od mrak.',
 'mrežar': 'Ribar koji lovi ribu mrežom.',
 'mrežokrilac': '(U množini) red insekata sa dva para krila u kojima se vidi mrežasti splet žilica; (u jednini) takav insekt (zool.).',
 'mrkonja': 'Domaća životinja (mužjak) mrke dlake i ime takvoj životinji.',
 'mrkost': 'Osobina onoga što je mrko, tamno, mrka boja; i namrođenost, namrštenost.',
 'mrkulja': 'Krava mrke dlake i ime takvoj kravi.',
 'mrvičast': 'Koji se lako mrvi, trošan, drobljiv; koji je u mrvicama; uporedi mrvast.',
 'mršavac': 'Mršav muškarac, mršavko.',
 'mršo': 'Mršav muškarac; uporedi mrša.',
 'muhamedanstvo': 'Monoteistička religija koju je osnovao Muhamed, muslimanska vera, islam.',
 'municipalan': 'Koji se odnosi na municipije (municipalna vlast, prava, uprava) (lat.).',
 'munjevitost': 'Osobina onoga što je munjevito.',
 'mutnina': 'Mutnoća, mutnilo; i ono što muti, zamućuje neku tečnost; mutna, zamućena tečnost.',
 'mutnoća': 'Osobina i stanje onoga što je mutno, zamućeno; zamućenost, mutnilo, mutnina; i čestice koje su zamutile neku tečnost, mutnina, mutež.',
 'muzar': 'Onaj koji muze stoku, koji se bavi mužom.',
 'muzilica': 'Uređaj za mužu krava.',
 'muzni': 'Koji se muze, koji daje mleko (o kravi, ovci, kozi, o bravu uopšte).',
 'mučiteljica': 'Ona koja muči, zlostavlja, kinži; i ono što zadaje muke, uzrokuje bol, patnju (o reči ženskog roda).',
 'mučnjak': 'Sanduk u vodenici u koji pri mlevenju pada brašno sa žrvnja.',
 'mušičavost': 'Osobina onoga koji je mušičav, nastranost, hirovitost, ćudljivost.',
 'muškinje': '(Zbirno, množina) muške osobe jedne porodice, nekog skupa i sl., muške osobe uopšte; uporedi ženskinje.',
 'nabacanost': 'Osobina i stanje onoga što je nabacano, nepovezano, bez reda i sistema (obično o umetničkom, naučnom i sl. delu).',
 'nabreklost': 'Osobina i stanje onoga što je nabreklo.',
 'nabuhlost': 'Stanje onoga koji je nabuhao, onoga što je nabuhlo.',
 'nacifašizam': 'Nacistička verzija fašizma, nacional socijalizam, nacizam; i nacizam i fašizam shvaćeni kao jedinstvo (pol.).',
 'nadahnutost': 'Osobina i stanje onoga koji je nadahnut, onoga što je nadahnuto; nadahnuće.',
 'nadebljati': 'Postati deblji, dobiti zadebljanje, odebljati (obično o jeziku, dlanovima, koži).',
 'nadgrađivati': 'Nesvršeni oblik glagola „nadgraditi".',
 'nadgrobnica': 'Kamena ili betonska ploča na grobu.',
 'nadigravati': 'Nesvršeni oblik glagola „nadigrati"; (nadigravati se) takmičiti se u igri, plesu i sl.; preneseno: nadmudrivati se, varati se, obmanjivati se.',
 'nadir': 'Tačka zamišljena u središtu nevidljive strane nebeske sfere nasuprot zenitu (astr.); preneseno: najniža tačka, najniži stepen neke osobine, sposobnosti i sl. (ar.).',
 'nadisati': '(Nadisati se) udahnuti dovoljno, zasititi se udišući (obično svež, čist vazduh, miris i sl.).',
 'nadletati': 'Nesvršeni oblik glagola „nadleteti"; (nadletati se) takmičiti se, nadmetati se u letenju.',
 'nadmašiv': 'Koji se može nadmašiti, prevazići; uporedi nenadmašiv.',
 'nadnaravnost': 'Osobina onoga koji je nadnaravan, onoga što je nadnaravno, natprirodno, natprirodnost.',
 'nadničariti': 'Raditi kao nadničar, nadničiti.',
 'nadomešćivati': 'Nesvršeni oblik glagola „nadomestiti".',
 'nadoplata': 'Dodatno plaćanje, naknadna doplata.',
 'nadopunjavati': 'Nesvršeni oblik glagola „nadopuniti"; (nadopunjavati se) međusobno se dopunjavati.',
 'nadozidati': 'Naknadno podići, dozidati nešto na podignutoj građevini ili uz nju, nadgraditi.',
 'nadrastati': 'Nesvršeni oblik glagola „nadrasti".',
 'nadraženost': 'Stanje onoga što je nadraženo, onoga koji je nadražen; uzbuđenost.',
 'nadražljivac': '(Obično u množini) naziv za neke vrste kratkotrajnih bojnih otrova, gasova, koji nadražuju sluzokožu nosa ili očiju i izazivaju kijanje ili suzenje (hem., voj.).',
 'nadripisar': 'Nestručno lice koje se, za novčanu ili drugu nagradu, bavi pisanjem molbi, žalbi, tužbi i sl.; koje drugima piše predstavke, popunjava formulare itd.',
 'nadripolitičar': 'Nesposoban, slab, loš političar; uporedi politikant.',
 'naglasni': 'Koji se odnosi na naglasak, akcenatski (lingv.).',
 'naglašenost': 'Osobina onoga što je naglašeno; lingv. položaj pod naglaskom, akcentovanost; i naglašavanje, isticanje, upadljivost, uočljivost.',
 'nagutati': '(Nagutati se) mnogo progutati (nagutati se vode); udahnuti mnogo, obično više puta (nagutati se prašine); preneseno: doživeti, pretrpeti mnogo neprijatnosti (nagutati se straha).',
 'nahođenje': 'Glagolska imenica od nahoditi (se); i mišljenje, sud, stav, shvatanje (raditi po svom nahođenju).',
 'nahrliti': 'Doći, pojaviti se hrleći, navaliti, pohrliti.',
 'nakalemljivati': 'Nesvršeni oblik glagola „nakalemiti".',
 'nakrcati': 'Krcajući pripremiti neku, obično veću ili dovoljnu količinu (naročito oraha, lešnika i sl.).',
 'nalogodavac': 'Lice koje izdaje naloge — blagajni za isplatu novca, knjigovodstvu za knjiženje, prenos i sl. (adm.); i organ nekog preduzeća, ustanove i dr. u čije ime se izdaju nalozi.',
 'namrviti': 'Isitniti, izdrobiti u mrve, izmrviti u nekoj, obično većoj ili dovoljnoj količini: namrvi pilićima hljeba!',
 'namrštenost': 'Osobina i stanje onoga koji je namršten, onoga što je namršteno, namrođenost.',
 'naobražen': 'Obrazovan; uporedi naobrazovan.',
 'napaljivati': 'Nesvršeni oblik glagola „napaliti".',
 'napasno': 'Agresivno, nasrtljivo, napadno; nametljivo.',
 'napaćenost': 'Stanje onoga koji je napaćen, izmučenost; uporedi patnja.',
 'naprednost': 'Osobina, stanje onoga koji je napredan, onoga što je napredno; uporedi progresivnost.',
 'naputovati': '(Naputovati se) provesti dosta vremena u putovanju, mnogo proputovati; zadovoljiti se, zasititi se putovanja.',
 'narendati': 'Isitniti na rendetu, ribežu, trenici i sl. (jabuke, roškve i sl.).',
 'narodnjaštvo': 'Društveno-politički pokret narodnjaka koji teži povezivanju vlasti, stranaka, intelektualne elite i dr. s narodom; ideje i duh narodnjaka; privrženost narodnjačkim idejama i težnjama.',
 'narteks': 'Prednji deo, predvorje crkve, priprata (arhitektura, grč.).',
 'naručnik': 'Deo odeće katoličkih sveštenika koji se za vreme mise stavlja na ruku od lakta do šake; uporedi narukavlje (crkv.).',
 'narušenje': 'Poremećaj, kvarenje, kršenje, narušavanje (obično nekih odnosa i sl.).',
 'nasisati': '(Nasisati se) zasititi se sisanjem, nahraniti se sisajući — iz dojke ili vimena; o pijavicama: krv iz tuđeg tela; o pčelama, leptirima: sok, tečnost iz nečega.',
 'naskakati': '(Naskakati se) zadovoljiti se, zasititi se skakanja, iskakati se.',
 'nastanjenost': 'Osobina i stanje nečega što je nastanjeno, naseljeno; naseljenost.',
 'natakati': 'Nesvršeni oblik glagola „natočiti".',
 'natiskati': 'Natrpati, nazbijati, nabiti; napuniti tiskajući (natiskati torbe); i sterati, sabiti (natiskati zatvorenike u ćeliju); (natiskati se) skupiti se u gustu gomilu, zbiti se.',
 'natkrivati': 'Nesvršeni oblik glagola „natkriti".',
 'natprosečan': 'Koji je iznad prosečnog, običnog; uporedi izuzetan (natprosečna veličina, vrednost, kvalitet, lepota, rezultat, čovek, talenat).',
 'natrgati': 'Nabirati trgajući, kidajući, nakidati (cveća, lišća, plodova, granja i sl.).',
 'natruha': 'Primesa, nanos stranih elemenata u nečemu; strani, tuđi uticaj u nečemu.',
 'natrčavati': 'Nesvršeni oblik glagola „natrčati".',
 'naturizam': 'Sunčanje i kupanje na javnim plažama bez kupaćih kostima ili gaćica; pokret koji propagira kult gologa ljudskog tela i neodevanje, nudizam.',
 'navezati': 'Zavezivanjem spojiti dva kraja, privezati jedan kraj za drugi, nadovezati (navezati isprekidane žice, konac); i vezujući pričvrstiti uz nešto, spojiti s nečim (navezati na kanap); (navezati se) nadovezati se.',
 'naveštavati': 'Nesvršeni oblik glagola „navestiti"; (naveštavati se) pojavljivati se, najavljivati se, pokazivati se.',
 'navešćivati': 'Nesvršeni oblik glagola „navestiti"; uporedi naveštavati.',
 'navitak': 'Pređa (konac i sl.) navijena na vratilo; i spleteno predivo, vlasi kudelje ili lana; povesmo.',
 'navlas': 'Do najmanje pojedinosti, potpuno, sasvim (navlas isto).',
 'navodniti': 'Zaliti, natopiti vodom, poljoprivredno zemljište; (navodniti se, o očima) ovlažiti se, okvasiti se suzama.',
 'navoziti': 'Vozeći nanositi, dovoziti na nešto (navoziti đubre na njive); (navoziti se) počinjati plovidbu, polaziti na plovidbu rekom, morem i sl.',
 'nazalnost': 'Nazalni karakter glasova; nazalni, nosni izgovor.',
 'nazdravica': 'Isto što i zdravica; preneseno: prazan, retoričan govor, besadržajan niz reči, fraza.',
 'nazdravičar': 'Zdravičar; preneseno: onaj koji drži praznorečive, besadržajne, hvalisave govore, frazer.',
 'naznačavati': 'Nesvršeni oblik glagola „naznačiti".',
 'nazubiti': 'Učiniti da nešto postane zupčasto, da ima zupce (kao na srpu, testeri); naoštriti zupce (nazubljeno sečivo).',
 'načelnikovati': 'Biti načelnik, biti na dužnosti, položaju načelnika; uporedi načelnik.',
 'nažuljati': 'Pritiskanjem, trenjem, trljanjem i sl. odvojiti pokožicu od donjeg sloja kože, izuljati (na nekom delu tela).',
 'neadekvatnost': 'Osobina ili stanje onoga što je neadekvatno.',
 'neatraktivan': 'Neprivlačan, nezanimljiv, neinteresantan (neatraktivan program).',
 'nebitnost': 'Osobina onoga što nije bitno; ono što nije bitno, nevažnost.',
 'neborac': 'Onaj koji nije borac; onaj koji nije sposoban da bude borac; i vojnik koji obavlja pomoćne poslove izvan borbene linije (voj.).',
 'nedefinisan': 'Čija se suština ne može definisati, neodređen.',
 'nedisciplina': 'Nepokoravanje određenim pravilima; kršenje uobičajenih normi, neposlušnost.',
 'nedodirljivost': 'Osobina onoga što je nedodirljivo, neprikosnovenost, nepovredivost.',
 'nedohvatljivo': 'Neuhvatljivo, nedostižno.',
 'nedokazanost': 'Osobina onoga što je nedokazano, nepotvrđenost.',
 'nedokučivost': 'Osobina onoga što je nedokučivo, neobjašnjivost; i nedostižnost, nepristupačnost.',
 'nedopustivost': 'Osobina onoga što je nedopustivo, neprihvatljivost.',
 'nedopuštenost': 'Nepriznato pravo na nešto, neprihvatljivost; zabrana.',
 'nedorečenost': 'Osobina onoga što nije izraženo do kraja, nepotpunost izraza.',
 'nedvosmislenost': 'Osobina onoga što je nedvosmisleno, jasnost.',
 'nefritis': 'Zapaljenje bubrega (med., grč.).',
 'negostoljubivost': 'Osobina onoga koji je negostoljubiv, onoga što je negostoljubivo; neljubazno ponašanje prema gostima.',
 'neiscrpnost': 'Osobina onoga što je neiscrpno, neiscrpljivost.',
 'neishranjenost': 'Osobina, stanje onoga koji je neishranjen, mršavost.',
 'neispavanost': 'Stanje onoga koji je neispavan, koji se nije naspavao.',
 'neizdrživost': 'Nemogućnost da se nešto izdrži, podnese.',
 'neizvedivost': 'Osobina onoga što je neizvedivo, neizvodljivost.',
 'neizveštačenost': 'Osobina onoga koji je neizveštačen, prirodnost.',
 'neiživljenost': 'Osobina, stanje onoga koji je neiživljen, onoga što je neiživljeno.',
 'nekamo': 'Nekuda, u nekom pravcu.',
 'nekompetentnost': 'Osobina onoga koji je nekompetentan, onoga što je nekompetentno.',
 'nekonformistički': 'Koji se odnosi na nekonformizam i nekonformiste (nekonformistički duh).',
 'nekorektnost': 'Osobina onoga koji je nekorektan, onoga što je nekorektno; i ono što je nekorektno.',
 'nekritičnost': 'Osobina onoga koji je nekritičan, onoga što je nekritično.',
 'nekultura': 'Nizak nivo duhovnog, civilizacijskog razvoja, obrazovanosti, prosvećenosti; kulturna zaostalost, primitivizam.',
 'nekurentan': 'Koji se slabo prodaje, koji ima lošu prođu (nekurentna roba).',
 'nelikvidnost': 'Svojstvo onoga što je nelikvidno; nesolventnost.',
 'nematoda': '(U množini) paraziti iz razreda nematoda koji žive u telu čoveka, životinje i na biljkama; (u jednini) parazit iz tog razreda (zool.).',
 'nemeti': 'Postajati nem, gubiti moć govora; pesnički: postajati nečujan, stišavati se, tihnuti; zamirati.',
 'nemusliman': 'Čovek koji nije muslimanske veroispovesti.',
 'nenadmašivo': 'Na nenadmašan način, da se ne može nadmašiti; izuzetno, izvanredno.',
 'nenadoknadivost': 'Osobina onoga što je nenadoknadivo, onoga koji je nenadoknadiv.',
 'neobazrivost': 'Osobina onoga koji se ne obazire na nešto; neopreznost; neuviđavnost.',
 'neoborivost': 'Osobina onoga što je neoborivo, onoga koji je neoboriv.',
 'neodrživost': 'Osobina, stanje onoga što je neodrživo.',
 'neoklasicizam': 'Pravac u umetnosti druge polovine XVIII i prve polovine XIX veka, koji se odlikuje ugledanjem na dela klasične, antičke kulture i klasicizma.',
 'neopisivost': 'Osobina onoga što je neopisivo, onoga koji je neopisiv.',
 'neopravdanost': 'Osobina onoga što se ne može opravdati, neosnovanost.',
 'nepobedivost': 'Osobina onoga koji je nepobediv.',
 'nepobitnost': 'Osobina onoga što je nepobitno.',
 'nepomućenost': 'Stanje, osobina onoga što je nepomućeno; bistrina, jasnoća.',
 'nepopravljivost': 'Stanje, osobina onoga koji je nepopravljiv, onoga što je nepopravljivo.',
 'nepouzdanje': 'Osećanje nepoverenja, neverice, sumnje; i obeshrabrenost, malodušnost.',
 'nepovratnost': 'Osobina onoga što je nepovratno.',
 'nepoznatost': 'Osobina onoga što je nepoznato.',
 'nepraktičnost': 'Osobina ili stanje onoga koji je nepraktičan, onoga što je nepraktično.',
 'nepreciznost': 'Osobina onoga koji je neprecizan, onoga što je neprecizno.',
 'neprekidnost': 'Osobina, stanje onoga što je neprekidno.',
 'neprelaznost': 'Osobina onoga što je neprelazno, onoga koji je neprelazan.',
 'nepremostivost': 'Osobina ili stanje onoga što je nepremostivo.',
 'neprikriveno': 'Na neprikriven način, neskriveno, otvoreno (neprikriveno pretiti, smejati se).',
 'neprilagodljivost': 'Osobina onoga koji je neprilagodljiv.',
 'neprilagođenost': 'Osobina onoga koji nije prilagođen, onoga što je neprilagođeno.',
 'neprimenljiv': 'Koji se ne može primeniti (u praksi), neodgovarajući, neupotrebljiv.',
 'neracionalnost': 'Osobina, svojstvo onoga što je neracionalno.',
 'neravnopravnost': 'Stanje, položaj onoga koji je neravnopravan; podređen položaj, status.',
 'nerazdeljivost': 'Osobina ili stanje onoga što je nerazdeljivo.',
 'nerazgovetnost': 'Osobina onoga što je nerazgovetno.',
 'nerazlučivo': 'Tako da se ne može razlučiti, nerazdvojno.',
 'neregularnost': 'Osobina onoga što je neregularno, nepravilnost.',
 'nerentabilnost': 'Osobina, stanje onoga što je nerentabilno.',
 'nesabranost': 'Osobina, stanje onoga koji je nesabran; nesređenost, rasejanost.',
 'nesan': 'Nespavanje; nesanica (zamoren od nesna, patiti od nesna).',
 'nesistematičan': 'Koji se ne odlikuje sistematičnošću, koji nije sistematičan.',
 'neskromnost': 'Osobina onoga koji je neskroman, onoga što je neskromno.',
 'nesolidnost': 'Osobina onoga koji je nesolidan, onoga što je nesolidno; ono što je nesolidno.',
 'nestranački': 'Koji nije u vezi sa političkim strankama, koji se ne odnosi na političke stranke.',
 'netaknutost': 'Osobina, stanje onoga što je netaknuto, onoga koji je netaknut; nedirnutost.',
 'neuništivost': 'Osobina onoga koji je neuništiv, onoga što je neuništivo.',
 'neustavnost': 'Osobina, stanje onoga što je neustavno.',
 'neuverljivost': 'Osobina onoga koji je neuverljiv, onoga što je neuverljivo.',
 'nevisoko': 'Na maloj visini.',
 'nevoljkost': 'Neraspoloženje, neljubnost; odbojnost, antipatija; i odsustvo volje da se nešto učini.',
 'nevrednost': 'Bezvrednost, beznačajnost; ono što je bez vrednosti.',
 'nezadrživost': 'Osobina onoga koji je nezadrživ, onoga što je nezadrživo.',
 'nezaobilazan': 'Koji se ne sme zanemariti, s kojim se mora računati (nezaobilazno pitanje).',
 'nezgrapnost': 'Osobina onoga koji je nezgrapan, onoga što je nezgrapno; nespretnost, neskladnost.',
 'nikamo': '(U odričnim rečenicama) ni u koje mesto, ni na koje mesto, nigde; ni u kojem pravcu, nikojim putem, nikuda.',
 'niklen': 'Koji je od nikla, prevučen niklom.',
 'nikoliko': 'Odričan odgovor na pitanje „koliko": ni u kojoj meri, nimalo; i nijedan, ništa (koliko si se obradovala? — nikoliko).',
 'niskokaloričan': 'Koji ima malo kalorija (niskokalorična hrana).',
 'niskopodni': 'Koji je niskog poda (niskopodni autobus).',
 'nokdaun': 'Snažan udarac koji omamljuje i obara nazemlju, ali bokser ipak može da nastavi borbu pre isteka vremena od deset sekundi (sport, engl.).',
 'noktić': 'Umanjenica i nežni oblik od nokat.',
 'nominala': 'Vrednost naznačena na različitim vrednosnim papirima, nominalna vrednost (bank., fin., lat.).',
 'nominalizam': 'Srednjovekovno skolastičko filozofsko učenje po kojem nisu primarne opšte ideje, već su realno postojeće samo pojedinačne stvari (fil.); ekon. shvatanje po kojem vrednost novca ostaje uvek jednaka bez obzira na njegovu stvarnu kupovnu moć.',
 'nonkonformizam': 'Neslaganje s vladajućim religioznim, političkim ili drugim shvatanjem (lat.).',
 'nonšalantnost': 'Neusiljenost, ležernost; nemar, bezbrižnost, ravnodušnost.',
 'nosina': 'Uvećanica i pežorativ od nos.',
 'noveleta': 'Kratka novela, novelica (fr.).',
 'novelistika': 'Novelistička književnost.',
 'novinarčić': 'Umanjenica od novinar.',
 'obadati': 'Nesvršeni oblik glagola „obosti".',
 'obelodanjivati': 'Nesvršeni oblik glagola „obelodaniti".',
 'obespravljenost': 'Stanje onoga koji je obespravljen.',
 'obeščašćenje': 'Uvreda časti, poniženje.',
 'obliznuti': 'Liznuti unaokolo; (obliznuti se) liznuti svoje usne.',
 'obljubljenost': 'Osobina, stanje onoga koji je obljubljen, onoga što je obljubljeno; omiljenost, popularnost.',
 'oblost': 'Osobina onoga što je oblo.',
 'obrubljivati': 'Nesvršeni oblik glagola „obrubiti".',
 'obuhvatnost': 'Osobina onoga što je obuhvatno, potpunost.',
 'odabranik': 'Onaj koji je izabran između drugih, izabranik.',
 'odaslanica': 'Ženska osoba odaslanik.',
 'odgađati': 'Nesvršeni oblik glagola „odgoditi".',
 'odgrizak': 'Odgrizen komad, zalogaj.',
 'odlakaviti': 'Postati dlakav, obrasti dlakama.',
 'odrapiti': 'Snažno udariti, ogalamiti, raspaliti nekoga (razg.); i isuviše mnogo naplatiti nekome nešto, odmeriti, izreći nekome previsoku kaznu; i kazati odrešito, bez okolišenja, drsko odgovoriti.',
 'odredski': 'Koji se odnosi na odred (odredska bolnica, zastava).',
 'odrezivati': 'Nesvršeni oblik glagola „odrezati".',
 'odrubljivati': 'Nesvršeni oblik glagola „odrubiti".',
 'odsanjati': 'Završiti sa sanjanjem; prestati sanjati o nečemu (odsanjati snove, želje).',
 'odsluživati': 'Nesvršeni oblik glagola „odslužiti".',
 'odvagati': 'Odmeriti vagom; preneseno: razmotriti i prosuditi, odrediti, presuditi (tačno, nepristrasno).',
 'odvagivati': 'Nesvršeni oblik glagola „odvagati" i „odvagnuti".',
 'odvodnjavati': 'Vršiti, sprovoditi odvođenje (suvišne) vode sa močvarnog zemljišta, isušivati takvo zemljište; uporedi melioracija.',
 'odšuteti': 'Ćutati, prećutati, ne reći.',
 'oformljenje': 'Uobličavanje, utvrđivanje završnog izgleda, oblika, sadržine i dr.; osnivanje, ustrojavanje, formiranje nečega.',
 'ogoljavati': 'Nesvršeni oblik glagola „ogoleti" i „ogoliti".',
 'okomica': 'Vertikala; strmina (uzbrdica ili nizbrdica).',
 'okoštanje': 'Stvaranje, obrazovanje koštanog tkiva, koštanog zadebljanja i sl., kao posledica patoloških, degenerativnih procesa.',
 'okrutnica': 'Okrutna ženska osoba.',
 'okupiranost': 'Stanje, položaj onoga što je okupirano, onoga koji je okupiran.',
 'olovan': 'Načinjen od olova, koji u svom sastavu ima olova (olovni vojnici, legura, cev); preneseno: siv, tmuran, sumoran (olovan dan, nebo).',
 'omamljivo': 'Omamljujuće, zanosno, opojno, opijajuće (ruža miriše omamljivo).',
 'omekšanje': 'Gubitak čvrstine; razmekšano mesto (tkiva, materijala i sl.).',
 'omofor': 'Deo odežde pravoslavnog arhijereja, sa otvorom za glavu, koji se nosi preko oba ramena; uporedi naramnica (crkv., grč.).',
 'omogućavati': 'Nesvršeni oblik glagola „omogućiti".',
 'omraženost': 'Stanje onoga koji je omražen, onoga što je omraženo, omrznuto; prezrenost.',
 'onemogućavati': 'Nesvršeni oblik glagola „onemogućiti".',
 'onesposobljavati': 'Nesvršeni oblik glagola „onesposobiti".',
 'onolicki': 'Onoliko majušan — kao ono na šta se pokazuje, čime se upoređuje; onako mali (on je onolicki kao moj sin; onolicni grad, a pun sveta).',
 'onomastika': 'Grana lingvistike koja se bavi proučavanjem vlastitih imena (grč.).',
 'operativnost': 'Sposobnost za preduzimanje, izvršavanje zadataka u praksi, praktičnost.',
 'opisivač': 'Onaj koji opisuje, prikazuje opisom (nekoga, nešto).',
 'opnica': 'Umanjenica od opna.',
 'oporavilište': 'Ustanova, mesto za oporavak posle bolesti, lečilište, odmaralište.',
 'oprašivati': 'Nesvršeni oblik glagola „oprašiti".',
 'opsežnost': 'Obimnost, opširnost.',
 'opskrbni': 'Koji se odnosi na opskrbu, snabdevački (opskrbna stanica, odeljenje).',
 'opsluživati': 'Nesvršeni oblik glagola „opslužiti".',
 'opunomoćitelj': 'Onaj koji daje punomoć, opunomoćava nekoga.',
 'opustošenost': 'Stanje onoga koji je opustošen, onoga što je opustošeno.',
 'orguljati': 'Svirati na orguljama.',
 'ornamentalan': 'Koji se odnosi na ornamente i ornamentiku, ukrasni, dekorativan (ornamentalna plastika, slova).',
 'oročavati': 'Nesvršeni oblik glagola „oročiti".',
 'osamdesetak': 'Oko osamdeset, približno osamdeset.',
 'osamdesetogodišnjak': 'Muška osoba od osamdeset godina.',
 'osamljivati': '(Osamljivati se) nesvršeni oblik glagola „osamiti (se)".',
 'osavremenjivati': 'Nesvršeni oblik glagola „osavremeniti".',
 'oscilogram': 'Grafički crtež dobijen pomoću oscilografa (fiz., grč.).',
 'osiguranica': 'Ženska osoba osiguranik.',
 'oskvrnjenje': 'Oskvrnavljenje.',
 'oslabljivati': 'Nesvršeni oblik glagola „oslabiti".',
 'ostrašćenost': 'Stanje, svojstvo onoga koji je ostrašćen, onoga što je ostrašćeno.',
 'osveštavati': 'Nesvršeni oblik glagola „osveštati".',
 'otegliti': 'Odvući tegljenjem (otegliti podmornicu).',
 'otečenost': 'Stanje onoga što je otečeno, natečenost, nabreklost.',
 'otkivak': 'Metalni predmet dobijen kovanjem.',
 'otklimati': 'Obići, udaljiti se klimajući (se), ospetati se.',
 'otklizati': 'Izvesti do kraja klizanje, klizanjem završiti, ispuniti nešto (otklizati svoj sat, valcer na ledu).',
 'otkupljivač': 'Onaj koji otkupljuje, vrši otkup.',
 'otočanka': 'Stanovnica otoka, ona koja je poreklom sa otoka.',
 'otpravljati': 'Nesvršeni oblik glagola „otpraviti".',
 'otresitost': 'Osobina onoga koji je otresit.',
 'otvrdnjavati': 'Nesvršeni oblik glagola „otvrdnuti".',
 'ovisok': 'Dosta, prilično visok, povisok.',
 'ovnić': 'Umanjenica od ovan.',
 'ozakonjenje': 'Utvrđivanje, regulisanje zakonom; proglašavanje nečega zakonitim, davanje čemu zakonsku snagu, pravnu osnovu.',
 'ozdravljati': 'Postepeno se izlečivati, postajati sve manje bolestan, isceljivati se.',
 'ozračenost': 'Stanje onoga koji je ozračen, onoga što je ozračeno; količina, stepen primljenog radioaktivnog ili dr. zračenja.',
 'očitost': 'Svojstvo onoga što je očito, što je očigledno, nesumnjivo.',
 'oživotvorenje': 'Ostvarenje, realizacija; oličenje.',
 'paf': 'Uzvik: označava zvuk koji se čuje pri snažnom udaru ili pucnju (onom.); „biti paf" — ostati bez reči, šokirati se od kakvog iznenađenja, čuda (razg.).',
 'palir': 'Nadzornik nad zidarima i radnicima na građevini, građevinski poslovođa (nem.).',
 'palisandrovina': 'Plemenita vrsta drveta ljubičastosmeđe boje koja se upotrebljava za fine stolarske radove i muzičke instrumente.',
 'panarabizam': 'Težnja za ujedinjenjem, saradnjom svih Arapa (pol.).',
 'panegiričar': 'Onaj koji piše panegirike ili drži panegirične govore.',
 'pangermanizam': 'Pokret za ujedinjenje svih Nemaca, germanskih naroda (pol.).',
 'panjina': 'Uvećanica i pežorativ od panj.',
 'panslavizam': 'Ideja, težnja za kulturnim i političkim zbližavanjem i ujedinjenjem svih slovenskih naroda, veslovenstvo (pol.).',
 'papati': 'Jesti (dečje).',
 'papica': 'Hrana, jelo (dečje, u umanjenom i nežnom značenju).',
 'papratnjača': '(U množini) velika grupa beskvetnica sa jako rasečenim ili složenim listovima; (u jednini) beskvetnica iz te grupe (bot.).',
 'parafrazirati': 'Izložiti, izlagati neku već kazanu ili napisanu misao, izreku, frazu i sl. svojim rečima, prepričavajući.',
 'paralaksa': 'Ugao pod kojim se vidi prividna promena mesta nekog tela zbog promene mesta s kojeg se telo posmatra; ugao koji nastaje kada se neko telo posmatra s dve različite tačke (astr., grč.).',
 'parangal': 'Naprava za ribolov u obliku dugačke vrpce na kojoj su jedna za drugom privezane udice (rib., ital.).',
 'parazitizam': 'Pojava, način na koji se paraziti održavaju u životu (biol.); preneseno: život na tuđ račun, paraziterstvo.',
 'parkirališni': 'Koji se odnosi na parkiralište i parkiranje, koji služi za parkiranje (parkirališni prostor).',
 'parkić': 'Umanjenica i nežni oblik od park.',
 'parlamentaran': 'Koji se odnosi na parlament, koji je u vezi s parlamentom (parlamentarni izbori, debata); „biti parlamentaran" — dopustiti i drugome da govori neometano, strpljivo saslušati, ne prekidati drugoga.',
 'parlamentarnost': 'Parlamentarno uređenje države, političko svojstvo tako uređene države; osobina onoga koji je parlamentaran.',
 'participirati': 'Učestvovati, sudelovati, obično u nekom finansijskom poslu.',
 'partikularan': 'Delimičan; poseban, zaseban, pojedinačan (partikularni interesi).',
 'pasatni': 'Koji se odnosi na pasate (pasatni vetrovi).',
 'pasivac': 'Homoseksualac koji u polnom odnosu s drugim homoseksualcem ima ulogu žene.',
 'pastila': '(Obično u množini) lek, obično za grlo, u obliku pilule ili pločice (lat.).',
 'patarice': '(Množina) drugi dan slave, krsnog imena i sl.',
 'pater': 'Katolički sveštenik, redovnik (lat.).',
 'paternalizam': 'Pokroviteljski, zaštitnički stav, držanje, ponašanje (obično lažno) poslodavaca prema radnicima, velike sile prema maloj državi, federacije prema članicama federacije i dr. (pol.).',
 'patogeneza': 'Postanak i tok bolesti (med., grč.).',
}

C = {
 'moškom': 'glosa fragmentarna (deo odrednice „tresti"); značenje nejasno',
 'mudo': 'gruba, razgovorna reč za mušku polnu žlezdu; sajt ima dečji režim — vlasnica odlučuje',
 'muskardina': 'glosa samo uput na „krečavica" — osnovna reč nije u našem rečniku, značenje nesigurno',
 'nadžupnik': 'nije u Matici (ni fuzzy); značenje nesigurno (nad- + župnik?)',
 'nenaglašeno': 'glosa pogrešno uhvaćena (tuđa odrednica); značenje nejasno',
 'neru': 'glosa fragmentarna; značenje nejasno',
 'neši': 'glosa fragmentarna; značenje nejasno',
 'nice': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'nici': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'nicu': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'nou': 'glosa fragmentarna; značenje nejasno',
 'nuo': 'glagolski oblik; u Matici samo unutar glosa — značenje nejasno',
 'nuši': 'glosa fragmentarna (deo odrednice „promaći"); značenje nejasno',
 'oksidaciono': 'oblik prideva (oksidaciono sredstvo); samostalna odrednica nije potvrđena — nesigurno',
 'ošići': 'glosa fragmentarna (deo odrednice „svratiti"); značenje nejasno',
 'patkova': 'oblik može biti i od „patak" i od prideva „patkov"; dodela nesigurna',
}
