# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 3631–3776 (Čuća … žučovod) + zaglavlja/isečci rešeni
# dodatnim python prolazom kroz normalizovane redove Matice (zaderati, čekač, ...).

DEC = {
 'čvaknuti': 'Svršeni oblik glagola „čvakati".',
 'đakonstvo': 'Đakonski čin; i đakonska dužnost, služba.',
 'šafranski': 'Koji se odnosi na šafran (šafranska boja).',
 'šalica': 'Umanjenica i nežni oblik od šala.',
 'šalina': 'Uvećanica i pežorativ od šal.',
 'šalić': 'Umanjenica i nežni oblik od šal.',
 'šalvarice': 'Umanjenica od šalvare (množina).',
 'šantung': 'Vrsta tkanine neravne površine od sirove kineske svile, po istoimenoj kineskoj pokrajini.',
 'šančić': 'Umanjenica od šanac.',
 'šarin': 'Šaren konj, šarac.',
 'šatorast': 'Koji ima oblik šatora (šatorasto brdo).',
 'šatorić': 'Umanjenica od šator.',
 'šaška': 'Vrsta skakavca koji se kreće u jatima (zool.); „egipatska šaška" — vrsta skakavca koja povremeno u velikim jatima opustoši sve zelene površine u severnoj Africi.',
 'šeikat': 'Oblast kojom vlada šeik.',
 'šekspirski': 'Koji se odnosi na Šekspira; šekspirovski (šekspirski stil).',
 'šepavac': 'Šepav muškarac, hromac, ćopavac.',
 'šepavost': 'Osobina i stanje onoga koji je šepav, hromost, ćopavost.',
 'šepesati': 'Tetati se u hodu; malo šepati.',
 'šeprtljav': 'Nespretan, neumešan; i smešan, zbunjen.',
 'šeprtljavost': 'Osobina onoga koji je šeprtljav.',
 'šepurina': 'Okrnjeni klip kukuruza, okomak, kočanj; i peteljka grozda; ostatak grozda sa koga su skinuta zrna.',
 'šesnaestinka': 'Šesnaestina cele note (muz.).',
 'šetnica': 'Staza za šetnju; šetalište.',
 'ševin': 'Koji pripada ševi, koji se odnosi na ševu (ševin glas).',
 'šezdesetogodišnjica': 'Navršena šezdeseta godina od nekog događaja, proslava ili pomen posle šezdeset godina.',
 'šic': 'Uzvik za teranje mačaka.',
 'šimi': 'Vrsta američkog plesa sličnog fokstrotu (engl.).',
 'šimširov': 'Koji se odnosi na šimšir, koji je od šimšira (šimširovo lišće, grana, sedlo).',
 'šimširovina': 'Šimširovo drvo (kao građa).',
 'šironja': 'Čovek širokih pleća, ramena, plećaš čovek; ugojen čovek nižeg rasta, dežmekast, zdepast čovek; i vo široko razmaknutih rogova.',
 'šivačica': 'Radnica koja šije, švalja, krojačica.',
 'šišnuti': 'Zašištati; zasiktati (šišnuti kroz nos, kroz zube) (onom.).',
 'šištavost': 'Osobina onoga što je šištavo (šištavost glasa).',
 'šišulja': 'Vrsta pšenice bez osja na klasu, golija (agr.).',
 'škarice': '(Množina) porodica insekata dvokrilaca čije ženke polažu jaja u cvet i list izazivajući stvaranje kvržastih izraslina — šišarica, šiški (zool.).',
 'škembo': 'Čovek s velikim trbuhom, trbonja (pež.).',
 'školjkast': 'Koji podseća na školjku, koji je po obliku sličan školjci (školjkast izgled, predmet).',
 'škrba': 'Oštećen, okrnjen zub; oštećeno mesto, rupa u zubu, krezubina; i oštećeno mesto na oštrici oštrog oruđa; i oštećenje zupca na zupčastom oruđu.',
 'škrbo': 'Škrbav muškarac.',
 'škrgutav': 'Koji škrguće, škričav (škrgutav sto).',
 'škriljavac': 'Isto što i škriljac (min.).',
 'škrofuloznost': 'Stanje onoga koji je oboleo od škrofuloze.',
 'šlampavo': 'Neuredno, aljkavo; nedrapno, nespretno.',
 'šlampavost': 'Osobina onoga koji je šlampav, neurednost, aljkavost; nedrapnost, nespretnost.',
 'šlepati': 'Isto što i šlepovati.',
 'šljahta': 'Nekadašnje poljsko niže i srednje plemstvo (polj., ist.).',
 'šljivarstvo': 'Gajenje šljiva; poljoprivredna grana koja se bavi gajenjem šljiva (agr.).',
 'šljiviti': 'Pridavati pažnju nekome, mariti za nekoga: ne šljivi nikoga (fam.).',
 'šmrkav': 'Koji često šmrče; balav, slinav.',
 'šmuk': 'Nakit, ukras (nem., razg.).',
 'špacir': 'Šetnja: ići u špacir (nem.).',
 'špan': 'Nastojnik, nadzornik nad kmetovima u feudalno doba; činovnik na feudalnom imanju (mađ., ist.).',
 'špar': 'Vrsta morske ribe slična zubacu (zool., ital.).',
 'špekulantski': 'Koji se odnosi na špekulante, svojstven špekulantima (špekulantski kapital, posao).',
 'šrauba': 'Udarac loptom u rukometu, vaterpolu i sl. izveden iz zaokreta (sport, nem.).',
 'štalica': 'Umanjenica od štala; „najpre štalicu pa kravicu" i sl. — najpre ono što je važnije, potrebnije, pa onda ono sporednije.',
 'štapićast': 'Koji je kao štapić, sličan štapiću (štapićaste ćelije).',
 'štedionički': 'Koji se odnosi na štedionicu (štedionička zgrada, knjižica).',
 'štekavac': 'Vrsta orla (zool.).',
 'šteker': 'Naprava priključena na dovod električne struje (obično ugrađena u zid), koja služi za priključivanje potrošača električne energije pomoću utikača, utičnica (el., nem.).',
 'štenećak': 'Akutna zarazna bolest mladih pasa (vet.).',
 'štiklica': 'Umanjenica od štikla.',
 'štitarka': '(U množini) porodica zeljastih dikotiledonih biljaka čiji su mali petoročlani dvopolni cvetovi skupljeni u složene štitaste cvasti; (u jednini) biljka iz te porodice (bot.).',
 'štitić': 'Umanjenica i nežni oblik od štit.',
 'štićeništvo': 'Starateljstvo, zaštitništvo.',
 'štofara': 'Fabrika štofa.',
 'štreberstvo': 'Osobina i postupak štrebera, laktaštvo, karijerizam.',
 'štropotav': 'Koji izaziva, stvara štropot (štropotava lokomotiva, točkovi).',
 'štrukle': 'Vrsta jela od testa nadevenog sirom, bundevom i sl. (nem.; množina).',
 'štuk': 'Smesa gipsa, mermerne prašine, kreča i lepka (ital.).',
 'šuber': 'Otvor na prozoru koji se zatvara pomicanjem daske (u bankama, poštama i sl.) (nem.).',
 'šugavost': 'Stanje i osobina onoga koji je šugav, zaraženost šugom.',
 'šumovitost': 'Osobina i stanje predela koji je šumovit, obraslost šumom.',
 'šunkica': 'Umanjenica od šunka.',
 'šupica': 'Umanjenica od šupa.',
 'šupljikavost': 'Osobina i stanje onoga što je šupljikavo (šupljikavost krečnjaka, sira).',
 'šuteti': 'Isto što i ćutati.',
 'šuškavo': 'Šuškajući, šušteći (šuškavo se lelujati; govoriti).',
 'šušur': 'Slab šum, šušanj.',
 'šćap': 'Uzvik kojim se označava iznenadno grabljenje nečega ili za podražavanje zvuka pri halapljivom gutanju hrane.',
 'žabetina': 'Uvećanica i pežorativ od žaba.',
 'žalar': 'Naziv za neke rodove ptica trkačica srodne šljukama, koje žive po peskovitim obalama (zool.).',
 'žarkost': 'Osobina onoga što je žarko, vrelo; oduševljenje, zanos (žarkost sunca, poljubaca; u glasu).',
 'želatinast': 'Koji sadrži želatin, koji je kao želatin, pihtijast.',
 'ženkica': 'Umanjenica i nežni oblik od ženka.',
 'žeravnik': 'Metalna posuda u kojoj se drži žar, mančal.',
 'žgoljavost': 'Osobina onoga koji je žgoljav; mršavost, kržljavost.',
 'žicati': 'Strugati, čistiti žicom (žicati parket); i udarati, ćuti (prutom i sl.); i probadati, žilati, sevati (žica me u leđima); žarg. dostavljati imena, podatke, najčešće policiji, otkucavati.',
 'židovka': 'Jevrejka.',
 'žilje': '(Množina) zbirno od žila; korenje.',
 'žirondinac': 'Pristalica Žironde, umerene republikanske stranke u vreme francuske revolucije (ist.).',
 'žitorodan': 'Koji dobro rađa žito, bogat žitom (žitorodna ravnica, Vojvodina, godina).',
 'živkati': 'Cvrkutati (o vrapcima) (onom.).',
 'životopisac': 'Pisac životopisa, biograf.',
 'životopisni': 'Koji se odnosi na životopis, biografski (životopisni esej).',
 'živčanost': 'Stanje onoga koji je živčan, nervna osetljivost.',
 'žižni': 'Koji se odnosi na žižu, koji je u vezi sa žižom (žižna daljina, rastojanje) (fiz.).',
 'žlebast': 'Sličan žlebu, koji ima oblik žleba (žlebasti obronak, nokat).',
 'žmigati': 'Žmirkati (žmigati očima); i davati žmigavcem znak za skretanje (žmigati levim žmigavcem).',
 'žoržet': 'Fina vunena ili svilena tkanina (fr.).',
 'žuljevitost': 'Osobina i stanje onoga koji ima žuljeve.',
 'župljanka': 'Stanovnica župe; ist. žena iz župe; i vernica u župi, parohijanka.',
 'župnikov': 'Koji pripada župniku.',
 'župnikovati': 'Biti župnik, sveštenik; imati zvanje i službu župnika.',
 'župnički': 'Koji se odnosi na župnike (župnička služba).',
 'žutac': 'Žumance; i zlatan novac, žušak; i nebeljeno, žutkasto pamučno platno; i životinja žute dlake ili perja; i biljka žutog ploda ili lista.',
 'žutak': 'Zlatni novčić, zlatnik.',
 'žutenica': 'Naziv za više vrsta biljaka iz različitih familija i rodova, čiji su cvetovi obično žute boje (bot.).',
 'žutika': 'Vrsta biljke sa bodljama i žutim cvetovima (bot.).',
 'žutokos': 'Koji je žute kose, plavokos (žutokosa deca).',
 'žućak': 'Zlatnik, dukat; lažni dukat, imitacija zlatnika; i dnevni leptir žute boje (zool.).',
 'žučljivo': 'Zajedljivo, ljutito (žučljivo odgovarati, osmehnuti se).',
 'žučovod': 'Žučni kanal, žučna cevčica (anat.).',
 # rešena zaglavlja/isečci:
 'zaderati': 'Malo, površinski derati.',
 'čekač': 'Lovac koji čeka u (na) čeki, u zasedi; i onaj koji čeka.',
 'čerupav': 'Raščupan, čupav (čerupava kosa, pile).',
 'zatamnenje': 'Potamnjenje; čin potamnjenja (glagolska imenica od „zatamneti se").',
}

C = {
 'đen': 'glosa fragmentarna; značenje nejasno',
 'đene': 'glosa fragmentarna (deo odrednice „godina"); značenje nejasno',
 'đenom': 'glosa fragmentarna (deo odrednice „godina"); značenje nejasno',
 'đenu': 'glosa fragmentarna (deo odrednice „godina"); značenje nejasno',
 'đeni': 'glosa fragmentarna (deo odrednice „vilica"); značenje nejasno',
 'đeno': 'glosa fragmentarna (deo odrednice „daljina"); značenje nejasno',
 'đima': 'glosa fragmentarna; značenje nejasno',
 'đogin': 'nežni oblik; osnovna reč („đotaš"?) nejasna — nesigurno',
 'šainu': 'glosa fragmentarna; značenje nejasno',
 'šaini': 'glosa fragmentarna; značenje nejasno',
 'šanja': 'glosa fragmentarna; značenje nejasno',
 'šanje': 'glosa fragmentarna; značenje nejasno',
 'šanjom': 'glosa fragmentarna; značenje nejasno',
 'šanju': 'glosa fragmentarna; značenje nejasno',
 'šati': 'glosa fragmentarna; značenje nejasno',
 'šela': 'glosa fragmentarna (deo odrednice „hotel"); značenje nejasno',
 'šelu': 'glosa fragmentarna; značenje nejasno',
 'šelešu': 'glosa fragmentarna; značenje nejasno',
 'šelj': 'glosa fragmentarna; značenje nejasno',
 'šelja': 'glosa fragmentarna; značenje nejasno',
 'šelji': 'glosa fragmentarna; značenje nejasno',
 'šelo': 'glosa fragmentarna (deo odrednice „valjak"); značenje nejasno',
 'šen': 'glosa fragmentarna; značenje nejasno',
 'šena': 'glosa fragmentarna; značenje nejasno',
 'šeni': 'glosa fragmentarna; značenje nejasno',
 'šeputić': 'umanjenica; osnovna reč („šeput") nejasna — nesigurno',
 'šer': 'glosa fragmentarna (deo odrednice „uopštiti"); značenje nejasno',
 'šera': 'glosa fragmentarna; značenje nejasno',
 'šereš': 'glosa fragmentarna (deo odrednice „doznaka"); značenje nejasno',
 'šereša': 'glosa fragmentarna; značenje nejasno',
 'šeri': 'verovatno „šeri" (vino) — glosa neuhvaćena; vlasnica odlučuje',
 'ševiti': 'gruba, žargonska reč (seksualni odnos); rečnik takve ne vodi',
 'šeška': 'glosa fragmentarna; značenje nejasno',
 'šikom': 'glosa nejasna — nesigurno',
 'škripina': 'uvećanica; osnovna reč („škrip"?) nejasna — nesigurno',
 'škova': 'glosa fragmentarna (deo odrednice „čist"); značenje nejasno',
 'šore': 'glosa fragmentarna (deo odrednice „mehaničar"); značenje nejasno',
 'šupak': 'vulgarno (vulg. po Matici); rečnik takve reči ne vodi',
 'šući': 'glosa fragmentarna; značenje nejasno',
 'švara': 'glosa fragmentarna; značenje nejasno',
 'ženja': 'glosa fragmentarna; značenje nejasno',
 'žicar': 'glosa neuhvaćena (samo zaglavlje strane u OCR-u) — nesigurno',
 'žine': 'glosa fragmentarna (deo odrednice „vaga"); značenje nejasno',
 'žini': 'glosa fragmentarna; značenje nejasno',
 'žinom': 'glosa fragmentarna; značenje nejasno',
 'žinu': 'glosa fragmentarna; značenje nejasno',
 'vodonosnih': 'oblik prideva (vodonosni slojevi); glosa neuhvaćena iz OCR-a — nesigurno',
 'čunjić': 'nije u Matici (ni fuzzy) — nepotvrđeno',
 'reša': 'moguće vezanost uz „reš" (hrskavo pečen), ali oblik nije jasan — vlasnica odlučuje',
 'rešu': 'moguće vezanost uz „reš" (hrskavo pečen), ali oblik nije jasan — vlasnica odlučuje',
 'mikrotalasan': 'Matica vodi samo imenicu „mikrotalas"; pridevska familija nije potvrđena kao token — vlasnica odlučuje',
 'mikrotalasnim': 'oblik prideva „mikrotalasan"; u Matici samo imenica „mikrotalas" — vlasnica odlučuje',
 'mikrotalasnima': 'oblik prideva „mikrotalasan"; u Matici samo imenica „mikrotalas" — vlasnica odlučuje',
 'mikrotalasnog': 'oblik prideva „mikrotalasan"; u Matici samo imenica „mikrotalas" — vlasnica odlučuje',
 'mikrotalasnoga': 'oblik prideva „mikrotalasan"; u Matici samo imenica „mikrotalas" — vlasnica odlučuje',
 'mikrotalasnome': 'oblik prideva „mikrotalasan"; u Matici samo imenica „mikrotalas" — vlasnica odlučuje',
 'mikrotalasnomu': 'oblik prideva „mikrotalasan"; u Matici samo imenica „mikrotalas" — vlasnica odlučuje',
}
