# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 2971–3300 (tešiteljica … videlica).

DEC = {
 'tešiteljica': 'Ona koja teši, utešiteljica.',
 'težakinja': 'Ženska osoba težak.',
 'tifon': 'Elementarna nepogoda — olujni vetar, potres, vulkanska provala; prema Tifonu, divu iz grčke mitologije sa zmijolikim trupom; uporedi tajfun (grč.).',
 'tiftin': 'Čvrsta gusta pamučna tkanina slična baršunu, za sportsku odeću i sl. (fr.).',
 'tigrovina': 'Koža tigra, krzno od tigra.',
 'tigrovski': 'Koji se odnosi na tigrove, koji pripada tigrovima, koji je kao u tigra (tigrovski pogled).',
 'tihan': 'U umanjenom značenju: tih (tihan glas).',
 'tikvast': 'Koji ima oblik tikve, koji izgledom podseća na tikvu (tikvasta posuda, boca).',
 'til': 'Laka svilena ili pamučna mrežasta tkanina, po francuskom gradu Tilu (fr.).',
 'tilda': 'Znak u obliku izvijene talasaste crte (~): u rečnicima pokazuje ponavljanje odrednice ili njenog sastavnog dela; u španskoj grafiji iznad slova n (ñ) pokazuje da ta treba čitati kao „nj" (šp.).',
 'tili': 'Za pojačavanje u izrazima: za (u) tili čas(ak), za (u) tili tren(utak) — odmah, vrlo brzo, začas.',
 'tintara': 'Glava (familijarno i pežorativno); uporedi tikva.',
 'tintarnica': 'Bočica za tintu, mastionica.',
 'tiskanica': 'Obrazac, formular (reg.); i ono što je tiskano, naštampano.',
 'tisov': 'Koji je od tisa, koji pripada tisu (tisovo drvo, list).',
 'tisovina': 'Tisovo drvo; tisovo drveće.',
 'titovka': 'Vrsta vojničke kape koju su nosili partizani i, u socijalističkoj Jugoslaviji, vojnici Jugoslovenske narodne armije, prema J. B. Titu (razg.).',
 'tivuška': 'Vrsta ribe; brkica (zool.).',
 'tobolčar': '(Obično u množini) isto što i torbar (zool.).',
 'tokariti': 'Raditi na tokarskoj mašini, na strugu.',
 'tokarstvo': 'Tokarski zanat, rad tokara.',
 'tonalno': 'U pogledu tona, tonaliteta.',
 'tonirati': 'Da(va)ti čemu osnovni ton, izraz.',
 'toničan': 'Koji se odnosi na tonus (glatki mišići su označeni kao tonični).',
 'tonički': 'Koji se odnosi na toniku (tonička harmonija; akcenat).',
 'tonzila': '(Obično u množini) isto što i krajnik (anat., lat.).',
 'topioničarstvo': 'Rad u topionicama.',
 'topljivost': 'Osobina onoga što je topljivo.',
 'toplokrvnost': 'Osobina onoga što je toplokrvno.',
 'toplonoša': 'Provodnik toplote.',
 'topolovina': 'Topolovo drvo.',
 'topčić': 'Umanjenica od top.',
 'torbetina': 'Uvećanica i pežorativ od torba.',
 'torina': 'Uvećanica i pežorativ od tor; tor.',
 'torić': 'Umanjenica od tor.',
 'tornjati': '(Tornjati se) brzo odlaziti, gubiti se (obično u zapovesti, u oštrijem izražavanju).',
 'torpedirati': 'Isto što i torpedovati.',
 'totalizator': 'Aparat za mehaničko registrovanje neke operacije, nekih merenja, u meteorologiji i sl. (lat.).',
 'tovilište': 'Mesto gde se tovi stoka, naročito svinje.',
 'trabakul': 'Teretni jedrenjak zaobljenog trupa na pramcu i oštre krme (ital.).',
 'tradicionalizam': 'Verovanje u tradiciju, održavanje tradicije.',
 'tradicionalnost': 'Osobina, stanje onoga koji je tradicionalan, onoga što je tradicionalno.',
 'tragikomičan': 'Koji je istovremeno i tragičan i komičan (tragikomična ispovest).',
 'tragikomično': 'Na tragičan i komičan način, i tragično i komično.',
 'traheida': '(U množini) duguljaste ćelije u drveću koje su međusobno spojene; (u jednini) takva ćelija.',
 'trahom': 'Zarazna bolest očiju, zapaljenje očnih veznica, vežnjace (med., grč.).',
 'traljavac': 'Onaj koji je traljav, neuredan, dronjav; onaj koji ne pokazuje određene sposobnosti, koji loše obavlja svoju dužnost.',
 'traljavost': 'Osobina, stanje onoga koji je traljav, onoga što je traljavo.',
 'traminac': 'Vrsta vinove loze i grožđa; vino od tog grožđa, prema mestu Tramin u Tirolu (agr.).',
 'trandovilje': 'Beli slez; i pitomi slez (bot.).',
 'transcendentalizam': 'Učenje Kantove i uopšte idealističke filozofije prve polovine XIX veka o apriornim, transcendentalnim formama saznanja, kao reakcija na racionalizam i empirizam (fil.).',
 'transcendentnost': 'Stanje, osobina, svojstvo onoga što je transcendentno.',
 'transcendirati': 'Preći, prelaziti granice iskustva, biti izvan ili iznad čulnog opažanja.',
 'transkontinentalan': 'Koji prelazi preko kontinenta (transkontinentalna železnica).',
 'transliterirati': 'Izvršiti transliteraciju.',
 'transmitirati': 'Preneti, prenositi, isporuči(va)ti.',
 'transplantirati': 'Izvršiti transplantaciju, presaditi, presađivati, premestiti, premeštati tkivo ili organ.',
 'transverzalno': 'Transverzalnim pravcem, poprečno.',
 'traumatizirati': 'Izaz(i)vati traumu.',
 'travarstvo': 'Nauka o travama, obično lekovitim; i sakupljanje trava i lečenje travama.',
 'travestirati': 'Napraviti travestiju; izopačiti, karikirati.',
 'trbušić': 'Umanjenica i nežni oblik od trbuh.',
 'tref': 'Boja u kartama u obliku žira, žir, mak (tref as, tref sedmica) (fr.).',
 'trefov': 'Koji se odnosi na tref (trefova sedmica, as).',
 'tresavica': 'Troznica, drhtavica; i oboljenje pri kome drhte udovi i glava.',
 'trećeligaš': 'Član treće lige, najčešće fudbalske (sport).',
 'trećerazredan': 'Koji je pri oceni kvaliteta, vrednosti, značaja i sl. svrstan u treću grupu, u treći, obično poslednji razred.',
 'trešnjevina': 'Trešnjevo drvo (kao građa).',
 'trešnjik': 'Trešnjev voćnjak; uporedi trešnjak, trešnjar.',
 'treščica': 'Umanjenica od treska.',
 'trgovinica': 'Umanjenica i nežni oblik od trgovina.',
 'tridesetina': 'Trideseti deo neke celine (tridesetina sume); i isto što i tridesetak (tridesetina ljudi).',
 'tridesetogodišnjak': 'Čovek koji ima trideset godina.',
 'trimestar': 'Tromesečni period, tromesečje; četvrti deo godine, kvartal (lat.).',
 'triola': 'Grupa od tri jednake note koje traju koliko i dve normalne note istog oblika (muz., ital.).',
 'tripice': '(Množina) jelo od iznudrice, škembići.',
 'triplikat': 'Treći primerek, druga kopija nekog teksta (lat.).',
 'trnovitost': 'Osobina i stanje onoga što je trnovito.',
 'trodimenzionalnost': 'Svojstvo onoga što je trodimenzionalno.',
 'trodnevnica': 'Trodnevni period.',
 'trogodišnjica': 'Navršene tri godine od nekog događaja (trogodišnjica oslobođenja); i (u pridevskoj službi, uz imenice ž. roda) trogodišnja (šljivovica trogodišnjica).',
 'trokolica': 'Vozilo na tri točka.',
 'trokrevetni': 'Koji ima tri kreveta (trokrevetna soba).',
 'trokrilan': 'Koji ima tri krila, tri preklopna dela (trokrilni orman, vrata).',
 'troletni': 'Koji traje tri leta; trogodišnji.',
 'trolistan': 'Koji ima tri lista (trolisna detelina).',
 'tromblon': 'Naročit dodatak pušci koji omogućuje ispaljivanje eksplozivnih projektila (voj., fr.).',
 'tromesečnik': 'List ili časopis koji izlazi jedanput u tri meseca.',
 'tropev': 'Kompozicija za tri instrumenta ili tri pevača, tri izvođača takve kompozicije, tercet (muz.).',
 'tropreg': 'Zaprega od tri konja.',
 'trostrukost': 'Osobina onoga što je trostruko.',
 'trovlašće': '(Množina) uprava trojice, triju grupacija, triju stranaka i sl.',
 'troznamenkast': 'Koji ima tri znamenke, cifre, trocifren (troznamenkasti broj).',
 'trozvuk': 'Akord, sazvuchje od tri zvuka — od velike ili male terce i čiste kvinte — od najnižeg tona naviše (muz.).',
 'trošarinski': 'Koji se odnosi na trošarinu (trošarinski ured, službenik).',
 'trp': '(U množini) razred bodljokožaca morskih životinja duguljastog savitljivog tela, na kome su sitne krečne pločice, morski krastavci; (u jednini) takav bodljokožac (zool.).',
 'trpkost': 'Svojstvo, stanje onoga što je trpko; trpkoća.',
 'trstenjak': 'Vrsta ptice; „veliki trstenjak" — vrsta ptice koja živi u trščacima (zool.).',
 'trstikov': 'Koji je od trstike (trstikova svirala).',
 'trto': 'Debeo i nezgrapan čovek; klipan (pež.).',
 'trupica': 'Manji panj, manja klada (sesti na trupicu).',
 'trusiti': 'Tresti, stresati, istresati (trusiti latice cveća, rosu); preneseno: ispijati do dna (trusiti čašu); (trusiti se) stresati se, padati, opadati, kruniti se (sa fasada se trusi malter).',
 'trutov': 'Trut; tošovan, lenština.',
 'tuberkula': 'Čvorić, mehurić, na završetku bronhiola u plućima (med.); razg. tuberkuloza.',
 'tuberkulin': 'Preparat (sterilni filtrat bacila tuberkuloze) za zaštitno cepljenje i lečenje od tuberkuloze.',
 'tucač': 'Onaj koji tuca kamen, pravi tucanik.',
 'tumbas': 'Mali čamac plitkog dna; i niz takvih čamaca kao pontonski most; i kameni stub koji podupire kakvu građevinu (ambar, vodenicu, most); i ono što podseća na takav stub (tumbas dima) (tur.).',
 'tunolov': 'Lov na tune; lov na tune kao grana ribarstva.',
 'tupast': 'Zatupast, tupav; i pomalo ograničen, priglup.',
 'tupavost': 'Osobina, stanje onoga koji je tupav.',
 'turbulentno': 'Na turbulentan način, s velikom žestinom.',
 'turcizirati': '(U)činiti koga Turčinom ili nešto turskim, poturči(va)ti (turcizirani Arbanasi).',
 'turina': 'Uvećanica od tur.',
 'turić': 'Umanjenica od tur.',
 'turmalin': 'Mineral s kristalima koji se bruse kao drago kamenje; dragi kamen različite boje.',
 'turmalinov': 'Koji je od turmalina (turmalinova pločica).',
 'tust': 'Ugojen, debeo (tusta osoba); zamašan, krupan (o delovima tela); koji sadrži mnogo masti, sala (o mesu); preneseno: bujan, sočan, obilan (o paši, travi); plodan, rodan (o zemlji) (reg.).',
 'tučonosan': 'Koji nosi u sebi tuču (grad), koji je pun tuče, gradonosan (tučonosan oblak).',
 'tuđinština': 'Ono što je tuđinsko, tuđinstvo.',
 'tvorić': 'Umanjenica od tvor.',
 'tvrdokrilac': '(U množini) insekti, kukci tvrdih prednjih krila, kornjaši; (u jednini) takav insekt (zool.).',
 'tvrđavni': 'Koji se odnosi na tvrđavu, koji pripada tvrđavi (tvrđavna postaja, vrata).',
 'ubirač': 'Onaj koji ubira, skuplja, naplaćuje i sl. (ubirač poreza).',
 'ubitačnost': 'Osobina, stanje onoga što je ubitačno (ubitačnost noćnog rada).',
 'ublaživati': 'Nesvršeni oblik glagola „ublažiti".',
 'ubrzanost': 'Stanje onoga što je ubrzano.',
 'ucenjivački': 'Koji se odnosi na ucenjivače, koji predstavlja ucenu (ucenjivačko pismo, otmica).',
 'ucepiti': 'Izvršiti cepljenje, kalamljenje, nakalamiti; preneseno: uliti, usaditi.',
 'udahnjivati': 'Nesvršeni oblik glagola „udahnuti".',
 'udarnica': 'Ženska osoba udarnik.',
 'udić': 'Umanjenica od ud.',
 'udubljenost': 'Stanje onoga koji je udubljen u nešto, zanesen nečim; zaokupljenost, zadubljenost.',
 'udvoran': 'Koji pokazuje naročitu pažnju, uslužan (udvoran službenik); i kojim se pokazuje posebna naklonost, pažnja, učtiv, ljubazan (udvoran postupak).',
 'udvoriti': '(Udvoriti se, nekome ili bez dopune) steći naklonost dodvoravajući se, dodvoriti se (udvoriti se devojci, gazdi).',
 'udvostručenost': 'Osobina onoga što je udvostručeno, dvostrukost.',
 'ugaonik': 'Ugaoni kamen; preneseno: temelj, osnova.',
 'ugađač': 'Onaj koji voli da nekome ugađa; uporedi ugađalica; i onaj koji udešava muzičke instrumente, štimer.',
 'uglatost': 'Osobina i stanje onoga što je uglato.',
 'uglednost': 'Ugled; lep izgled, lepota.',
 'ugljikohidrat': 'Ugljeni, ugljični hidrat.',
 'ugotica': 'Morska riba srebrnastobele boje, srodna osliću i bakalaru (zool.).',
 'ugotoviti': 'Spremiti, zgotoviti (jelo).',
 'ugošćivati': 'Nesvršeni oblik glagola „ugostiti".',
 'uhat': 'Koji ima velike uši; i koji ima drške sa strane (o kakvom posuđu).',
 'uhlebiti': 'Omogućiti nekome, zaposlivši ga ili na koji drugi način, pribavljanje sredstava za život; (uhlebiti se) dobiti službu, zaposliti se.',
 'ukalupljenost': 'Osobina onoga što je ukalupljeno, šablonizovano.',
 'ukleštenje': '(U izrazu „ukleštenje kile") zatlavljenost spuštenih creva u šupljine u trbušnoj duplji (med.).',
 'ukonačenje': 'Dolazak, primanje, smeštanje na konak.',
 'ukopnina': 'Pogrebni trošak, taksa za ukop, za sahranu; i ono što se ukopa zajedno sa pokojnikom (neke lične stvari).',
 'ukrućenost': 'Osobina, stanje onoga koji je ukrućen, onoga što je ukrućeno.',
 'ukućanka': 'Ženska osoba ukućanin.',
 'ulaznina': 'Dažbina koja se plaća pri ulasku negde, pri unošenju nečega negde.',
 'ulepšanje': 'Ulepšan izgled; ulepšan prikaz.',
 'ulickati': 'Ulačati, uladiti, doterati; (ulickati se) udesiti se, doterati se.',
 'ulizati': 'Ovlažiti jezikom, zalizati, olizati; i zalizati dlaku, lako začešljati kosu; (ulizati se) istanjiti se od duže upotrebe, izlizati se; i doterati se.',
 'uljar': 'Onaj koji se bavi uljem (prodaje ga i dr.).',
 'uljarstvo': 'Proizvodnja ulja.',
 'uljevitost': 'Osobina onoga što sadrži ulje.',
 'ulogovati': '(Ulogovati se) pristupiti nekoj stranici interneta unoseći odgovarajuću lozinku, odnosno šifru (rač.).',
 'uložnica': 'Uložna, štedna knjižica; i jagodična kost (anat.).',
 'ultradesničar': 'Pristalica, pripadnik ultradesnice.',
 'ultramarin': 'Mineral plave, zelene ili ljubičaste boje i skupocena modroljubičasta boja dobijena od njega ili na veštački način (lat.).',
 'umanjenica': 'Reč u umanjenom, deminutivnom obliku (kućica od kuća).',
 'umasirati': 'Masiranjem uneti, uprljati (umasirati ulje u kosu).',
 'umazati': 'Uprljati, zamazati, umrljati (umazati ruke, odeću); (umazati se) zamazati se, umrljati se (umazati se blatom).',
 'umirovljenje': 'Prestanak aktivne službe, penzionisanje.',
 'umokac': 'Umak, sos.',
 'umrtvljenost': 'Stanje onoga što je umrtvljeno, onoga koji je umrtvljen.',
 'unapređivač': 'Onaj koji nekoga ili nešto unapređuje.',
 'uneravnotežen': 'Duhovno nestabilan, neuravnotežen.',
 'unesrećenik': 'Onaj koji je unesrećen.',
 'unilateralno': 'U korist samo jedne zainteresovane strane; samovoljno, samovlasno, jednostrano (unilateralno ukinuti sankcije).',
 'unionistički': 'Koji se odnosi na unionizam i unioniste (unionistički sabor).',
 'unovčenje': 'Zamena nečega za novac (unovčenje vrednosnih papira); i izvlačenje materijalne koristi iz nečega (unovčenje znanja).',
 'unovčivati': 'Nesvršeni oblik glagola „unovčiti".',
 'unukov': 'Koji pripada unuku (unukov sin, kći).',
 'unča': 'Stara mera za težinu, dvanaesti deo libre (funte), dram; i stara mera za dužinu, palac; preneseno: mala količina, mrvica, zrnce (lat.).',
 'uobičavati': 'Nesvršeni oblik glagola „uobičajiti".',
 'uopštenje': 'Proširenje nečega na širu, načelnu pojavu, generalizacija.',
 'upaljivost': 'Osobina onoga koji je upaljiv, onoga što je upaljivo.',
 'uperivati': 'Nesvršeni oblik glagola „uperiti".',
 'upotreban': 'Koji se upotrebljava, koristi, primenjuje.',
 'upraviteljstvo': 'Uprava, upravljanje; mesto i dužnost upravitelja.',
 'upržiti': 'Prženjem odstraniti, otkloniti tečnost iz nečega; prženjem zgotoviti, ispržiti jelo (upržiti meso).',
 'upumpati': 'Pumpajući ubaciti (vazduh, vodu i dr.).',
 'upumpavati': 'Nesvršeni oblik glagola „upumpati".',
 'uranov': 'Koji pripada uranu, koji je u vezi sa uranom (uranova ruda, atom, uranove soli).',
 'urastati': 'Nesvršeni oblik glagola „urasti".',
 'uredovati': 'Raditi, biti zaposlen u uredu; i zavoditi red, intervenisati (obično o policiji).',
 'ureter': 'Kanal koji od bubrega sprovodi mokraću u mokraćnu bešiku, mokraćovod (anat.).',
 'uretra': 'Mokraćna cev kojom mokraća otiche iz bešike (anat., grč.).',
 'urica': 'Umanjenica i nežni oblik od ura.',
 'urinirati': 'Ispuštati mokraću, mokriti.',
 'urlator': 'Onaj koji urla (ital.).',
 'uročiti': 'Odrediti vreme, rok, zakazati, ugovoriti; (uročiti se) dogovoriti se, sporazumeti se o nečemu.',
 'usaglašenost': 'Svojstvo, stanje onoga što je usaglašeno.',
 'usalamuriti': 'Spaviti u salamuru, usoliti u salamuri (meso npr.).',
 'usavršenost': 'Svojstvo, stanje onoga što je usavršeno.',
 'usfaliti': 'Uzmanjkati, nedostati, ponestati (obično bezlično).',
 'usipati': 'Nesvršeni oblik glagola „usuti".',
 'uskokodakati': '(Uskokodakati se) početi kokodakati, raskokodakati se; i razgalamiti se.',
 'uskomešanost': 'Stanje onoga što je uskomešano.',
 'uskotračan': 'Koji je uskih tračnica (o koloseku, pruzi): uskotračna pruga (žel.).',
 'usmen': 'Izražen rečima koje nisu napisane, nepisan (usmeni sporazum, nalozi); i koji se prenosi, obavlja govorom (usmena književnost, ispit).',
 'usmrćenje': 'Lišenje života, ubistvo.',
 'usporednica': 'Paralelna, uporedna linija (mat.); geogr. isto što i uporednik.',
 'usporednost': 'Uporedost, naporedost.',
 'usporedo': 'Uporedo, naporedo.',
 'usporivač': 'Ono što usporava (usporivač nuklearnih reakcija).',
 'uspuhati': '(Uspuhati se) početi puhati, duvati; udariti u puhanje.',
 'usputan': 'Koji se dešava, nalazi uz put; sporedan, manje važan ili nevažan (usputne kuće; usputni razgovori).',
 'usredotočenje': 'Postizanje visokog stepena sabranosti, usredsređenosti, koncentracija.',
 'usredotočiti': 'Koncentrisati, usredsrediti (pažnju, aktivnost i sl.) u jednom pravcu, na jednu stvar; (usredotočiti se) koncentrisati se, usredsrediti se na nešto.',
 'usrđe': 'Usrdnost, srdačnost.',
 'ustanovljivati': 'Nesvršeni oblik glagola „ustanoviti".',
 'ustreperiti': 'Zatreperiti, ustreptati.',
 'ustrpljiv': 'Strpljiv; uzdržan.',
 'ustupljivati': 'Nesvršeni oblik glagola „ustupiti".',
 'utakati': 'Nesvršeni oblik glagola „utočiti".',
 'uteriv': 'Koji se može uterati, naplatiti (uteriv dug).',
 'utešljiv': 'Koji se može utešiti; uporedi utešiv.',
 'utomiti': 'Prigušiti, potisnuti; eliminisati (utomiti strast).',
 'utopistički': 'Koji se odnosi na utopiste (utopistički program, ideje).',
 'utopizam': 'Utopističko stanje, utopističke ideje, utopija.',
 'utovarivač': 'Onaj koji utovaruje, radi na utovaru robe; tehn. vrsta dizalice za zahvatanje i prenošenje materijala.',
 'utreti': 'Upreti (pogled).',
 'utrobni': 'Koji se odnosi na utrobu (utrobna kesa, utrobni organi).',
 'utrostručenje': 'Trostruko uvećanje.',
 'utržak': 'Novac zarađen trgovinom (dnevni utržak).',
 'utržiti': 'Steći trgujući.',
 'utuženje': 'Podnošenje tužbe, tužba; zahtev izložen u tužbi.',
 'utužiti': 'Podneti tužbu protiv nekoga, (op)tužiti; i obuhvatiti tužbom, naznačiti u tužbi.',
 'utuživ': 'Koji se može tužiti, podložan tužbi (utuživ ugovor).',
 'uvalica': 'Umanjenica od uvala; i bora, nabor.',
 'uvalina': 'Uvećanica od uvala; uvala; i udubljenje uopšte.',
 'uvezivati': 'Nesvršeni oblik glagola „uvezati".',
 'uvišestručiti': 'Višestruko, više puta povećati (uvišestručiti rashode).',
 'uvoznica': 'Ona koja uvozi robu iz inostranstva za domaće tržište (obično o državi); i dozvola za uvoz, uvozna isprava.',
 'uvredljivost': 'Osobina onoga što je uvredljivo, kojim se vređa, koje sadrži uvredu; i osobina onoga koji se lako vređa, osetljivost na uvredu.',
 'uvučenost': 'Osobina i stanje onoga što je uvučeno, onoga koji je uvučen.',
 'uzao': 'Splet nastao uvezivanjem nečega savitljivog (konca, užeta, marame i dr.), čvor.',
 'uzburkanost': 'Stanje onoga koji je uzburkan, onoga što je uzburkano.',
 'uzdihati': '(Uzdihati se) početi ubrzano i teško disati, zadihati se, zaduvati se.',
 'uzdržanje': 'Uzdržavanje; uzdržanost, uzdržljivost.',
 'uzdržavatelj': 'Staratelj, hranitelj.',
 'uzemljiti': 'Izvršiti uzemljenje; (uzemljiti se) prodreti, zaći u zemlju (koren jablana se duboko uzemlji).',
 'uzemljivač': 'Metalni vod ili provodnik koji se spaja s aparatom radi uzemljenja (el.).',
 'uzljubiti': 'Početi ljubiti, voleti, zavoleti.',
 'uzmah': 'Nagli pokret ruke, noge, tela radi udara, postizanja snage i brzine, zamah; i polet, zanos, entuzijazam; muz. nenaglašeni deo ritmičkog oblika, takta.',
 'uzmanjkati': 'Izostati, ne naći se (trudimo se da joj ne uzmanjka hrane).',
 'uznositost': 'Ponos, oholost.',
 'uzoritost': 'Osobina onoga koji je uzorit, onoga što je uzorito.',
 'uzročan': 'Koji je u vezi sa uzrokom, koji predstavlja uzrok (uzročna veza); uzročna (kauzalna) rečenica — zavisna rečenica kojom se kazuje uzrok radnje u glavnoj rečenici (lingv.).',
 'uzveličati': 'Učiniti većim, povećati, uveličati; preneseno: uzdići, pohvaliti.',
 'uzvratan': 'Koji se odnosi na uzvrat, koji dolazi kao uzvrat, kao uzvraćanje (uzvratna poseta).',
 'učiteljevati': 'Biti učitelj, raditi kao učitelj.',
 'ušata': 'Vrsta morske ribe (zool.).',
 'ušenac': 'Vrsta insekta koji napada vinovu lozu, uporedi filoksera (zool.); i (u množini) porodica insekata, kukaca rilaca koji sišu biljne sokove iz lišća, lisne vaši; (u jednini) lisna vaš.',
 'ušitak': 'Ušiveni komad neke tkanine.',
 'ušljivost': 'Stanje onoga koji je ušljiv, vašljivost.',
 'uštipčić': 'Umanjenica i nežni oblik od uštipak.',
 'ušutkavati': 'Nesvršeni oblik glagola „ušuškati".',
 'uščuvanost': 'Stanje onoga što je uščuvano, sačuvano.',
 'užarenost': 'Stanje onoga što je užareno, usijanost; žar, rumenilo; uzbuđenost, vatrenost.',
 'uživljenost': 'Stanje onoga koji se uživljava.',
 'vagnuti': 'Izmeriti težinu vagom (vagnuti žito); preneseno: ozmeriti, proceniti, prosuditi; i pokazati određenu težinu (vagnuti 100 kila); i nakrenuti se (vagnuti na desnu stranu).',
 'vakuola': '(Obično u množini) okrugla šupljina, mehurić, u protoplazmi ćelije, biljaka i jednoćelijskih životinja (biol., lat.).',
 'val': 'Uzdignuti deo ustalasane vodene mase, talas; i ono što izgleda kao val, što ima talasast oblik (valovi kose); fiz. talasasto kretanje, širenje (elektromagnetni valovi, trusni valovi).',
 'valić': 'Umanjenica od val.',
 'valovitost': 'Osobina, izgled onoga što je valovito.',
 'vaninstitucionalan': 'Koji se odvija, vrši van zvaničnih institucija.',
 'vatrogastvo': 'Vatrogasna služba, požarništvo.',
 'vatrometno': 'Kao vatromet; preneseno: blistavo, sjajno.',
 'vazalan': 'Koji ima svojstvo vazala prema nekome; potčinjen, podređen, zavisan (vazalna država, odnos).',
 'vazdušan': 'Koji se odnosi na vazduh (vazdušna linija, saobraćaj); koji je od vazduha (vazdušni omotač, struja); koji je u vezi s lečenjem na čistom vazduhu (vazdušna banja); i isto što i vazdušast.',
 'vehementno': 'Žestoko, silovito, neobuzdano, plahovito, vatreno.',
 'vekovati': 'Provoditi vekove, živeti vekovima (vekovati u ropstvu); i večno postojati, trajati; i (često sa dopunom „vek") živeti, provoditi život (vek vekovati s nekim).',
 'veletrgovina': 'Trgovina na veliko; i trgovačka radnja za prodaju na veliko.',
 'velikomučenica': 'Žena velikomučenik (velikomučenica Varvara).',
 'velikosrpstvo': 'Velikosrpski nacionalizam, šovinizam.',
 'velter': '(Obično u sintagmi „velter kategorija") kategorija boksera čija je težina od 62 do 67 kg (sport, engl.).',
 'ventilni': 'Koji se odnosi na ventil.',
 'veprovina': 'Meso od vepra, svinjetina.',
 'vergl': 'Mehanička muzička sprava u obliku sandučića na kojoj se okretanjem ručice sviraju uvek iste melodije: ponavljati nešto kao vergl (ital.).',
 'verizam': 'Realistički pravac u italijanskoj likovnoj umetnosti, književnosti i muzici nastao krajem XIX veka, pod uticajem francuskog naturalizma (fr.).',
 'vernički': 'Koji se odnosi na vernike, svojstven vernicima (vernički fanatizam).',
 'veronal': 'Fabrički naziv za jedno od jakih sredstava za uspavljivanje (farm.).',
 'veronaučni': 'Koji se odnosi na veronauku.',
 'vertikalnost': 'Vertikalan položaj.',
 'vesalce': 'Umanjenica od veslo.',
 'vesnica': 'Ona koja donosi vesti, poruke, glasnica; izaslanica; preneseno: ona ili ono što najavljuje, najaveštava nešto (zora vesnica dana).',
 'vesta': 'Kratak kaput; prsluk; i sveštenička mantija (ital.).',
 'vestalka': 'Starorimska devičanska sveštenica božice Veste koja je čuvala „sveti oganj" u njenom hramu (mit.).',
 'vetrobranski': 'Koji se odnosi na vetrobran (vetrobransko staklo).',
 'vetruša': 'Vrsta manjeg sokola koji ume da lebdi u mestu (zool.).',
 'vetrušina': 'Uvećanica i pežorativ od vetar.',
 'vezidba': 'Vezivanje, privezivanje (obično vinove loze, vinograda); vreme kad se vrši taj posao.',
 'vezirstvo': 'Dostojanstvo, zvanje i vlast vezira; i oblast kojom upravlja vezir.',
 'večernica': 'Isto što i večernje (crkv.).',
 'veštakinja': 'Ženska osoba veštak.',
 'vežbačica': 'Ženska osoba vežbač.',
 'vidarica': 'Ženska osoba vidar, isceliteljka.',
 'videlac': 'Vidoviti čovek, vizionar; i onaj koji ima sposobnost da vidi ono što drugi ne mogu, da doživi ukazanje božanskih bića u čovečjem liku.',
 'videlica': 'Ženska osoba videlac.',
}

C = {
 'tiri': 'glosa fragmentarna; značenje nejasno',
 'tirić': 'glosa fragmentarna; značenje nejasno',
 'titi': 'glosa fragmentarna (deo odrednice „dok"); značenje nejasno',
 'tonja': 'glosa OCR-nečitka (botanička) — nesigurno',
 'tosti': 'glosa fragmentarna; značenje nejasno',
 'tova': 'glosa fragmentarna; osnovna reč nejasna',
 'tovom': 'glosa fragmentarna; osnovna reč nejasna',
 'trak': 'glosa fragmentarna; značenje nejasno',
 'trama': 'glosa samo uput na „vetromer" — značenje nesigurno',
 'tubast': 'glosa OCR-nečitka — nesigurno',
 'tučar': 'glosa OCR-nečitka (životinjske vrste nečitljive) — nesigurno',
 'turirali': 'glosa fragmentarna (deo odrednice „potom"); značenje nejasno',
 'uku': 'glosa fragmentarna; značenje nejasno',
 'uke': 'glosa fragmentarna; značenje nejasno',
 'ura': 'glosa fragmentarna; značenje nejasno',
 'utom': 'glosa pogrešno uhvaćena; značenje nejasno',
 'ušak': 'glosa pogrešno uhvaćena (deo odrednice „megdan"); značenje nejasno',
 'vac': 'glosa fragmentarna; značenje nejasno',
 'vana': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'vane': 'u Matici samo unutar tuđih glosa; značenje nejasno',
 'vavu': 'glosa fragmentarna (deo odrednice „vaditi"); značenje nejasno',
 'veda': 'Matica vodi „veda" samo unutar glosa o veri; hinduistički smisao nije potvrđen u ovom OCR-u — vlasnica odlučuje',
 'Vener': 'oblik planete Venere (u rečniku ima objašnjenje); Matica ga kao oblik ne vodi eksplicitno — vlasnica odlučuje',
 'Venerem': 'oblik planete Venere; Matica ga kao oblik ne vodi eksplicitno — vlasnica odlučuje',
 'Venerima': 'oblik planete Venere; Matica ga kao oblik ne vodi eksplicitno — vlasnica odlučuje',
 'vešnik': 'glosa fragmentarna; značenje nejasno',
}
