# -*- coding: utf-8 -*-
# Odluke za pregled.txt linije 2641–2970 (sangviničnost … tezaurus).

DEC = {
 'sangviničnost': 'Osobina sangvinika.',
 'sanjač': 'Onaj koji sanja, koji mnogo sanja.',
 'sankilot': 'Revolucionar, proleter u doba francuske buržoaske revolucije 1789. (ist., fr.; obično u množini).',
 'sančić': 'Umanjenica od san.',
 'saodgovoran': 'Koji deli odgovornost s nekim, suodgovoran.',
 'sapetost': 'Stanje onoga koji je sapet; spuštanost, spletenost.',
 'sapunar': 'Onaj koji pravi sapun, sapundžija.',
 'sapunara': 'Radionica i prodavnica sapuna, sapundžinica.',
 'saraga': 'Vrsta sine, suve slatkovodne ribe, ukljeva (zool.); preneseno: veoma mršava osoba.',
 'sarka': 'Vrsta crne, divlje patke; liska (zool.).',
 'satanizovati': 'Prikazati, prikazivati kao sotonu; preneseno: (o)crniti do krajnosti.',
 'satiričnost': 'Osobina onoga što je satirično.',
 'savetodavan': 'Koji daje savet, savetuje (savetodavan odbor, organ).',
 'sažalan': 'Sažaljiv, žalostiv (sažalno oko, osmeh).',
 'scenografkinja': 'Ženska osoba scenograf.',
 'sedamdesetak': 'Približno sedamdeset, oko sedamdeset (predmeta, lica i sl.).',
 'sedamdesetogodišnjak': 'Onaj koji ima sedamdeset godina ili približno toliko.',
 'sedlarstvo': 'Sedlarski zanat.',
 'sedmoglav': 'Koji ima sedam glava (sedmoglava aždaja).',
 'sedobrad': 'Koji je sede brade.',
 'sedoglav': 'Koji je sede glave.',
 'sedra': 'Porozan, šupljikav krečnjak koji se stvara u podnožjima vodopada i drugih mesta gde se sliva voda (min.).',
 'sekanta': 'Prava koja seče krivu liniju ili površinu u najmanje dve tačke (mat., lat.).',
 'selance': 'Umanjenica od selo.',
 'selekcionirati': 'Izvršiti selekciju (selekcionirati robu, seme).',
 'seljanče': 'Umanjenica od seljanin; dete sa sela.',
 'semantičar': 'Onaj koji se bavi semantikom, stručnjak za semantiku.',
 'semenarstvo': 'Stručno ispitivanje i gajenje semena.',
 'semenica': 'Košuljica, opna u kojoj se nalazi jezgro semena.',
 'semeništarac': 'Učenik semeništa, bogoslov.',
 'semit': '(U množini) grupa naroda veoma starog porekla, srodnih po jeziku i antropološkim osobinama (starovekovni Akađani, Aramejci, Feničani i dr., danas Jevreji i Arapi); (u jednini) pripadnik te grupe.',
 'senatorstvo': 'Služba i zvanje senatora.',
 'senilo': 'Zaklon, štitnik na svetiljci radi ublažavanja jačine svetlosti, abažur.',
 'seniti': 'Zasenjivati, zaslepljivati jakom svetlošću; i isto što i senčiti; (seniti se) bivati zaslepljen, zasenjivati se.',
 'senzacionalnost': 'Svojstvo, stanje onoga što je senzacionalno, onoga koji je senzacionalan.',
 'senzitivnost': 'Svojstvo, stanje onoga koji je senzitivan, onoga što je senzitivno; osetljivost, senzibilnost.',
 'senčica': 'Umanjenica od senka.',
 'septet': 'Kompozicija za kamerni sastav od sedam pevača ili sedam svirača; kamerni ansambl od sedam izvođača (muz.).',
 'septima': 'Sedmi stepen dijatonske lestvice; interval od sedam tonova na bilo kom delu dijatonske lestvice (muz.); i strofa od sedam stihova.',
 'septičan': 'Koji gnjije, koji stvara trulež, gnoj, koji izaziva sepsu; koji sadrži zarazne klice (septična rana, angina); septička jama — posebno uređena jama za fekalije.',
 'setveni': 'Koji se odnosi na setvu (setvene površine, setveni radovi).',
 'severoistočnjak': 'Vetar koji duva sa severoistoka.',
 'sezamov': 'Koji se odnosi na sezam, koji potiče od sezama (sezamovo ulje, seme).',
 'sečka': 'Nasečena, narezana slama ili kukuruzovina kao hrana za stoku; i naprava za sečenje, sečkalica.',
 'seša': 'Nežni oblik od sestra (fam.).',
 'shema': 'Crtež koji prikazuje uređaj, mehanizam ili raspored delova nečega, plan organizacije nečega (shema ratnih rovova); prethodna skica, nacrt, prikaz nečega u glavnim, opštim crtama (shema sporazuma); i opšta, gotova šablonska formula, uzorak, obrazac (grč.).',
 'shematičan': 'Koji se zasniva na shemi (shematična rasprava); i koji je prikazan u opštim crtama, koji daje samo uopštenu sliku, apstraktan (shematičan prikaz).',
 'sidriti': 'Spuštati sidro na morsko ili rečno dno da se usidri, ukotvi brod, čamac, kotviti; (sidriti se) držati se na sidru, kotviti se (o brodu, čamcu).',
 'siga': 'Sedimentna šupljikava stena koja nastaje taloženjem rastvorenog krečnjaka u pećinama; sige stalaktiti, sige stalagmiti (lat.).',
 'sigla': 'Početna slova kojima se zamenjuje neko ime ili naziv; i znak kojim se zamenjuje slog ili reč u stenografiji (ital.).',
 'signalizirati': 'Da(va)ti signal, javiti, javljati signalom.',
 'silazan': 'Koji silazi, koji se spušta (silazna putanja, akcenat, intonacija).',
 'simplicistički': 'Koji se odnosi na simpliciste (simplicističko rezonovanje, razmišljanje).',
 'sindikalist': 'Član sindikata; i pristalica sindikalizma.',
 'sinkretizam': 'Jedinstvenost, neraščlanjivost nekog prvobitnog nerazvijenog stanja (sinkretizam prvobitne umetnosti); fil. spajanje, sjedinjavanje različitih, često nespojivih, filozofija u jedinstvenu celinu (grč.).',
 'sinoniman': 'Koji je sinonim, koji ima svojstva sinonima (biti sinoniman s nekom rečju).',
 'sinoptičar': 'Meteorolog koji proučava sinoptičke karte, stručnjak u prognoziranju vremena (grč.).',
 'sinovčić': 'Umanjenica i nežni oblik od sinovac.',
 'sintetičar': 'Onaj koji (obično u naučnom radu) primenjuje metod sinteze.',
 'sinusoida': 'Krivulja koja grafički prikazuje promene sinusa u zavisnosti od promene ugla (mat., lat.-grč.).',
 'sirnica': 'Pita sa sirom; i sud ili prostorija gde se drži sir.',
 'siromašica': 'Žena siromah.',
 'sisica': 'Umanjenica i nežni oblik od sisa.',
 'sitničavost': 'Svojstvo, osobina onoga koji je sitničav.',
 'sitnozrn': 'Sitnog zrna, koji je od materije sa izgledom sitnih zrna (sitnozrna sorta pšenice, peščar, ruda pirita).',
 'situirati': 'Rasporediti, raspoređivati, naći, nalaziti mesto za nekoga, za nešto, postaviti, postavljati nekoga, nešto negde (situirati bolnicu izvan centra).',
 'siveti': 'Postajati siv; (siveti se) biti siv, sivo se odražavati.',
 'sivka': 'Isto što i sivulja.',
 'sićušnost': 'Osobina onoga koji je sićušan, onoga što je sićušno.',
 'skadarka': 'Vrsta puške kakvu su pravili skadarski majstori (ist.); agr. vrsta loze crnog grožđa i vina.',
 'skakalište': 'Mesto za sportsko skakanje (sport).',
 'skapirati': 'Shvatiti, razumeti (razg.).',
 'skautizam': 'Skautski pokret, skautska aktivnost.',
 'skautkinja': 'Ženska osoba skaut.',
 'skelar': 'Onaj koji vrši prevoz skelom; uporedi skeleđija.',
 'skeptičnost': 'Osobina, stanje onoga što je skeptično.',
 'skladišnica': 'Pismeni dokument o smeštenoj robi u skladištu (o vrsti robe, količini i dr.).',
 'skladišnina': 'Naknada za smeštaj robe u skladištu.',
 'skliskost': 'Osobina, stanje onoga što je sklisko, klizavost.',
 'skrušenje': 'Pokajanje, skrušenost.',
 'skupljačica': 'Ona koja nešto skuplja.',
 'slalomaš': 'Učesnik, takmičar u slalomu.',
 'slavitelj': 'Onaj koji hvali, uzdiže, veliča nešto ili nekoga (slavitelji rata).',
 'slavodobitan': 'Koji je dobio, stekao slavu, pun pobedničkog ponosa (slavodobitno uzbuđenje).',
 'slavodobitnik': 'Onaj koji je stekao veliku slavu pobedivši na nekom takmičenju, onaj kome je kao pobedniku pripala slava.',
 'slavodobitno': 'Na slavodobitan, pobednički način, pobedonosno (slavodobitno ući, ponašati se, smeškati se).',
 'slavodobitnost': 'Stanje onoga koji je slavodobitan.',
 'sledbeništvo': 'Svojstvo, stanje onoga koji je sledbenik nekoga, nečega; postupak sledbenika.',
 'slezov': 'Koji se odnosi na slez, koji je od sleza (slezov čaj, boja).',
 'slip': 'Vrsta gaćica (engl.).',
 'slobodoljubiv': 'Koji voli slobodu, koji se bori za slobodu (slobodoljubiv narod).',
 'slobodoljubivost': 'Osobina onoga koji je slobodoljubiv; slobodoljublje.',
 'slugan': 'Sluga (pežorativno).',
 'sluganski': 'Koji je kao u slugana (slugansko držanje).',
 'sluganstvo': 'Sluganska osobina, poslušnost, ropska uslužnost, servilnost.',
 'sluzavost': 'Svojstvo onoga što je sluzavo.',
 'slušateljstvo': '(Zbirno) skup slušalaca, slušaoci, publika.',
 'smećkast': 'Pomalo smeđ.',
 'smežuranost': 'Svojstvo, stanje onoga što je smežurano.',
 'smokvik': 'Mesto gde rastu smokve.',
 'smrekinja': 'Smrekov plod.',
 'smrekovina': 'Smrekovo drvo (kao građa i gorivo).',
 'snatriti': 'Maštati, sanjariti (pesn.).',
 'snegovit': 'U kome pada sneg (o vremenu); koji obiluje snegom (snegovit dan; kraj).',
 'snežiti': 'Padati (o snegu).',
 'sociolingvistika': 'Grana lingvistike koja proučava vezu jezičkih i društvenih pojava, socijalnu uslovljenost jezika.',
 'sodar': 'Proizvođač soda-vode.',
 'sodoma': 'Blud, razvrat, nemoralnost (u izrazu „sodoma i gomora").',
 'sofističan': 'Koji ima svojstva sofizma (sofističan dokaz, zaključak).',
 'sokolašica': 'Ženska osoba sokolaš.',
 'sokratski': 'Kao Sokrat; mirno, sabrano.',
 'solventnost': 'Sposobnost plaćanja, platežnost.',
 'somina': 'Uvećanica i pežorativ od som.',
 'sonatina': 'Mala sonata (muz., ital.).',
 'sondaža': 'Ispitivanje, istraživanje sondama.',
 'spati': 'Isto što i spavati (pesn.).',
 'spavaći': 'Koji se odnosi na spavanje, koji je u vezi sa spavanjem (spavaća soba, kola, bolest).',
 'spekulativan': 'Koji se odnosi na spekulaciju, misaon (spekulativna metoda).',
 'spekulativno': 'Na spekulativan način, misaono.',
 'spiritus': 'Duh; dah (lat.); i vrsta grčkog nadrednog znaka, primenjivanog i u starom slovenskom pismu.',
 'spiroheta': 'Jednoćelijski mikroorganizam spiralnog oblika, izazivač sifilisa i drugih bolesti (med., grč.).',
 'splavarstvo': 'Splavarski posao, splavarenje.',
 'splavski': 'Koji se odnosi na splavove (splavski saobraćaj).',
 'spljoštenost': 'Osobina, stanje onoga što je spljošteno.',
 'sprinterica': '(Obično u množini) naročita cipela za trkače i uopšte za atletičare (engl.).',
 'sprinterski': 'Koji se tiče sprintera ili sprinta.',
 'sprčkati': 'Načiniti na brzinu, kojekako, sklepati (sprčkati ručak).',
 'sramežljivac': 'Sramežljiv čovek.',
 'sraslost': 'Stanje onoga što je sraslo.',
 'srbofilstvo': 'Privrženost Srbima, ljubav prema Srbima.',
 'srbulja': 'Rukopisna ili štampana knjiga pisana srpskoslovenskim jezikom.',
 'srdobolan': 'Koji boluje od srdobolje (dizenterije).',
 'srebrnar': 'Zanatlija koji izrađuje predmete od srebra.',
 'srednjoprugaš': 'Atletičar koji trči na srednjim stazama, naročito na 800 ili 1.500 m.',
 'sredozemka': 'Stanovnica Sredozemlja.',
 'srh': '(Najčešće u množini) osećaj praćen drhtavicom koji obuzima čoveka zbog hladnoće, straha ili uzbuđenja; žmarci, jeza.',
 'srnica': 'Umanjenica i nežni oblik od srna.',
 'stabalce': 'Umanjenica od stablo.',
 'staklarstvo': 'Zanatska delatnost koja se bavi izradom predmeta od stakla.',
 'stalaža': 'Polica (fr.).',
 'standardnost': 'Osobina onoga što je standardno.',
 'stanjivati': 'Nesvršeni oblik glagola „stanjiti"; (stanjivati se) nesvršeni prema „stanjiti se".',
 'stap': 'Uzan i visok drveni sud za mućenje maslaca.',
 'starovekovni': 'Koji pripada starom veku (starovekovna monarhija, civilizacija).',
 'stasitost': 'Osobina i stanje onoga koji je stasit.',
 'statirati': 'Biti statista.',
 'stenodaktilograf': 'Onaj koji izgovorene reči zapisuje stenografijom i to onda prepisuje na pisaćoj mašini.',
 'stenodaktilografkinja': 'Ženska osoba stenodaktilograf.',
 'stesati': 'Tešući skinuti; tesanjem smanjiti; i istesati (stesati figuru od drveta).',
 'stik': 'Čvrsto kozmetičko sredstvo u obliku valjka, namenjeno mazanju (dezodorans u stiku).',
 'stogodišnjak': 'Onaj koji ima sto godina.',
 'stolarstvo': 'Stolarski posao, zanat.',
 'stolina': 'Uvećanica i pežorativ od sto.',
 'stožernik': 'Polarni krug, uporednik (geogr.).',
 'strabizam': 'Razrokost (med., grč.).',
 'stradalnički': 'Koji se odnosi na stradalnike i na stradanje (stradalničke patnje).',
 'stradavati': 'Nesvršeni oblik glagola „stradati".',
 'strančarski': 'Koji se odnosi na strančare i strančarstvo (strančarska politika, ograničenost).',
 'strašljivica': 'Strašljiva, plašljiva osoba (obično ženska), plašljivica.',
 'strgati': 'Trgnuvši skinuti, svući (strgati pokrivač); naglim pokretom, silom odvojiti, iščupati (strgati rukav); i raskinuti, rastrgati (strgati knjigu).',
 'strmoglavljivati': '(Strmoglavljivati se) nesvršeni oblik glagola „strmoglaviti se".',
 'strmost': 'Svojstvo, stanje onoga što je strmo.',
 'strnat': 'Koji obiluje klasjem, klasa.',
 'strugalica': 'Čelično oruđe za struganje, turpijanje drveta, metala i dr., turpija.',
 'strukturirati': 'Da(va)ti strukturu, odrediti, određivati sklopu čemu (strukturirati privredu).',
 'strunja': 'Životinjska dlaka (obično kozja ili svinjska), kostret; i nit od te dlake, koja se koristi u razne svrhe (na nju se privezuju udice za pecanje ribe npr.).',
 'strusiti': 'Obresti, sresti; uporedi struniti (strusiti latice cveta); i popiti, ispiti, istrusiti (strusiti čašu vina).',
 'stubina': 'Uvećanica od stub.',
 'studentić': 'Student (pežorativno, umanjeno).',
 'studioznost': 'Osobina onoga koji je studiozan, onoga što je studiozno.',
 'stupast': 'Koji je nalik na stup, stubast.',
 'stupidno': 'Na stupidan način, glupo (stupidno reagovati, ponašati se).',
 'stupina': 'Uvećanica od stup.',
 'stupić': 'Umanjenica od stup.',
 'stupnjevati': 'Isto što i stepenovati.',
 'stupnjevito': 'Na stupnjevit način, stepenasto; postupno (stupnjevito se uzdizati; napredovati).',
 'stvaratelj': 'Stvaralac.',
 'stvarca': 'Umanjenica od stvar (pesn.).',
 'stvorić': 'Umanjenica od stvor.',
 'subaštinica': 'Ženska osoba subaštinik.',
 'subaštinik': 'Onaj koji sa nekim ima zajedničko baštinsko pravo.',
 'subpolaran': 'Koji je ispod pola, ispod polarne oblasti; subpolarni pojas — prostor od 58 do 66° geografske širine koji čini prelazni pojas od arktičkog u umereni (geogr.).',
 'subreta': 'Pevačica veselih uloga u opereti, obično sopran (fr.).',
 'subverzivnost': 'Prevratničke, rušilačke aktivnosti; subverzija (lat.).',
 'sudbenost': 'Sudska nadležnost, delokrug suda.',
 'sudelovati': 'Delovati, raditi zajedno sa nekim, imati udela u kakvom poslu.',
 'suficitaran': 'Koji je u vezi sa suficitom, koji donosi suficit (suficitarno poslovanje).',
 'sufinansirati': 'Da(va)ti zajedno s nekim novac za nešto.',
 'sugestibilan': 'Koji se lako podvrgava sugestiji, podložan sugestiji (sugestibilan stav, mišljenje).',
 'sugestibilnost': 'Osobina onoga koji je sugestibilan.',
 'sugestivnost': 'Osobina onoga koji je sugestivan, onoga što je sugestivno.',
 'suglasno': 'Isto što i saglasno.',
 'suhomesnat': 'Koji je od suvog mesa (suhomesnata roba).',
 'sukladnost': 'Osobina onoga što je sukladno, podudarnost, saglasnost.',
 'suknen': 'Koji je načinjen od sukna (suknen kaput, haljina).',
 'sukobljenost': 'Stanje onoga koji je u sukobu s nekim ili nečim.',
 'sukrivnja': 'Saučesništvo u krivici.',
 'suložnica': 'Ženska osoba suložnik.',
 'suložništvo': 'Stanje i položaj u kome se nalazi suložnik ili suložnica.',
 'sultanat': 'Zemlja u kojoj vlada sultan.',
 'sultanica': 'Sultanova žena.',
 'sultanić': 'Umanjenica i pežorativ od sultan.',
 'suma': 'Iznos dobijen sabiranjem dvaju ili više brojeva, zbir (mat., lat.).',
 'sumarnost': 'Osobina, stanje onoga što je sumarno.',
 'sumeštanka': 'Ženska osoba sumeštanim, sugrađanka.',
 'sumišljenik': 'Istomišljenik, jednomišljenik.',
 'sumnjivost': 'Osobina onoga koji je sumnjiv, onoga što je sumnjivo.',
 'sumporača': 'Šibica, žilica u kojoj ima sumpora; i prskalica za prskanje vinove loze modrom galicom.',
 'sumporov': 'Koji u sebi ima sumpora (sumporovo jedinjenje).',
 'suprotstavljenost': 'Osobina, stanje onoga što je suprotstavljeno, onoga koji je suprotstavljen nekome, nečemu.',
 'surina': 'Prost širok kaput sure boje, uporedi surka; zool. vrsta sove; i sura boja, sivilo (surina sutona).',
 'surka': 'Kraći kaput od surog sukna, ukrašen gajtanima, kao deo narodne nošnje; i kraći kaput uopšte; vrsta dugačkog radnog kaputa.',
 'suseljanin': 'Onaj koji je iz istog sela kao i neko drugi.',
 'suspenzivan': 'Koji zaustavlja, zadržava, odlaže (naročito izvršenje kazne).',
 'suspregnuti': 'Zaustaviti, zadržati, obuzdati, savladati (suspregnuti emocije); (suspregnuti se) savladati se, uzdržati se.',
 'susretište': 'Mesto susretanja.',
 'sustalost': 'Stanje onoga koji je sustao, zamor.',
 'sustanarstvo': 'Stanje sustanara; sustanarsko pravo.',
 'sustav': 'Celokupnost delova (stvari, pojmova i sl.) koji obrazuju kakvu celinu, sastav; uporedi sistem.',
 'sustavan': 'Koji je zasnovan, koji se zasniva na nekom sustavu; sistematičan, dosledan (sustavno iznošenje podataka, niz elemenata).',
 'sustavnost': 'Osobina i stanje onoga što je sustavno, sistematičnost.',
 'sutoka': 'Mesto gde se dve reke ulivaju jedna u drugu.',
 'suvad': '(Zbirno) suvo granje; uporedi suvarak, suvar.',
 'suvačar': 'Vlasnik suvače ili onaj koji radi u suvači.',
 'suzdržljivost': 'Osobina onoga koji je suzdržljiv, uzdržljivo ponašanje, uzdržljivost.',
 'suznica': 'Suzna kesica u očnoj duplji, suzna žlezda (anat.).',
 'suzovod': 'Kanal kojim otiche suzna tečnost u nosnu duplju (anat.).',
 'sućutan': 'Koji ima sućut, saosećanja; koji izražava sućut, saosećanje, saučešće (sućutan prijatelj; reč).',
 'sućutno': 'Saosećajući, saosećajno (sućutno govoriti).',
 'sušanj': 'Suvo lišće.',
 'sušionica': 'Prostorija za sušenje nečega (najčešće veša); uporedi sušara.',
 'sušičavost': 'Stanje onoga koji je sušičav.',
 'sušnica': 'Prostorija u kojoj se nešto (obično meso ili voće) suši; uporedi sušiti.',
 'suženost': 'Osobina, stanje onoga što je suženo (suženost prostora); preneseno: skučenost, ograničenost (suženost misli).',
 'svaditi': 'Izazvati svađu, stvoriti razdor, mržnju između dve ili više osoba, zavaditi, posvaditi; (svaditi se) doći u sukob, zavaditi se, posvaditi se.',
 'svagdašnjica': 'Isto što i svakidašnjica.',
 'svakodnevan': 'Koji se ponavlja iz dana u dan, koji se vrši, događa, dešava svakoga dana, svakidašnji, svadanji, redovan; koji služi za svaki dan, običan (svakodnevni izdatak, pojava; odelo).',
 'svaštariti': 'Raditi mnoge stvari, ali neozbiljno i nestručno; baviti se sitnim, slabo organizovanim poslovima (pež.).',
 'sveprisutnost': 'Osobina, stanje onoga koji je sveprisutan, što je sveprisutno; neograničeno postojanje svuda i u svemu (sveprisutnost božje ruke, ljubavi).',
 'svetlina': 'Svetlost, sjaj; otvorenost boje.',
 'svetosavlje': 'Kult svetog Save; i oblik, vid pravoslavnog hrišćanstva zasnovan na učenju svetog Save, čija su osnovna načela izneta u „Žičkoj povelji".',
 'svetosavski': 'Koji se odnosi na svetog Savu, njegovo učenje i praznik posvećen njemu (svetosavska proslava, beseda).',
 'sveučilište': 'Isto što i univerzitet.',
 'svevlast': 'Neograničena, potpuna, apsolutna vlast, apsolutizam.',
 'sveznadar': 'Onaj koji sve zna, veoma učen čovek; mudrac.',
 'sveznalaštvo': 'Osobina, stanje sveznalice; neobično veliko znanje i pamet.',
 'sviba': 'Grmolika biljka iz porodice drenova (bot.).',
 'svibovina': 'Svibovo drvo.',
 'sviralica': 'Umanjenica od svirala.',
 'sviter': 'Vunena sportska majica sa rukavima; džemper (engl.).',
 'svrabljivac': 'Šugavac.',
 'svrabljivost': 'Šugavost.',
 'svračak': 'Ptica pevačica i selica iz istoimene porodice, koja tamani miševe i insekte i nabija ih na trn (zool.).',
 'svračić': 'Umanjenica od svraka; mladunče svrake.',
 'svrbljiv': 'Koji izaziva svrbež, svrab.',
 'svrsishodnost': 'Osobina onoga što je svrsishodno, celishodnost, prikladnost, podesnost.',
 'tabelaran': 'Izložen, dat u vidu tabele (tabelarni pregled).',
 'tabetičar': 'Onaj koji boluje od tabesa.',
 'tabinja': 'Vrsta morske ribe pljosnatog tela (zool.).',
 'tabletić': 'Umanjenica od tablet.',
 'taborište': 'Mesto za taborovanje, logorište.',
 'tabula': 'Tabla, tablica (lat.); „tabula rasa" — slikovita karakteristika duhovnog stanja, svesti deteta, saglasno uverenju da čovekovu svest uobličava samo iskustvo, a ne nasleđe.',
 'tabulator': 'Deo na pisaćoj mašini ili tastaturi kompjutera koji olakšava tabelarno ispisivanje podataka.',
 'tadašnjica': 'Tadašnje doba, tadašnje vreme.',
 'tajan': 'Koji predstavlja tajnu, nepoznat, nedokučiv (tajno prostranstvo); koji se čuva kao tajnu, skriva od javnosti, koji tajno, krišom deluje (tajan sastanak, veza, organizacija); i tajanstven, zagonetan (tajna noć).',
 'tak': 'Bilijarski štap (fr.).',
 'taktizirati': 'Ostvarivati svoje ciljeve okolišno, veštinom postupanja, sprovodeći neku taktiku.',
 'talaštvo': 'Stanje u kojem se nalazi talac.',
 'taliti': 'Prevoditi u tečno stanje pomoću toplote, topiti (taliti rudu); (taliti se) prelaziti u tečno stanje pod uticajem toplote, topiti se (taliti se u peći).',
 'taljevina': 'Rastavljena materija, rastopina.',
 'taljivost': 'Osobina onoga što je taljivo, topljivost.',
 'talk': 'Vrlo mek silikatni beli ili zelenkasti mineral, primenjuje se u proizvodnji hartije, gume, lekova, u kozmetičkoj industriji i dr. (min., nem.).',
 'taložnik': 'Naročita jama, rezervoar, deo kakvog uređaja i sl. koji u kakvom procesu prerade neke materije služe za taloženje.',
 'tamburati': 'Svirati na tamburi.',
 'tangens': 'Trigonometrijska funkcija koja pokazuje odnos katete koja stoji nasuprot uglu i katete koja je uz ugao (mat., lat.).',
 'tangirati': 'Dotaći, doticati, dotaknuti; odnositi se na nekoga, nešto, ticati se nekoga, nečega (lično sam tangiran; to nas ne tangira).',
 'tanin': 'Beličastožutkast prah oporog ukusa koji se dobija iz šišarke i kore hrasta i nekih drugih belogoričnih stabala; koristi se pri štavljenju kože i u medicini (hem., fr.).',
 'tankoća': 'Osobina onoga što je tanko, tankost; prefinjenost, tananost (tankoća osećanja).',
 'tankoćutnost': 'Osobina onoga koji je tankoćutan, osetljivost, osećajnost.',
 'tantalov': 'Koji se odnosi na tantal, koji sadrži tantal, načinjen od tantala (tantalova ruda, vlakno); „tantalove muke" — v. muka.',
 'tapetarstvo': 'Tapetarski posao, tapetarski zanat.',
 'tarana': 'Testo izmrvljeno u zrnate mrvice (tur.); „izvući se kao tarana iz lonca" — neopaženo otići iz društva; vešto se osloboditi kakve obaveze.',
 'taranta': 'Vrsta guštera; i vrsta morske ribe (zool., ital.).',
 'taslak': 'Komad grubo obrađenog drveta; i neotesan blok kamena (tur.).',
 'tavica': 'Umanjenica od tava.',
 'tašizam': 'Pravac u apstraktnom slikarstvu, slikarska tehnika spontanog nabacivanja boje na platno, slično stavljanju tačaka (fr.).',
 'tažiti': 'Ublažavati, utoljavati; stišavati, umirivati (tažiti glad, žeđ; duhove).',
 'teglenica': 'Teretni plovni objekat bez vlastitog pogona koji se vezuje za tegljača; plovni objekat koji se teglji (brod.).',
 'tegobnost': 'Osobina i stanje onoga što je tegobno; tegoba.',
 'telce': 'Umanjenica od telo.',
 'telekomanda': 'Uređaj kojim se upravlja nekim aparatom, objektom na daljinu (grč.-lat.).',
 'telemark': 'Naziv za naročit pokret pri doskoku skakača u skijaškim skokovima, pri kojem se jedna noga ispruža napred radi sigurnijeg skoka; prema imenu norveške pokrajine Telemarken (sport).',
 'tenda': 'Platneni zastor za zaštitu od sunca i kiše, na terasama, plažama, brodovima i dr. (ital.).',
 'tendenciozan': 'Koji ima određenu tendenciju, preduzet s određenom namerom, koji služi izvesnoj svrsi, često u negativnom smislu (tendenciozna vest, pitanje, članak).',
 'tendirati': 'Biti sklon nečemu, biti usmeren u određenom pravcu, težiti, naginjati (Rusija je tendirala Carigradu).',
 'teoretik': 'Isto što i teoretičar (grč.).',
 'teoretizirati': 'Isto što i teoretisati.',
 'terapeutika': 'Grana medicine koja proučava metode lečenja bolesti; teorija i praksa lečenja.',
 'terasica': 'Umanjenica od terasa.',
 'tercina': 'Strofa od tri jamska stiha (knjiž., ital.).',
 'termika': 'Nauka o toploti (fiz.); i jedriličarski termin za uspon suvog vazduha pri tihom, toplom i vedrom vremenu (grč.).',
 'terminalan': 'Završni, krajnji, konačni.',
 'terminirati': 'Utvriditi, utvrđivati termin, odrediti, određivati rok.',
 'terminolog': 'Stručnjak za terminologiju.',
 'termitnjak': 'Gnezdo, mravinjak termita; uporedi termit.',
 'termodinamički': 'Koji se odnosi na termodinamiku, zasnovan na principima termodinamike.',
 'termograf': 'Meteorološki instrument koji automatski grafički beleži kretanje temperature vazduha (fiz., grč.).',
 'tetkić': 'Tetkin sin, brat od tetke.',
 'tetrebica': 'Ženka tetreba.',
 'tezaurus': 'Blago, dragocenosti, riznica; i veliki rečnik u kojem je skupljeno i opisano jezičko blago nekog jezika; velika enciklopedija (grč.).',
}

C = {
 'selina': 'glosa pogrešno uhvaćena (tuđa odrednica); značenje nejasno',
 'seline': 'glosa pogrešno uhvaćena (tuđa odrednica); značenje nejasno',
 'Skopja': 'makedonski oblik; standardno „Skoplje" — Matica toponim ne vodi, vlasnica odlučuje',
 'Skopje': 'makedonski oblik; standardno „Skoplje" — Matica toponim ne vodi, vlasnica odlučuje',
 'Skopjem': 'makedonski oblik; standardno „Skoplje" — Matica toponim ne vodi, vlasnica odlučuje',
 'Skopjima': 'makedonski oblik; standardno „Skoplje" — Matica toponim ne vodi, vlasnica odlučuje',
 'Skopju': 'makedonski oblik; standardno „Skoplje" — Matica toponim ne vodi, vlasnica odlučuje',
 'Skoplja': 'oblik grada Skoplja; Matica ne vodi toponim (u rečniku „Skoplje": glavni grad Severne Makedonije) — vlasnica odlučuje',
 'Skopljem': 'oblik grada Skoplja; Matica ne vodi toponim — vlasnica odlučuje',
 'Skopljima': 'oblik grada Skoplja; Matica ne vodi toponim — vlasnica odlučuje',
 'Skoplju': 'oblik grada Skoplja; Matica ne vodi toponim — vlasnica odlučuje',
 'slanutak': 'glosa samo uput (OCR-nečitljiv) — nesigurno',
 'sranje': 'vulgarno (na blok-listi generatora); rečnik takve reči ne vodi',
 'stališe': 'glosa nejasna iz konteksta; značenje nesigurno',
 'stališi': 'glosa nejasna iz konteksta; značenje nesigurno',
 'stipi': 'glosa fragmentarna; značenje nejasno',
 'stošom': 'glosa fragmentarna (deo odrednice „puritanizam"); značenje nejasno',
 'sugradica': 'glosa OCR-nečitka — nesigurno',
 'sud': 'standardna reč (sud, sudnica), ali odrednica u OCR-u nije locirana/čitljiva — vlasnica odlučuje',
 'suda': 'standardna reč (gen. od „sud"); odrednica u OCR-u nije locirana — vlasnica odlučuje',
 'taca': 'glosa fragmentarna; značenje nejasno',
 'tariši': 'glosa fragmentarna; značenje nejasno',
 'taši': 'glosa fragmentarna; značenje nejasno',
 'ter': 'glosa fragmentarna (deo odrednice „raščistiti"); značenje nejasno',
}
